### ISSUE TITLE
Image as base64 to style background-image:url() issue

### ISSUE THREAD

**Issue by MichaelSamteladze** [apache/cordova-plugin-camera#327]
If you have following setup:

```
navigator.camera.getPicture(
            SuccessCallback,
            ErrorCallback,
            {
                quality: 40,
                destinationType: Camera.DestinationType.DATA_URL,
                encodingType: Camera.EncodingType.JPEG,
                sourceType: Camera.PictureSourceType.PHOTOLIBRARY,
                correctOrientation: true,
                cameraDirection: Camera.Direction.FRONT
            }
        );
```

and

```
OnTakePictureSuccess: function (ImageBase64) {
ImageBase64 = 'data:image/jpeg;base64,' + ImageBase64
$(Selector).attr('style', "background-image:url('" + ImageBase64 + "')");'');
    }
```

Displays empty image, but if you replace some whitespaces and newlines in Base64 then it works

```
ImageBase64 = 'data:image/jpeg;base64,' + ImageBase64.replace(/\r?\n|\s{1,}/g, '');
```

Problem found on iOS 9 and Android 6.

**Comment by janpio** [comment]
Are you saying the base 64 image date being returned from `getPicture` is broken?

**Comment by MichaelSamteladze** [comment]
Yes data is not quite accurate.

**Comment by janpio** [comment]
Does this only affect `background-image:url( ... )`?
Does this also happen in other OS versions?

**Comment by MichaelSamteladze** [comment]
Yes it only affected background-image, to be honest I didn't try other iOS versions, this also happened in android 6

**Comment by janpio** [comment]
Does this make sense to you that it only affects `background-image`, but not other uses?

**Comment by janpio** [comment]
I don't really know what you are reacting to, I asked a simple question trying to understand the issue further.

**Comment by MichaelSamteladze** [comment]
Sorry if was tough.

Initially it was strange, cause I stored result returned from OnTakePictureSuccess in a variable and printed it out.

I took printed result to test it locally in my test HTML file.

Printed result had newlines, so I thought it was browser formating and I formatted result in html minifiers.

I tried minified in <img src="Base64" /> it worked and also tried it in <div style="background-image:url(Base64)"></div> also worked.

Initially I did not realized that html minifier fixed an issue.
After I tried original result in img and it worked, then I tried it via div and here I caught a problem.

**Comment by janpio** [comment]
As you know what is going on, can you create a super simple app with `cordova create` and implement just what is necessary to show the problem? Put it on Github, so someone from Cordova can have a look at it when there is the time.

**Comment by MichaelSamteladze** [comment]
Sure, I will take care and I'll update this thread with link

**Comment by MichaelSamteladze** [comment]
Here is my sample project that failed on my iPad 2, iOS 9.3.1

https://github.com/MichaelSamteladze/CordovaCameraPluginV4.0.3Problem

**Comment by fracon** [comment]
Hey guys after spent a few days trying to find out why we our app's camera didn't work well in iOS we realize yesterday (November, 26) that we are facing exactly the same problem reported by @MichaelSamteladze. After spent some minutes searching for ocurrencies i found this bug reported and some others threads with people reporting problems with camera but without know that is the exactly problem so as @MichaelSamteladze said i think fix this bug could save a lot of time and stress from other developers. 

As information, we are using the 4.0.3 plugin version.

@MichaelSamteladze thanks for the workaround.

**Comment by breautek** [comment]
Cannot reproduce on modern versions

```
document.body.onclick = () => {
        navigator.camera.getPicture((e) => {
            console.log(e);
            document.body.style.backgroundImage = `url("data:;base64,${e}")`;
        }, (e) => {
            console.error(e);
        }, {
            destinationType: navigator.camera.DestinationType.DATA_URL
        });
    };
```

Also works if you specify the JPEG mimetype, but you'll need to guarentee if the data is an actual jpeg encoded image.
