### ISSUE TITLE
Trouble using plugin in VueJS context

### ISSUE THREAD

**Issue by humblecoder** [apache/cordova-plugin-camera#328]
Having serious trouble making use of the plugin in the browser.  I am not explicitly calling `onDeviceReady` anywhere, because I'm not sure where it makes sense in a Vue context.  That said, I have the following method being called in a `@click` event (using ES6):

```
picFromCamera(){
      console.log(navigator.camera)
      navigator.camera.getPicture(
        (data)=>{
          console.log(data)  //NOTHING HAPPENING, NOT GETTING FIRED?
        },
        (err)=>{console.log(err) //NOTHING HAPPENING, NOT GETTING FIRED?}, 
	{
    		sourceType:Camera.PictureSourceType.CAMERA,
	        quality:50,
    		destinationType:Camera.DestinationType.DATA_URL,
        	// popoverOptions: new CameraPopoverOptions(300, 300, 100, 100, Camera.PopoverArrowDirection.ARROW_ANY)
    	});
    },
```

The console successfully outputs the `navigator.camera` object, however it doesn't appear that `getPicture()` does anything.  I receive no errors or feedback of any sort.

I am running the following commands in order to ensure that anything I might be missing is getting built and served:

```
qvn2018 yarn run build && cordova build && cordova serve
```

I have the following versions installed:

```
node --version
v8.11.4
yarn --version
1.9.4
cordova --version
8.0.0

cordova platform ls
Installed platforms:
  browser 5.0.4
  ios 4.5.5
```

**Comment by janpio** [comment]
As far as I know you have to `cordova run browser` to activate the browser platform, `serve` is just a local webserver for your `www`.

**Comment by humblecoder** [comment]
Well, that was amazingly helpful.  I could probably do with reading the docs more deeply, however, it might be nice if that distinction was much more obvious by the Cordova crew.  Thanks!

**Comment by janpio** [comment]
Sounds valid. We would appreciate it if you could send a Pull Request for the docs at the appropriate location! Thanks.
