### ISSUE TITLE
Exif data lost when correctOrientation is true

### ISSUE THREAD

**Issue by ddsky** [apache/cordova-plugin-camera#329]
The image I retrieve in the success callback has proper exif data if I set the options to:
```
 let options = {
    sourceType: Camera.PictureSourceType.CAMERA,
    destinationType: Camera.DestinationType.FILE_URI
};
```

Once I use `correctOrientation` (or quality, or targetHeight or targetWidth) in the options, the exif data is lost:
```
 let options = {
    correctOrientation: true,
    sourceType: Camera.PictureSourceType.CAMERA,
    destinationType: Camera.DestinationType.FILE_URI
};
```

**Comment by ddsky** [comment]
Sorry for not posting this information right away!

cordova-android 7.0.0
cordova-plugin-camera: 4.0.3

I'm building this via yarn/npm latest version on Windows and Linux.

**Comment by ddsky** [comment]
Thanks for the info. I updated to 7.1.1 but it made no difference. I tested this on multiple devices with Android 6.0.

**Comment by ddsky** [comment]
@janpio that would be my guess too. Who can solve this though?

**Comment by AlvaroHerrero** [comment]
I think we need to call
exifData.readExifData();
just after
exifData.createInFile(filePath);
This way the original exifData data will be on the helper before re-saving them on the rotated file.

**Comment by ddsky** [comment]
Thanks @AlvaroHerrero that sounds like the right path. Please note that this does not only happen if `correctOrientation` is set to true but also if `quality`, `targetWidth`, or `targetHeight` is set. I guess whenever the image is manipulated and re-saved.

**Comment by AlvaroHerrero** [comment]
Yes, it also happens when the image is selected from the gallery.

**Comment by ddsky** [comment]
Is there a roadmap on when this might be fixed?

**Comment by janpio** [comment]
Please create a Pull Request that fixes this on this repository, then this can be reviewed, merged and finally released.

**Comment by AlvaroHerrero** [comment]
The PR is already created. I don´t know if there is something more for me to do.
https://github.com/apache/cordova-plugin-camera/pull/331

**Comment by janpio** [comment]
Linking to the PR here and to this issue in the PR would be a good thing ;) With a few hundred issues and PRs per day, this is the only way to get the connetions :)

Well, then we'll have to wait for more people to review the PR - that actually know about Android and Java etc. Feel free to test the changes @ddsky and leave an "Approve" review on the PR if everything works as expected.

**Comment by ddsky** [comment]
@janpio, sorry I'm new to this. How do I test the PR? Wouldn't it need to be merged so I can update to the latest version of the plugin in my app to test it?

**Comment by janpio** [comment]
You can install the PR branch directly as your plugin: https://github.com/AlvaroHerrero/cordova-plugin-camera/tree/GH-329 (`cordova plugin add https://github.com/AlvaroHerrero/cordova-plugin-camera/tree/GH-329` should work)

**Comment by ddsky** [comment]
@janpio installing this plugin like so does not seem to work for me

```
> cordova plugin add https://github.com/AlvaroHerrero/cordova-plugin-camera/tree/GH-329
(node:27864) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin https://github.com/AlvaroHerrero/cordova-plugin-camera/tree/GH-329 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
```
Anything I'm doing wrong?

**Comment by janpio** [comment]
No, I gave you the wrong command. Sorry.
```
cordova plugin add https://github.com/AlvaroHerrero/cordova-plugin-camera.git#GH-329
```
should work

**Comment by ddsky** [comment]
Super, thank you @janpio, that worked.

I can hereby confirm that rescaling and keeping the exif data now works properly. 

What is the process from here, when will this be in the main branch?

**Comment by janpio** [comment]
Leave that comment on the PR https://github.com/apache/cordova-plugin-camera/pull/331 please.

Someone from Apache Cordova will have to decide if this is a useful change, test and review it, then merge it. Then it will be included in the next release, whenever that will happen.

**Comment by ddsky** [comment]
Thanks, I have done that.

**Comment by HarelM** [comment]
I've just tested the code using the instructions #415 and I still see an issue with exif data getting lost when getting images from the photo library on android device.
The code I'm using is the following:
`navigator.camera.getPicture(() => ..., { destinationType: Camera.DestinationType.DATA_URL, sourceType: Camera.PictureSourceType.PHOTOLIBRARY, saveToPhotoAlbum: false}).
Code can be seen here:
https://github.com/IsraelHikingMap/Site/blob/d81cfdfd339060aab9b512352741b5af00c8a214/IsraelHiking.Web/sources/application/directives/image-capture.directive.ts#L41
Let me know if there's a way I can help or if I need to open a new issue for this.
Thanks for a great plugin! Keep up the good work.

**Comment by janpio** [comment]
Best open a new issue - otherwise this mgiht get lost here. (Please include a link back to this here of course for context) Thanks.

**Comment by HarelM** [comment]
@janpio I opened #452. Thanks for the quick response!
