### ISSUE TITLE
On Android an empty string is returned when selecting a video from the photo library

### ISSUE THREAD

**Issue by hebra** [apache/cordova-plugin-camera#330]
With version 4.0.3 the plugin returns an empty string instead of the file URI when selecting a video from the photos library. When selecting a photo, everything works fine.

**Comment by janpio** [comment]
What Android version are you testing on?
What version of the Cordova Android platform do you have installed?
Did it work with plugin version 4.0.2?

**Comment by hebra** [comment]
- Android 7.1.1
- SDK version 25
- Cordova 8.0.0
- Cordova Android 7.0.0 and 7.1.1 (both not working)
- 4.0.2 of the plugin is also not working

In addition I am using Ionic 4 Beta with Angular 6. There is already a ticket tracked regarding this matter in the Ionic Native Github with the note that the issue itself is caused by the cordova plugin:
https://github.com/ionic-team/ionic-native/issues/1721

There is also a probably related pull request:
https://github.com/apache/cordova-plugin-camera/pull/198

**Comment by janpio** [comment]
Can you share a minimal project (`cordova create` or `ionic start`, then implement just enough to demonstrate the problem) on GitHub? 

The PR doesn't look like a 100% match, but it's worth investigating.

**Comment by hebra** [comment]
Find a demo project in my GitHub:
https://github.com/hebra/cordova-plugin-camera-issue-330

It is an Ionic 4 project, to build you need the Ionic 4 Beta CLI tools installed, e.g. via `npm install -g ionic`

To build an APK you'll need an Android SDK in your path (right now the minimum required is 25. Also Java 8 JDK has to be installed.

The camera logic itself is in `home.page.html` and `home.page.ts`

To build run `ionic cordova build android`.

**Comment by janpio** [comment]
Awesome.

Note to whoever takes a look at this: This also uses an Ionic Native wrapper in between the Cordova plugin and the actual application that could be source for the problem.

**Comment by jcesarmobile** [comment]
I couldn't reproduce on the sample app with cordova-android 7.1.4

Tested on Android 8.1 and Android 7.0 devices

**Comment by uspasojevic96** [comment]
This issue is not reproducible on emulator, but on real device path is empty string

**Comment by vishwanath1004** [comment]
HI Team, am also facing the issue, can anyone suggest or help me
