### ISSUE TITLE
destinationType return wrong value type

### ISSUE THREAD

**Issue by cikcoh** [apache/cordova-plugin-camera#333]
const options: CameraOptions = {
      quality: 100,
      destinationType: this.camera.DestinationType.DATA_URL,
			sourceType: this.camera.PictureSourceType.PHOTOLIBRARY,
      mediaType: this.camera.MediaType.ALLMEDIA
    }
 when i get picture/video from gallery it returns data in file_uri instead of base64.
 if i get a new picture from camera the, it return base64.

**Comment by janpio** [comment]
What platform?
What versions?

Does the documentation say otherwise?

**Comment by cikcoh** [comment]
"cordova": "^8.0.0",
    "cordova-android": "6.4.0",

the documentation stated that it will return base64 if destinationType set to DATA_URL

**Comment by janpio** [comment]
And the version of the plugin? And the device you are testing on? And the version of the OS on the device you are testing on?

**Comment by cikcoh** [comment]
"cordova-plugin-camera": "^4.0.3",
Redmi 4X
Android Version 7.1.2 N2G47H
