### ISSUE TITLE
Take picture removes wake lock in iOS

### ISSUE THREAD

**Issue by LarsBocons** [apache/cordova-plugin-camera#335]
I use cordova-plugin-powermanagement to prevent the device to go to sleep, but it seems that taking a picture removes that screen lock. It's only on iOS and only if you take a picture. Not when you grab one from the library. 
I have done a workaround, aquiring screen lock again right after picture was taken, but surely this must be a bug?

I'm using version 4.0.2 of the camera plugin, 
Cordova iOS version 4.5.4, and iPhone 5 + iPhone X.

**Comment by jcesarmobile** [comment]
The camera component changes the IdleTimerDisabled value, that is something we don't control and can't change its behaviour, so there is nothing we can do. You'll have to continue with your workaround.
