### ISSUE TITLE
On android it opens the a recent folder

### ISSUE THREAD

**Issue by Ross-Rawlins** [apache/cordova-plugin-camera#338]
I have copied all of the example code and I have used this plugin countless times, but on a new install when I call teh camera it opens a recent's folder then the camera. 

I am running the latest version on android 7.1.0. This configuration works fine in all my other apps.

**Comment by bleiburger** [comment]
Hi Ross-Rawlins. Did you solve your problem? i have the same problem.

**Comment by djimmo** [comment]
I also have this issue. I want to open the camera, but instead the photo folder is opened first, then the camera is opened, and finally the photo selected in the photo folder is used.

Hardware used:
Moto G5 with Android 8.1.0

**Comment by kopitar** [comment]
Hi,
Anyone found a solution to this issue yet? (testing on Android 5, 7 ,8)

**Comment by breautek** [comment]
Stale
