### ISSUE TITLE
FILE URI Not showing in <img> tag - Android

### ISSUE THREAD

**Issue by tmk1991** [apache/cordova-plugin-camera#340]
When selecting an image from the users library, the file URI returns `/storage/emulated/0/Pictures/IMG_20180911_114705.jpg`

When taking a picture it returns
`file:///storage/emulated/0/Android/data/com.app/cache/1536682152687.jpg`

Neither image shows up in the img tag when setting its source to either location.

I get the mini broken link icon where the img tag is

**Comment by q735423841** [comment]
How did you solve this problem?

**Comment by tmk1991** [comment]
Still open. Have not solved.

**Comment by q735423841** [comment]
> Still open. Have not solved.

I found one thing，i installed the corodva-plugin-carmea and build android，when i run the app on an android phone, the carmea right did not open in settings.Then the console print not allowed load the resource. Did you have this same problem?

**Comment by tmk1991** [comment]
Nope :(

**Comment by jcesarmobile** [comment]
I can't reproduce with this code:

```
navigator.camera.getPicture(function(url){
            console.log(url);
            var img = document.getElementById("result");
            img.setAttribute("src", url);
        }, function(err){
            console.log(err);
        },
            {
                destinationType: Camera.DestinationType.FILE_URI,
                sourceType: Camera.PictureSourceType.PHOTOLIBRARY
            });
```

And this img tag in my index.html
`<img id="result" src="">`

**Comment by shijunti19** [comment]
有人解决吗
How to solve it?

https://ionicframework.com/docs/wkwebview/

import { normalizeURL } from 'ionic-angular';

we need normalizeURL

**Comment by jcesarmobile** [comment]
That doesn’t work at the moment, try just using window.Ionic.WebView.convertFileSrc
