### ISSUE TITLE
Can't select a picture with a size of 5MB or more on Android

### ISSUE THREAD

**Issue by htrinhq** [apache/cordova-plugin-camera#344]
Hi,
When i want to select a photo from SAVEDPHOTOALBUM, it seems that i can't select a picture with a size of 5MB or more on android, while it works perfectly on iOS.
I'm working on Ionic 3.20.0
with the cordova-plugin-camera 2.4.1
cordova 8.0.0
android 6.4.0

For both Android and iOS i'm using the same Camera Options, whiche are:
`quality: 100,
 allowEdit: true,
 sourceType: sourceType,
 correctOrientation: true,
 destinationType: this.camera.DestinationType.FILE_URI,
 encodingType: this.camera.EncodingType.JPEG,
 mediaType: this.camera.MediaType.PICTURE`

**Comment by janpio** [comment]
What happens if you do select such a picture?

> android 6.4.0
> cordova-plugin-camera 2.4.1

Your Cordova tooling seems to be out of date, which might be causing all kinds of problems. 
You can read about how to figure out the current Cordova versions and how to update CLI, platforms and plugins here: https://ionic.zone/cordova/update

As the current version of this plugin is `4.0.3`, I don't think it makes too much sense to debug this very old version of yours. Please update.

**Comment by janpio** [comment]
Depending on the Android version of the device or emulator you are using to test, of course it might be related to the use of Cordova Android 6.4.0. 

We also can't support old versions, so the only way to decide if this is an actual bug to investigate is for you to confirm that it exists in the most recent Cordova Android 7.1.1.

**Comment by htrinhq** [comment]
All right, I keep you updated, this update can take a while since it's a big project.
Thanks for your answers!

**Comment by janpio** [comment]
(Maybe it's quicker and simpler to just create a new project with `cordova create`, add the appropriate platform and plugins, then implement a minimal UI to test this behavior. This would also be the perfect reproduction sample if someone wants to look at this bug in the future.)

**Comment by sks30** [comment]
Same issue even i am facing for my code.Please let me know the workaround to fix this issue.

**Comment by timbru31** [comment]
Closing due to lack of feedback and a minimal reproduction repository (More information on how to create one in case anyone wants to pickup this stale issue: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md
