### ISSUE TITLE
saveToPhotoAlbum doesn't save image

### ISSUE THREAD

**Issue by HarelM** [apache/cordova-plugin-camera#346]
Image is not stored to my DCIM folder on my device nor it shows in my gallery app even though `saveToPhotoAlbum` is set to `true`.
Android, xiomi redmi 4.
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/sources/application/directives/image-capture.directive.ts

**Comment by accttech** [comment]
I think the problem is  `saveToPhotoAlbum `. Try removing this and the photo will be saved to the app's cache. I am having the same issue. I think we need to find a way to move the cached photo to a persistant storage.

**Comment by HarelM** [comment]
I have tried removing it and got the same results... :-/

**Comment by eeerrrttty** [comment]
Up.

**Comment by PieterVanPoyer** [comment]
@HarelM  sorry for the late reply, is this issue still happening with the latest plugin version?

**Comment by HarelM** [comment]
I'm using version 5.0.1 on android 9 and the image is getting saved somewhere so I can see it using photo app.
I don't know if it works for android 10 and 11 which have more strict rules related to storage...

**Comment by PieterVanPoyer** [comment]
I am closing this one for now. There are some report regarding sdk30. 
If you have troubles with Android 10 or 11 and this plugin, please file another issue later.

**Comment by PieterVanPoyer** [comment]
FYI: version 5.0.2 has been released the previous week. Just a minor bug fix.
