### ISSUE TITLE
getPicture() returns empty filePath when file from SD Card selected

### ISSUE THREAD

**Issue by sacav1** [apache/cordova-plugin-camera#347]
Hi,

When I want to select a file from files library on Android 8.0, everything works when I select a file from internal memory but when I select a file from the SD Card the function getPicture() returns an empty filePath. No error triggered, I enter on the success calback.

I'm working on Ionic 3.20.0 with the cordova-plugin-camera 4.0.3

The permissions READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE are granted.

Any idea ?

Thanks

**Comment by Maraket** [comment]
I can confirm this, also if the file is from a google drive path (which is in the selection available paths) it also pass' an empty string

**Comment by Maraket** [comment]
Alright so I've looked into this further, and found the issue comes down to here:
https://github.com/apache/cordova-plugin-camera/blob/master/src/android/FileHelper.java

Basically since the file is not on the local file system the code to handle this hasn't been added yet

**Comment by Maraket** [comment]
A suggestion would be to include / merge with https://github.com/hiddentao/cordova-plugin-filepath/blob/master/src/android/FilePath.java which seems to get the path necessary. There was a pull request which would default to the URI using too string (pull 198 i think), but using the logic from the plugin would likely be a more complete solution

**Comment by janpio** [comment]
Would you be up to adding the logic from the plugin you used in a Pull Request @Maraket? Sounds like a good idea.
