### ISSUE TITLE
possible to use portrait (or other modes) on iOS?

### ISSUE THREAD

**Issue by jamesdixon** [apache/cordova-plugin-camera#348]
iOS allows for a really great "portrait" mode (not to be confused with portrait orientation). Is it possible to access any of these modes via the plugin?

**Comment by jamesdixon** [comment]
Following up here on a similar note that iOS 12 provides effects. Any way to allow cordova camera to access those as well? 

Thank you!

**Comment by jcesarmobile** [comment]
The plugin uses `UIImagePickerController`, which doesn't allow any of this.
