### ISSUE TITLE
Get Image File URL and Convert to Base64

### ISSUE THREAD

**Issue by mino922** [apache/cordova-plugin-camera#349]
I am trying to upload an image and display it by getting the FILE_URI. This works great, but I also need to get the base64 value of the same image and send it to our server.

I tried using the DATA_URL, but I am unable to display the base64 encode string as an image. I am running Ionic 3 and was running into unsafe URL warnings from angular, but after getting around those the image still does not display.

Any ideas on how to achieve this?

**Comment by jcesarmobile** [comment]
For displaying the base 64 string you have to do something like in the example provided

```
function cameraCallback(imageData) {
   var image = document.getElementById('myImage');
   image.src = "data:image/jpeg;base64," + imageData;
}
```

notice the `data:image/jpeg:base64,` part
