### ISSUE TITLE
camera androdi

### ISSUE THREAD

**Issue by SmallProgramIndustry** [apache/cordova-plugin-camera#350]
Android photos sometimes flash back, but why? Is it due to poor performance?
安卓拍照“少数情况”会闪退，这是什么原因造成的呢?是否手机性能不够导致的？

**Comment by SmallProgramIndustry** [comment]
In rare cases, the APP crumbles when you take a photo
My APP project  Technical support
ionic3.20 + angular 5.2
The android mobile phone

**Comment by SmallProgramIndustry** [comment]
Ionic:

   ionic (Ionic CLI)          : 4.1.1
   Ionic Framework            : @ionic/angular 4.0.0-beta.2
   @angular-devkit/core       : 0.7.2
   @angular-devkit/schematics : 0.7.2
   @angular/cli               : 6.1.2
   @ionic/ng-toolkit          : 1.0.5
   @ionic/schematics-angular  : 1.0.4

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (5 plugins total)

System:

   NodeJS : v10.9.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.0
   OS     : Windows 10

**Comment by SmallProgramIndustry** [comment]
Ionic:

   ionic (Ionic CLI)  : 4.1.2 (C:\Users\ASUS\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.5.2
   @ionic/app-scripts : 2.0.2

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 6.3.0
   Cordova Plugins       : no whitelisted plugins (26 plugins total)

System:

   NodeJS : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10

**Comment by janpio** [comment]
Your Cordova tooling seems to be out of date, which might be causing all kinds of problems. 
You can read about how to figure out the current Cordova versions and how to update CLI, platforms and plugins here: https://ionic.zone/cordova/update

Same with Ionic Framework and most importantly app-scripts. You should really update this.
