### ISSUE TITLE
Getting error in getPicture function

### ISSUE THREAD

**Issue by arupnayak** [apache/cordova-plugin-camera#351]
I am getting the below error while invoking getPicture function
length=1; index=1

"@ionic-native/camera": "^4.5.3",
"cordova-plugin-camera": "^4.0.2",

**Comment by janpio** [comment]
What platform? What platform version?
What OS version? What device?
What is the exact code you are invoking?

**Comment by arupnayak** [comment]
> What platform? What platform version?
> What OS version? What device?
> What is the exact code you are invoking?

Hi @janpio I am building an ionic app. There were some provider config missing in AndroidManifest.xml
After adding the issue got resolved. Hence, closing the issue.

**Comment by Owlbertz** [comment]
@arupnayak Could you please describe how you resolved that issue? I am facing the same problem.

**Comment by WanQiane** [comment]
I am getting the same error while invoking getPicture function,and I solved it finally.
Firstly,I build an app with cordova-plugin-camera alone and it worked well.
Secondly,I build an app with cordova-plugin-camera and many other plugins ,it crashed with error: length=1; index=1
Then I find that many plugins uesd FileProvider ,but the value of android:authorities are same. 
I changed this value and it‘s working.

**Comment by gonself** [comment]
hi!
@WanQiane  can you describe step by step?
thanks in advanced

**Comment by WanQiane** [comment]
I'm sorry to reply you so late.The problem I meet has nothing to do with
plugin of cordova-plugin-carema. It is mainly caused by multiple plugins
using fileprovider registered with the same name in the file named
'AndroidManifest .xml'.

Sorry to bother you  and thank you for your letter.

gonself <notifications@github.com> 于2020年10月1日周四 下午10:21写道：
