### ISSUE TITLE
表格类图片模糊

### ISSUE THREAD

**Issue by Jeijie** [apache/cordova-plugin-camera#359]
发现部分手机拍照表格类图片模糊

代码：
var options = {
                quality: 100,
                targetWidth: 800,
                targetHeight: 800,
                destinationType: Camera.DestinationType.FILE_URI,
                sourceType: Camera.PictureSourceType.PHOTOLIBRARY,
                allowEdit: false,
                popoverOptions: CameraPopoverOptions,
                saveToPhotoAlbum: false
              };

           $cordovaCamera.getPicture(options).then(function (res) {
                  //xxxx

                  }
                }, function (err) {
              
![wht tz4 up9mtp_l6 35c](https://user-images.githubusercontent.com/9338052/47195068-c93e8500-d38c-11e8-9643-72a595dcacee.png)

**Comment by jcesarmobile** [comment]
Please, report the issues in English.
Tried using google translate, but still not clear what's the issue
