### ISSUE TITLE
Android 7.1.2 app crashes or "Unable to create bitmap!" when calling camera from work profile app

### ISSUE THREAD

**Issue by martinsomm** [apache/cordova-plugin-camera#360]
Dear team, first of all thanks for maintaining this fantastic plugin 👍

We experience an issue with the 4.0.3 plugin version in an app delivered with Microsoft Intune. The app is only available in Android work mode, when work profile is switched on.

When starting the camera, we get a message toast "**you're using this app outside of your work profile**". The camera opens and we can take a picture.

Then depending on destinationType the following happens:
- DATA_URL: the app stops/crashes without any message
- FILE_URI: we return to the app and the value we get in success callback is "**Unable to create bitmap!**"

We had some Microsoft people having a look at the FILE_URI version and this is their feedback:

The debugger informs in the beginning of the logs that the crash was due to “**Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference**”
```
10-22 10:46:45.771 32379 32379 E AndroidRuntime: FATAL EXCEPTION: main
10-22 10:46:45.771 32379 32379 E AndroidRuntime: Process: com.aaa.bbb, PID: 32379
10-22 10:46:45.771 32379 32379 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=33, result=-1, data=null} to activity {com.aaa.bbb/com.aaa.bbb.Test}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference

 10-22 10:46:45.771 32379 32379 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
```

I read all the logs from the end and going up and found a few errors:

```
10-22 11:55:33.184  6106  6135 D StrictMode: StrictMode policy violation: android.os.StrictMode$StrictModeDiskReadViolation: policy=65599 violation=2

10-22 11:55:33.184  6106  6135 D StrictMode:  at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1438)

10-22 11:55:34.139  3670  7369 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
```

We appreciate your consideration in this matter
Best Regards

**Comment by epetre** [comment]
We are experiencing this issue too.

**Comment by breautek** [comment]
Sorry that this issue hasn't received any attention.

`cordova-android@7.1.2` is severely out-dated now. If you're experiencing this issue, I would suggest updating to the latest version available on both the plugin and the platform, which at the time of writing, these are versions 4.1.0 and version 9.0.0 respectfully.

If you still experience the issue on the latest releases, then please do open a new issue with the issue form filled out.

**Comment by rashnk** [comment]
same issue occured today in cordova android12
