### ISSUE TITLE
Camera permission

### ISSUE THREAD

**Issue by shreyaspb** [apache/cordova-plugin-camera#362]
I am seeing this alert when I call function to take picture instead of the custom usage description specified in the plugin.xml

Also, the Camera permission by default is set to 'Denied' in App's settings.

![img_0207](https://user-images.githubusercontent.com/44608167/47717559-19122b80-dc6c-11e8-8a51-3187d9d62070.PNG)

**Comment by jcesarmobile** [comment]
You probably used the id of another app where the permission was denied and you overwrote it.
