### ISSUE TITLE
EncodingType PNG or JPEG returns incorrect file size

### ISSUE THREAD

**Issue by robertovanderlinden** [apache/cordova-plugin-camera#366]
When I specify the option encodingType to JPEG and select a PNG file, the file size is incorrect. 
This also applies the other way around. If the selected image file type is the same as the encoding, the file size is correct.

Is it possible to dynamically set the encodingType based on the selected image? Or is there a bug in the code? I'm testing this on Android

**Comment by hazems** [comment]
Do you have a code sample of exactly what you are trying to achieve?

**Comment by breautek** [comment]
Stale
