### ISSUE TITLE
Unable to open Front camera in ANDROID

### ISSUE THREAD

**Issue by prashant-93** [apache/cordova-plugin-camera#367]
Hi,

I was trying to implement the camera plugin in ionic 3. and i want to open the front camera by default or any method by which we can flip the camera on some user action.
I am using the following camera options;
`this.cameraoptions = {
      quality: 50,
      destinationType: this.camera.DestinationType.DATA_URL,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE,
      correctOrientation: true,
      sourceType: this.camera.PictureSourceType.CAMERA,
      cameraDirection: 1,
    }`
 
After setting the cameraDirection to 1 it still opens the back camera. Is there any identifier by which I can detect the image captured is from front camera or not.

**Comment by vishakhag6** [comment]
Yes, I am also facing the same problem but unable to find anything.

**Comment by jcesarmobile** [comment]
On Android only back camera works, it's on [the docs](https://github.com/apache/cordova-plugin-camera#android-quirks-1)

**Comment by brodybits** [comment]
PR to fix this would be nice

**Comment by jcesarmobile** [comment]
There is a way of making it work, but it's not documented and doesn't work on all devices, so I don't think it should be added.

Other way would be to use Camera API instead of an Intent, but that would need a full plugin rewrite.

**Comment by gigonzalezs** [comment]
I alreade fix this issue. Pushing PR very soon.

**Comment by sonikdesign** [comment]
Hi all. Are there news about open front camera in Android?
