### ISSUE TITLE
Android not respecting destType of FILE_URI

### ISSUE THREAD

**Issue by jliddev** [apache/cordova-plugin-camera#368]
when using the below settings android will always return the DATA_URL and not the FILE_URI

sourceType: PHOTOLIBRARY
destinationType: FILE_URI
mediaType: PICTURE

Line 710 in CameraLauncher.java always sends back the data url.

changing it to the below works.

if( destType == FILE_URI ){
  this.callbackContext.success(fileLocation);
} else {
  this.callbackContext.success(uriString);
}

**Comment by janpio** [comment]
Could you submit the suggested change as a Pull Request please? Thanks.

**Comment by jliddev** [comment]
PR Submitted [https://github.com/apache/cordova-plugin-camera/pull/369](https://github.com/apache/cordova-plugin-camera/pull/369)

**Comment by jcesarmobile** [comment]
I can't reproduce the issue, with your change I get this path:

`/storage/emulated/0/DCIM/Camera/IMG_20181123_130112.jpg`

without your change I get

`content://com.android.providers.media.documents/document/image%3A43`

none of those are `DATA_URL`
