### ISSUE TITLE
Crashing in iOS 12 with PictureSourceType.CAMERA

### ISSUE THREAD

**Issue by benmcmaster** [apache/cordova-plugin-camera#371]
`getPicture` is crashing in iOS 12 with:
```
photoObj =
	quality: 40
	allowEdit: false
	destinationType: navigator.camera.DestinationType.FILE_URI
	targetWidth: 1500
	targetHeight: 1500
	encodingType: navigator.camera.EncodingType.JPEG
	mediaType: navigator.camera.MediaType.PICTURE
	sourceType: navigator.camera.PictureSourceType.CAMERA
	saveToPhotoAlbum: true
	correctOrientation: true
```

**Comment by sakujo** [comment]
Same here.  I take a pic and after then i get to edit section and after hitting done the app crashes without any error messages / popups. I tested via ionic serve -c.

`$scope.camera = function() {

        $ionicPlatform.ready(function () {

            $scope.photo = "";

            var options = {
                quality: 100,
                destinationType: Camera.DestinationType.DATA_URL,
                sourceType: Camera.PictureSourceType.CAMERA,
                allowEdit: true,
                encodingType: Camera.EncodingType.JPEGs,
                saveToPhotoAlbum: true
            };

            if(ionic.Platform.isIOS()) {
                options.popoverOptions = CameraPopoverOption;
                options.correctOrientation = true;
            }

            $cordovaCamera.getPicture(options).then(function(imageData) {
                $scope.photo = "data:image/jpeg;base64," + imageData;
            }, function(err) {
                // error
            });
        })

    };`

**Comment by sakujo** [comment]
> `getPicture` is crashing in iOS 12 with:
> 
> ```
> photoObj =
> 	quality: 40
> 	allowEdit: false
> 	destinationType: navigator.camera.DestinationType.FILE_URI
> 	targetWidth: 1500
> 	targetHeight: 1500
> 	encodingType: navigator.camera.EncodingType.JPEG
> 	mediaType: navigator.camera.MediaType.PICTURE
> 	sourceType: navigator.camera.PictureSourceType.CAMERA
> 	saveToPhotoAlbum: true
> 	correctOrientation: true
> ```

Did solve this issue?

**Comment by apoorvitgi** [comment]
I am also facing the same issue. Has anyone solved this?

**Comment by jcesarmobile** [comment]
You have to add this to your config.xml to avoid the crash before prompting for the camera permission
```
<edit-config target="NSCameraUsageDescription" file="*-Info.plist" mode="merge">
    <string>need camera access to take pictures</string>
</edit-config>
```

And this to avoid the crash before saving the picture to the photo album

```
<edit-config target="NSPhotoLibraryAddUsageDescription" file="*-Info.plist" mode="merge">
    <string>need photo library access to save pictures there</string>
</edit-config>
```

With those two I can take pictures without problems on iOS 12

**Comment by inexuscore** [comment]
I'm still having this issue why is this thread closed? I have all the privacy descriptions and I can take pictures, open the photo library etc. However, the app crashes after a bit. When I try to navigate away or take some other action, the app breaks. This only happens on iOS, currently testing on iPhone 8 + iOS 12.1. Been struggling with this for two weeks now. At first, I thought there's something wrong with my code or config, but no, it's the camera plugin.

All Cordova plugins have been updated to their latest versions, also the android/ios engines.
I have tried everything that I could possibly think of:
- privacy descriptions
- making sure my JS code and promises are stable and reliable
- ensuring the Content-Security-Policy definitions are correct
- and tons more

No luck still. I don't even use the returned media to get an error. I just open the camera, or the photo library dialog, cancel and close. And then navigate away and the app crashes. This is ridiculous!

I need help. I have an app in production and I need to fix this ASAP. Let me know if you need more information about my project setup, config and code. I need to resolve this NOW.

**Comment by inexuscore** [comment]
No worries, sorry I don't think my problem is with the Camera plugin at all. Thing is, when I target my local IIS, that is, setting the API base URL, the app works flawlessly. But when I target our remote server, the app crashes when I try to work with the Camera, Library etc. No idea why. I've posted a thread on StackOverflow: [https://stackoverflow.com/questions/53828493/cordova-ios-crashes-when-targeting-remote-server?noredirect=1#comment94506168_53828493](url)
