### ISSUE TITLE
Cannot take pictures on Android 8

### ISSUE THREAD

**Issue by AutoAlert** [apache/cordova-plugin-camera#373]
If I try and take a photo on a device using Android 8 (Samsung Galaxy S7 edge) with targetSDK 26, i get an error 

> file:///data/user/0/{mypackage}/cache/Capture.jpg exposed beyond app through ClipData.Item.getUri()

Which I believe is due to changes in how apps can access the file system from Android Nougat.  See [
https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed](url)

I am using:

- 8.1.2  (cordova-lib@8.1.1)
- android 7.1.2
- cordova-plugin-camera 4.0.3
- cordova-plugin-console 1.0.3
- cordova-plugin-file 6.0.1

I have tried adding the following to my AndroidManifest.xml

`<provider android:authorities="com.okappy.okappy.provider" android:exported="false" android:grantUriPermissions="true" android:name="android.support.v4.content.FileProvider">
        <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/camera_provider_paths" />
    </provider>`

And the following to camera_provider_paths.xml

`<paths xmlns:android="http://schemas.android.com/apk/res/android">
<external-path name="external_files" path="."/>`

But I get the same error unless I change the targetSDK to a lower value.  Is this something simple i'm missing or is it a bug in the plugin?

Thanks
Richard

**Comment by jeffreyvdhondel** [comment]
To fix this issue we had to edit the android manimanifest.xml.

Located here:
project/android/src/main/AndroidManifest.xml


Add the xmlns:tools: 
`<manifest android:hardwareAccelerated="true" android:versionCode="87" android:versionName="0.0.14" package="nl.package.name" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">`

Add the tools:node="remove" to the write external storage:
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove" />`

**Comment by theoafactor** [comment]
@jeffreyvdhondel thanks but this does not work still..

**Comment by AutoAlert** [comment]
Hi @jeffreyvdhondel thanks for the response. I tried your suggestion but unfortunately it still does not work, still the same error.

**Comment by AutoAlert** [comment]
Hi @jcesarmobile thanks for responding. 

We have found the issue. The issue is with our code rather than your plugin.  We were using the following 

    function captureImage() {
        navigator.device.capture.captureImage(captureImageSuccess, captureImageError, {limit: 1});
    }

    function captureImageSuccess(mediaFiles) {
        uploadFile(mediaFiles[0]);
    }

    function uploadFile(mediaFile,fileType) { //#F333
        var win = function (r) {
    }

    var options = new FileUploadOptions();
        ImageURL=mediaFile.fullPath;
        options.fileName = (fileType)? mediaFile.name : mediaFile.file; //#F333
        options.mimeType = "multipart/form-data";
        var params = new Object();
        params.fileName = 'AndroidPhoneUpload';
        params.imageType = (fileType)?fileType:'Picture';   //#F333
        var printName = prompt("Add a title","");  //#F644
        if (printName){
            params.printedName = printName;
        }
        window.resolveLocalFileSystemURL(ImageURL, function(fileEntry) {
            fileEntry.file(function(fileObj) {
                params.fileSize = ""+fileObj.size;
            });
        });
        options.params = params;
        var ft = new FileTransfer();
        ft.upload(ImageURL, encodeURI("uploadURL"),win,fail,options);
    }

Which we have replaced with

    navigator.camera.getPicture(function cameraSuccess(imageUri) {
            var options = new FileUploadOptions();
            options.fileKey="file";
            options.fileName="test";
            options.mimeType="multipart/form-data";
            var params = new Object();
            params.fileName = 'AndroidPhoneUpload';           
            options.params = params;
            var ft = new FileTransfer();
            ft.upload(imageUri, encodeURI("https://upload.okappy.com/UploadToS3"), win, fail, options);
        }, function captureImageError(error) {
            console.debug("Unable to obtain picture: " + error, "app");
        }, options);

**Comment by desmeit** [comment]
@AutoAlert What was the issue in detail?
I see no difference between your codes.

**Comment by pritish5** [comment]
@jeffreyvdhondel work perfectly

**Comment by jeffreyvdhondel** [comment]
We solved our issue now with this fix.

https://github.com/bitstadium/HockeySDK-Cordova/issues/100#issuecomment-465903717
