### ISSUE TITLE
Multiple capture crashes the Application

### ISSUE THREAD

**Issue by sks30** [apache/cordova-plugin-camera#374]
Whenever i am taking the image from gallery or from camera multiple times App crashes due to increased memory of the App. How to do clean up in case of Android? is there a way to do it?

Whenever i am selecting some images from gallery then one copy was there in this below path-
content://com.android.providers.downloads.documents/document/1144 

Please suggest me how to remove this one from android.

**Comment by janpio** [comment]
Are these two different questions or problems? If so, please create a second issue so those can be handled separately.

**Comment by sks30** [comment]
As per my understanding both are interlinked . because of memory increase app got crashed.

**Comment by janpio** [comment]
Ok, then I just don't understand your issue.

> How to do clean up in case of Android?

What do you want to clean up?

> Whenever i am selecting some images from gallery then one copy was there in this below path-

What does that mean?

> Please suggest me how to remove this one from android.

Remove what from Android?

**Comment by sks30** [comment]
Okay let me explain again.
1. suppose i have selected some image from gallery.
2. So in network tab i can see the url of blob file and jpg file both such as

blob:file:///1e6c0487-a0f4-4ae2-bed1-44a620a0ecdb
content://com.android.providers.downloads.documents/document/1144

3. So after the completion of uploading process i want to remove these two file from my app temporary folder.

**Comment by janpio** [comment]
Where is the connection to your Android app crashing here?

**Comment by sks30** [comment]
If i am doing those process explained above multiple times then Android app is crashing.

**Comment by sks30** [comment]
When user add document image to preview from camera or gallery, then storage increase, and it does not get cleared up on cancelling the preview or uploading the document successfully. If user adds image to preview and cancel it- Repeat 5 times, then storage keeps on increasing and finally crashing.

**Comment by janpio** [comment]
Yes, that I got. But does it have to do with your question in https://github.com/apache/cordova-plugin-camera/issues/374#issuecomment-439011146?

**Comment by sks30** [comment]
yes due to multiple capture these crash things are happening.

**Comment by janpio** [comment]
I got that. But does this have to do with your question on how to remove some files?

**Comment by breautek** [comment]
stale
