### ISSUE TITLE
Not supporting on browser 

### ISSUE THREAD

**Issue by amitgandole** [apache/cordova-plugin-camera#375]
Hello,
As mentioned in plugin documentation, Camera working fine in DevApp. But when I run same on mobile browser, Its saying cordova not available. Is it issue or am I doing anything wrong?

My code is : 
takePicture(){

    const options: CameraOptions = {
      quality: 100,
      destinationType: this.camera.DestinationType.FILE_URI,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE
    }
  
    this.camera.getPicture(options).then((imageData) => {
      
    }).then((imageData) => {
    this.base64Image= "data:image/png;base64," + dataImage;
   
    }, (err) => {
        console.log(err);
    });
  }

**Comment by janpio** [comment]
What is "DevApp"?

Also, what is `this.camera`? The plugin is available under `navigator.camera`.

Are you using Ionic Native maybe? Then you should probably open an issue at their repository - you are at the Cordova plugin's repository that is used by Ionic Native.

**Comment by amitgandole** [comment]
DevApp is IONIC DevApp which allows to  run app without installation. and i have declared the camera constructor in constructor : `constructor(public navCtrl: NavController,
    public camera: Camera) {

  }`

Also in import section : 
`import { Camera, CameraOptions } from '@ionic-native/camera';
`

**Comment by janpio** [comment]
As I wrote, you are in the wrong place here then. You are looking for https://github.com/ionic-team/ionic-native/issues/

**Comment by amitgandole** [comment]
haha.. wow.. and I and redirected to this repo from official ionic website. Thanks.

**Comment by janpio** [comment]
Ionic Native documentation links to this repository as it is the the Cordova plugin being used by the Ionic Native wrapper. But if you have problems using the Ionic Native wrapper, you still have to go to the Ionic Native repository - we can't help for that.
