### ISSUE TITLE
UIImagePickerController cancel handling incorrect for iOS11+

### ISSUE THREAD

**Issue by easywasdev** [apache/cordova-plugin-camera#376]
The way the plugin handles the user cancelling the UIImagePickerController is not correct for iOS11+. From iOS 11 Apple no longer requires the user's explicit permission to show UIImagePickerController:

> Accessing images using UIImagePickerViewController no longer requires explicit permission, though accessing the photo library through other APIs does. The changes to the photo library permission model is detailed in the WWDC17 sessions What's New in Photos and Privacy and Your Apps.

From https://forums.developer.apple.com/thread/86974#271938
See https://developer.apple.com/videos/play/wwdc2017-505/?time=252

Currently, `imagePickerControllerDidCancel` returns an error ("has no access to assets") if `picker.sourceType != UIImagePickerControllerSourceTypeCamera && [ALAssetsLibrary authorizationStatus] != ALAuthorizationStatusAuthorized`. In iOS11+ this will never be true. `[ALAssetsLibrary authorizationStatus]` returns `ALAuthorizationStatusNotDetermined` because permission is never requested. So returning the permission denied error is incorrect. The code remains correct from iOS 10 and below.

I will submit a pull request with a suggested solution to this problem either later today or Monday.

**Comment by easywasdev** [comment]
CDVCameraLibTests do not run in Xcode 10, but worked in Xcode 9. I will submit the PR shortly

**Comment by jcesarmobile** [comment]
Fixed
