### ISSUE TITLE
Image quality and file size

### ISSUE THREAD

**Issue by humblecoder** [apache/cordova-plugin-camera#378]
I realize that it's mentioned in the documentation that adjusting `quality` might not work.  For example, there is little difference between setting image `quality: 100` or `quality:10`.  But it doesn't really explain why or how to work around this issue.  Please make it work...? 🤷‍♂️

**Comment by janpio** [comment]
What platform? What device?

**Comment by humblecoder** [comment]
@janpio Apologies, I've been in iOS-land all day that I assume everyone is in that context.  Deploying to iPhone6s and above.

**Comment by janpio** [comment]
Missed to ask for iOS version... then we should have everything to investigate this (one day).

**Comment by jcesarmobile** [comment]
I don't understand the issue? what is the problem?

**Comment by janpio** [comment]
He wants to know why this is the case and if it can be worked around.

**Comment by humblecoder** [comment]
@jcesarmobile when `quality` is changed, I see no discernible difference in file size or actual image quality.

**Comment by janpio** [comment]
What photos? Newly taken ones or from the gallery?

**Comment by humblecoder** [comment]
@janpio I actually didn't check "gallery" photos.  I've strictly been looking at "newly taken" photos.

**Comment by janpio** [comment]
Ok, so you take a photo on an iPhone6s or newer and setting `quality` doesn't make a "discernible difference in file size or actual image quality" - correct?

Best create a super quick reproduction app with `cordova create` that shows the issue well enough so we don't have to do any coding before being able to reproduce the problem. Put it on GitHub and post the link to the repo here. Thanks.

**Comment by jcesarmobile** [comment]
I've been doing some tests and it highly depends on the photo, but I see a big difference in the photos, with 100% quality I've seen up to 3,5MB on an iPad 4, and up to 150KB with 10%.

I see a is a really discernible difference.
