### ISSUE TITLE
Remove deprecated platforms from README

### ISSUE THREAD

**Issue by jcesarmobile** [apache/cordova-plugin-camera#380]
We have removed the code for deprecated platforms, but we still mention them as supported and it's quirks, we should remove all that.

**Comment by janpio** [comment]
(You can probably duplicate this in `apache/cordova` and add a TODO for all plugins...)

**Comment by jcesarmobile** [comment]
I should check all plugins first, maybe they were removed correctly in other plugins

**Comment by janpio** [comment]
maybe...

**Comment by jcesarmobile** [comment]
In fact it was correctly removed, but then added by accident later, probably because of the automatic doc generation, I've only checked a few other repos but didn't have the deprecated platforms anymore.
