### ISSUE TITLE
allowEdit not working when sourceType is PHOTOLIBRARY

### ISSUE THREAD

**Issue by Carlosps** [apache/cordova-plugin-camera#393]
Hello,

**cordova-android": "7.0.0"**
**OS version** 7.1.2 
**Device** Redmi 4x

The editing works fine when source type is camera, but nothing happens when we select PHOTOLIBRARY.

`const options: CameraOptions = {
      allowEdit: true,
      quality: 70,
      destinationType: this.camera.DestinationType.DATA_URL,
      sourceType: useAlbum ? this.camera.PictureSourceType.PHOTOLIBRARY : this.camera.PictureSourceType.CAMERA,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE
    }`

Any idea what that might be? Thank you.

**Comment by janpio** [comment]
What Cordova platform? What platform version?
What OS version? What device?

**Comment by Carlosps** [comment]
Just updated the question with that information, thanks.

**Comment by Carlosps** [comment]
Any updates on that?

**Comment by kadimawl** [comment]
Maybe it has something to do with cell phones

**Comment by hazems** [comment]
This is a valid bug working on a fix now.

**Comment by hazems** [comment]
I created a PR that fixes this issue:
https://github.com/apache/cordova-plugin-camera/pull/426

@jcesarmobile @macdonst please review when you have sometime, thank you.

**Comment by hazems** [comment]
@janpio PR is ready for review, thanks:
https://github.com/apache/cordova-plugin-camera/pull/426

**Comment by hazems** [comment]
If anyone or @Carlosps is interested in this fix, feel free to thumb up this PR which fixes this issue :
https://github.com/apache/cordova-plugin-camera/pull/426

Thanks

**Comment by SidiBecker** [comment]
This bug is fixed?

**Comment by cleverappdesign** [comment]
I have the same issue on Android only, works fine on iOS

```
Ionic:

   ionic (Ionic CLI)  : 4.10.2
   Ionic Framework    : ionic-angular 3.9.3
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.1.0
```

**Comment by cleverappdesign** [comment]
I got it working when using the Android Permission plugin
https://github.com/apache/cordova-plugin-camera/issues/486#issuecomment-576463204

**Comment by arushraj** [comment]
The issues is still not fixed. can anyone update on this

**Comment by breautek** [comment]
We are deprecating the `allowEdit` feature and will no longer provide support for it. In brief, the feature is unreliable cross plaform as it depends on image manipulation support in the underlying camera application, which an app cannot test for. Use a dedicated image manipulation library instead.

See https://github.com/apache/cordova-plugin-camera/pull/914 for more details.
