### ISSUE TITLE
iOS app not asking permission after manually disable permission

### ISSUE THREAD

**Issue by ViCoastLLC** [apache/cordova-plugin-camera#395]
My app was working fine, I just manually disabled permissions and tried to take pictures. Now it is not asking permission, not even allowing to take pictures. It is just displaying blank screen onclick of camera through my app.

**Comment by jcesarmobile** [comment]
iOS only asks for permissions once, if you disable it, it won't ask again.
There are some changes on master that will make it return an error when permission is not granted.

**Comment by ViCoastLLC** [comment]
> iOS only asks for permissions once, if you disable it, it won't ask again.
> There are some changes on master that will make it return an error when permission is not granted.

May I know what do you mean by 'Some changes on Master"?

**Comment by jcesarmobile** [comment]
Máster is the branch on github, if you install from github url instead of from nom you can get the development version
