### ISSUE TITLE
Write External Storage permission

### ISSUE THREAD

**Issue by jijishthomas** [apache/cordova-plugin-camera#398]
Hello,
This camera plugin requests WRITE_EXTERNAL_STORAGE permission, which is listed as a malicious permission by android, So in order to prevent this, I tried to use DATA_URI, and changed the WRITE_EXTERNAL_STORAGE permission to READ_EXTERNAL_STORAGE, but the app crashes after taking image.

**Comment by yuankunluo** [comment]
yes, same problem hier with ionic 4

**Comment by breautek** [comment]
`WRITE_EXTERNAL_STORAGE` is still necessary for writing the image to the temporary location.
