### ISSUE TITLE
NullPointerException error on some Android phones

### ISSUE THREAD

**Issue by mifkys** [apache/cordova-plugin-camera#400]
Hello. I receive few crash logs from some Android phones with next error:

> java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
> 	at org.apache.cordova.camera.CameraLauncher.processResultFromGallery(CameraLauncher.java:702)
> 	at org.apache.cordova.camera.CameraLauncher.access$000(CameraLauncher.java:74)
> 	at org.apache.cordova.camera.CameraLauncher$1.run(CameraLauncher.java:833)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> 	at java.lang.Thread.run(Thread.java:818)

Using latest version of plugin.
Code:
```
let cameraOptions = {
            sourceType: this.camera.PictureSourceType.PHOTOLIBRARY,
            destinationType: this.camera.DestinationType.FILE_URI,
            encodingType: this.camera.EncodingType.JPEG,
            mediaType: this.camera.MediaType.PICTURE
          }
          this.camera.getPicture(cameraOptions).then(uri => {
             …
          }).catch(err => {
             ….
          });
```

App crashed on this phones:
Huawei GR3
Huawei Y3III
Android 5.1
Android 6.0

**Comment by hazems** [comment]
Got it, a PR will be available soon!

**Comment by hazems** [comment]
@jcesarmobile @janpio @macdonst a Quick PR is available:
https://github.com/apache/cordova-plugin-camera/pull/429

Thanks

**Comment by mifkys** [comment]
Great! thanks!

**Comment by hazems** [comment]
If anyone or @mifkys is interested in this fix, feel free to thumb up this PR which fixes this issue:
https://github.com/apache/cordova-plugin-camera/pull/429

Thanks

**Comment by PieterVanPoyer** [comment]
Seems like this is fixed in https://github.com/apache/cordova-plugin-camera/pull/429
