### ISSUE TITLE
choosing multiple images from gallery using this plugin

### ISSUE THREAD

**Issue by 10aditya** [apache/cordova-plugin-camera#401]
why doesn't this plugin's CameraOptions have number of images field? Unlike ImagePicker Plugin this uses native image selector but doesn't allow multiple image selection. Please add that feature or correct if I'm wrong. Thanks.

**Comment by jcesarmobile** [comment]
Because it was decided to only pick one as Camera only allows one so gallery should have the same behaviour.

You talk about a different plugin that allows it, so just use that one.
