### ISSUE TITLE
Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided

### ISSUE THREAD

**Issue by frankenState** [apache/cordova-plugin-camera#403]
I followed the documentation in  https://ionicframework.com/docs/native/camera/ and already added the browser platform in cordova. But that problem is always showing up. We are dead in our Thesis Project if we didnt solve this thing. We're new to Ionic and Angular. About weeks of learning. Please help us.

**Comment by breautek** [comment]
Stale
