### ISSUE TITLE
Support for Android 3.x and Jetpack

### ISSUE THREAD

**Issue by alsocalledchris** [apache/cordova-plugin-camera#405]
Building a Cordova App that uses Android 3.x and Jetpack does not build with the below errors:

- Error:(25, 34) error: package android.support.v4.content does not exist

I'm not able to change the compile target version (28) which looks like a solution that others have made. Any other suggestions?

Thanks.

**Comment by dfattlar** [comment]
+1  Seeing this issue too.

**Comment by pbergner** [comment]
seeing it well, is there a workaround?

**Comment by stck** [comment]
In order to support jetpack's format, dependency
`android.support.v4.content` should be changed to `androidx.loader.content`

**Comment by dfattlar** [comment]
Thanks @stck! From Android Studio I clicked Refactor > Migrate to AndroidX. After the scan, I clicked 'Do Refactor', and was then able to build to Android device again.

**Comment by contfedorov** [comment]
`cordova-android` supports AndroidX since [version 9.0](https://cordova.apache.org/announcements/2020/06/29/cordova-android-9.0.0.html). Are there any plans to move this plugin to AndroidX instead of support library?

**Comment by jcesarmobile** [comment]
Version 6 of the plugin uses AndroidX 
https://github.com/apache/cordova-plugin-camera/pull/751
