### ISSUE TITLE
Camera showing only black screen  after ios12 upgrade

### ISSUE THREAD

**Issue by prosunbondopadhyay** [apache/cordova-plugin-camera#407]
Hi ,

We made a custom app which has some upload functionality using camera. This was working fine till IOS 11. After upgrading to IOS 12 the same app shows the camera but with black screen.
Can you please help?

**Comment by JBerendes** [comment]
Having the same problem. 🔥 🔥 🔥 
Can't release my app without a fix but it does look like https://github.com/bitpay/cordova-plugin-qrscanner/issues/209 might have the workaround.

**Comment by stck** [comment]
Since iOS 12, Apple restrict usage of internal API's w/o usage descriptions. So it can be done manually in xcode, or, as mentioned above, by using cordova-plugin-diagnostic, which looks excessive

**Comment by JBerendes** [comment]
Thanks, @stck. I got mine going by updating the generated .plist file. I agree, it's pretty excessive to use diagnostic. It might be wise to make a copy of the generated .plist (from the platforms ios folder) to a .plist file in the root of the project. Watch for changes and always keep the root file up to date. Then use a post install hook or a script to copy the root .plist back to the appropriate location in the platforms ios folder. @prosunbondopadhyay I think we have answered this and hope it works out.

**Comment by JBerendes** [comment]
If your app requires additional internal api functionality then it would probably make sense to go with cordova-plugin-diagnostic as you would probably want to check that the user hasn't disabled some functionality through settings or app settings. ... for example if you have an app that requires bluetooth and the user toggled it off you would want the app to show the user an alert and direct them to turn on bluetooth.

**Comment by breautek** [comment]
stale
