### ISSUE TITLE
App crash when opening camera on iOS

### ISSUE THREAD

**Issue by rockraft7** [apache/cordova-plugin-camera#408]
App is crashing when opening camera on iPhone 7 with software update 12.1.2 with memory issue message:

`Message from debugger: Terminated due to memory issue`

Code snippet:

`           navigator.camera.getPicture(function (imageData) {
                    files.push(imageData);
                }, function (error) {
                    alert("Taking picture failed: " + error);
                }, {
                    quality: 30,
                    destinationType: navigator.camera.DestinationType.DATA_URL,
                    encodingType: navigator.camera.EncodingType.JPEG,
                    correctOrientation: true,
                    targetWidth: 640,
                    targetHeight: 640
                });
`
I am using version 4.0.3

**Comment by rockraft7** [comment]
Only on certain device. will close for now

**Comment by rehman22** [comment]
Ios camera is working?  I have issue in ios camera  its working on android
