### ISSUE TITLE
How to get full quality pictures ?

### ISSUE THREAD

**Issue by Jeijie** [apache/cordova-plugin-camera#410]
I need to get full quality pictures, but when I set quality 100, It doesn't seem to work.

var hpzType = Camera.PictureSourceType.CAMERA;
              var options = {
                quality: 100,
                targetWidth: 800,
                targetHeight: 800,
                destinationType: Camera.DestinationType.FILE_URI,
                sourceType: hpzType,
                allowEdit: false,
                encodingType: Camera.EncodingType.JPEG,
                popoverOptions: CameraPopoverOptions,
                saveToPhotoAlbum: true
              };

cordova-plugin-camera 2.4.1 "Camera"

--------------------------------
Cordova CLI: 6.5.0
Gulp version:  CLI version 2.0.1
Gulp local:
Ionic Framework Version: 1.2.4
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
OS: Windows 7 SP1
Node Version: v8.12.0

--------------------------------

**Comment by jcesarmobile** [comment]
If you want full quality images don't set targetHeight and targetWidth
