### ISSUE TITLE
Any way to specify advanced params like shutter speed or ISO?

### ISSUE THREAD

**Issue by Xeoncross** [apache/cordova-plugin-camera#413]
Reading the [camera intent code for Android](https://github.com/apache/cordova-plugin-camera/blob/6899c5ece9/src/android/CameraLauncher.java#L293), it's not clear how this would be achieved. Is there anyway to specify the shutter speed or ISO using this plugin?

**Comment by jcesarmobile** [comment]
It's not possible to do it with the Intetn

**Comment by Xeoncross** [comment]
@jcesarmobile what would I need to do in order to add this feature? If Intent isn't the correct way, would I need to parse the camera.getParameters()?
