### ISSUE TITLE
iOS: Camera.PictureSourceType.PHOTOLIBRARY does not prompt for permissions

### ISSUE THREAD

**Issue by PTRFRLL** [apache/cordova-plugin-camera#414]
Running iOS 12.1.2. When I select the option to load from photo library for the first time, there is no prompt to allow the app access to the photo library. The app has full-access from the start. 

The other photo related permissions all work, access to camera, accces to ADD to photo library, etc. 

Here's the relevant code:

```js
var options = {
    sourceType: this.camera.PictureSourceType.PHOTOLIBRARY,
    destinationType: this.camera.DestinationType.FILE_URI,
    saveToPhotoAlbum: true,
    correctOrientation: true
};
this.camera.getPicture(options).then(imagePath => {
    //more code here...
});
```

and my config.xml file:

```xml
<edit-config file="*-Info.plist" mode="merge" target="NSPhotoLibraryUsageDescription">
    <string>[app name] uses your photo library to upload images</string>
</edit-config>
<edit-config file="*-Info.plist" mode="merge" target="NSCameraUsageDescription">
    <string>[app name] uses your camera to capture photos</string>
</edit-config>
<edit-config file="*-Info.plist" mode="merge" target="NSLocationAlwaysUsageDescription">
    <string>[app name] uses your location to locate nearby facilities</string>
</edit-config>
<edit-config file="*-Info.plist" mode="merge" target="NSLocationWhenInUseUsageDescription">
    <string>[app name] uses your location to locate nearby facilities</string>
</edit-config>
<edit-config file="*-Info.plist" mode="merge" target="NSPhotoLibraryAddUsageDescription">
    <string>[app name] saves photos you take in-app to your photo library</string>
</edit-config>
```

**Comment by PTRFRLL** [comment]
Apologies, this is more related to the Ionic Native Camera plugin. [I found an issue on their repo that already discusses this](https://github.com/ionic-team/ionic-native/issues/2634).

**Comment by ZaLiTHkA** [comment]
the review guys at Apple are preventing me from releasing an app because of this same issue, but I'm not using Ionic for this project... so I don't think it *is* actually an Ionic issue.

@PTRFRLL did you find a way to get the prompt to show up?
