### ISSUE TITLE
DATA_URL is improperly prefixed

### ISSUE THREAD

**Issue by 0awful** [apache/cordova-plugin-camera#420]
Getting a dataURL from the cordova-plugin-camera omits the 'data:'mimeType';base64, '

**Comment by hazems** [comment]
This is currently the actual API behavior across all platforms. I do not think it is a bug since it is consistent across other platforms.

**Comment by jcesarmobile** [comment]
It's a known issue https://issues.apache.org/jira/browse/CB-9819

**Comment by hazems** [comment]
@jcesarmobile If we agree to have this supported across platforms, here is my Android support proposal:
https://github.com/hazems/cordova-plugin-camera/commit/e6609c0b6a590a30ef7802826888693142576bee

**Comment by jcesarmobile** [comment]
I personally agree, but for this kind of changes is recommended to send a mail to the dev list proposing it

**Comment by hazems** [comment]
Sure will share it with the group.

**Comment by hazems** [comment]
Sent to development group email.

**Comment by hazems** [comment]
@imizaac A PR is created to fix this behavior across of all Camera platforms:
https://github.com/apache/cordova-plugin-camera/pull/432

cc @jcesarmobile

**Comment by hazems** [comment]
If anyone or @imizaac is interested in this fix, feel free to thumb up this PR which fixes this issue across all of Cordova supported platforms:
https://github.com/apache/cordova-plugin-camera/pull/432

Thanks

**Comment by hazems** [comment]
@ruisilva450 This is the PR that fix this issue across all platforms:
https://github.com/apache/cordova-plugin-camera/pull/432

Please thumbs it up to show an interest in merging it.

**Comment by ruisilva450** [comment]
> 
> 
> @ruisilva450 This is the PR that fix this issue across all platforms:
> #432
> 
> Please thumbs it up to show an interest in merging it.

I already saw that, has my thumbs up and that's why I'm asking 😃
