### ISSUE TITLE
is correctOrientation  support IOS?

### ISSUE THREAD

**Issue by guanyuan** [apache/cordova-plugin-camera#424]
I am wondering if correctOrientation is supported on IOS ?

**Comment by janpio** [comment]
`correctOrientation: true  //Corrects Android orientation quirks` from the docs indicates that probably not.

**Comment by guanyuan** [comment]
When I view the source code in src/ios/CDVCamera.m, I saw the defination that option.
```
if (options.correctOrientation) {
        image = [image imageCorrectedForCaptureOrientation];
    }
```
So I am a little confused.
Thanks for your confirmation. 
I have tested on my iphone, and correctOrientation is not working.

**Comment by janpio** [comment]
I did not confirm anything, I just mentioned what the docs say.

**Comment by guanyuan** [comment]
@janpio  Thanks for you kindness.
So does anyone else who also test if the correctOrientation work on IOS or not?

my cordova version: 6.5.0

**Comment by jcesarmobile** [comment]
That's not "docs", it's an unfortunate comment in a code sample.
I've sent a PR to remove it. 
correctOrientation is supported on iOS, the docs where correctOrientation is documented don't mention that it's not supported.
