### ISSUE TITLE
Cordova camera plugin issue for windows 10

### ISSUE THREAD

**Issue by SukumarNomula** [apache/cordova-plugin-camera#428]
I am implementing an app which should support Android, IOS and windows 10. 
I am getting an issue in windows app when I try to select same video from gallery for the second time. First time plugin is copying the video file to its local path and for the second time it is throwing error like "The operation cannot be performed  as the file is accessed by other process". If I select other file then there is no problem. Issue raises only when I select the same video file more than once.

I am using:
* windows 10,
* ionic 3.20,
* cordova 8.0.0

Appreciate if any one suggest a solution.

**Comment by MSwapna428** [comment]
Already attempted solution mentioned in : https://github.com/apache/cordova-plugin-camera/issues/329

**Comment by erisu** [comment]
[Cordova Windows](https://github.com/apache/cordova-windows) has been deprecated and is no longer supported making this issue obsolete.
