### ISSUE TITLE
how to localize text on ios?

### ISSUE THREAD

**Issue by YaroslavG** [apache/cordova-plugin-camera#433]
Hello guys,
when I click camera.getPicture() on ios I can see this action sheet. How I can change or localize this texts?
![Снимок экрана 2019-03-20 в 18 21 44](https://user-images.githubusercontent.com/5793103/54701846-6c631880-4b3e-11e9-935d-99251637ad17.png)

**Comment by jcesarmobile** [comment]
You can add languages with edit-config and config-file tags like

```
<config-file parent="CFBundleLocalizations" target="*-Info.plist">
  <array>
    <string>en</string>
    <string>es</string>
  </array>
</config-file>
```
