### ISSUE TITLE
CameraUsesGeolocation and NATIVE_URI aren't working when used together

### ISSUE THREAD

**Issue by 0mpurdy** [apache/cordova-plugin-camera#436]
# Bug Report

## Problem

On iOS:

Works: `DestinationType.NATIVE_URI` 
Works: `CameraUsesGeolocation`
Works: `DestinationType.FILE_URI` + `CameraUsesGeolocation`
Doesn't work: `DestinationType.NATIVE_URI` + `CameraUsesGeolocation`

### What is expected to happen?

Taking a photo with the camera on iOS will return a native URI, and the photo will have geolocation information.

### What does actually happen?

The success callback is never invoked when using `DestinationType.NATIVE_URI` and `<preference name="CameraUsesGeolocation" value="true" />`.

## Information

Failures still work as expected (cancelling from the camera popover will still show an error message).

### Command or Code

Github repo that has the problem: https://github.com/0mpurdy/ionic-3-gallery

The FILE_URI button works as expected (loads the photo), the NATIVE_URI button does not work (nothing happens on return from the camera)

### Environment, Platform, Device

iOS, both on iPad mini 2 and iPhone 6

### Version information

```
Ionic:

   ionic (Ionic CLI)  : 4.10.1 (/Users/username/.config/yarn/global/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.3
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 6 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/username/Library/Android/sdk/)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.0
   NodeJS            : v10.11.0 (/Users/username/.nvm/versions/node/v10.11.0/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2 Build version 10E125
```

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
  + Using a new install of Ionic 3
- [x] I included all the necessary information above

**Comment by BurkusCat** [comment]
I've had this issue before (didn't get to the bottom of it, just had to remove it). Anyone any ideas?

**Comment by plchampigny** [comment]
I currently have the same issue with the DestinationType.FILE_URI + CameraUsesGeolocation with iOS 13 device

**Comment by pbergner** [comment]
Any update on this issue?

**Comment by knight9999** [comment]
Could some please check my commit? 
https://github.com/knight9999/cordova-plugin-camera/commit/f8041a2381e3f7f611e7b6502bc1a1b4df0516d0  
(this is a fix for 4.3.x branch)

**Comment by knight9999** [comment]
I updated my forked code.

The situation In my environment (iOS 13.6) is
Doesn't Work `CameraUsesGeolocation` and `FILE_URI`
Doesn't Work `CameraUsesGeolocation` and `DATA_URL`
Doesn't Work `CameraUsesGeolocation` and `NATIVE_URI`.

My forked code https://github.com/knight9999/cordova-plugin-camera/commits/fix-issue-436_on_5.0.X 
fixed it. (However, for NATIVE_URI, the geolocation data is not embedded into the metadata yet. 
Because the location manager was not called in this case.)

**Comment by jcesarmobile** [comment]
Closing as NATIVE_URI was removed in 5.0.0
