### ISSUE TITLE
iOS Not close camera after denied permissions

### ISSUE THREAD

**Issue by albertocanca** [apache/cordova-plugin-camera#440]
# Bug Report

## Problem
The first time camera is opened, the plugin open a popover to ask user if he want to accept the permission. In case you denied this permission, the camera is still opened and the user can take a black photo

### What is expected to happen?
When the user denied the permission, the camera must close.

### What does actually happen?
When the user denied the permission, the camera is still opened.

### Version information

Version @ionic-native/camera: ^4.20.0,
Version cordova-plugin-camera": ^4.0.3
iOS device: 12.1.2

ionic (Ionic CLI)  : 4.6.0
Ionic Framework    : ionic-angular 3.9.2
@ionic/app-scripts : 3.2.1
cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
Cordova Platforms     : android 7.1.4, ios 4.5.5
ios-deploy : 1.9.2
ios-sim    : 6.1.2
NodeJS     : v6.10.3
npm        : 6.1.0
OS         : macOS High Sierra
Xcode      : Xcode 10.1 Build version 10B61

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by abbasalwash** [comment]
I have the same problem.

Version @ionic-native/camera: ^4.20.0,
Version cordova-plugin-camera": ^4.0.3
iOS device: 12.1.2

@ionic/cli-utils  : 1.19.2
ionic (Ionic CLI) : 3.20.0
cordova (Cordova CLI) : 6.5.0 
@ionic/app-scripts : 3.2.3
Cordova Platforms : android 6.3.0 ios 4.3.1
Ionic Framework : ionic-angular 3.9.5
ios-deploy : 1.9.4 
Node : v10.15.3
npm : 5.10.0 
OS : macOS Mojave
Xcode : Xcode 10.2.1 Build version 10E1001

**Comment by janpio** [comment]
There are newer Cordova iOS versions than both of you are using, 5.0.1 is the current version. Does this problem also appear in this iOS 12 optimized version?

**Comment by abbasalwash** [comment]
Thank you for your response, to upgrade to higher version I will need more time of other plugins and dependencies. Is there an alternative?

**Comment by janpio** [comment]
You could create a quick new project with `cordova create`, then add the minimal plugins and code required to recreate the situation you are seeing in your app. More information on how to create this: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

If it also happens with the current version, we have a proper bug (and you can jsut put this reproduction app on GitHub for us to look at and fix it). 

If it does not happen in this app, we know that it is a bug that already has been fixed and can try to help you get a workaround in your existing app.


Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue.

**Comment by wnabil** [comment]
I have the same issue and i have the latest plugin version 4.0.3
tested on iPhone 6 with iOS 12

**Comment by wnabil** [comment]
Tested the new cordova iOS version 5.0.1 but not luck.
@janpio can you please try to fix this or if you have a workaround.

**Comment by janpio** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md
