### ISSUE TITLE
I'm getting "plugin_not_installed" errors on iOS devices with Ionic 4

### ISSUE THREAD

**Issue by tonymccallie** [apache/cordova-plugin-camera#442]
## Problem
I'm trying to get the plugin to work on iOS 12.2 and have tried compiling through Ionic's AppFlow and through my local XCode.

### What is expected to happen?
I should be able to access Camera functions.

### What does actually happen?
I keep getting:
```
[Warning] Native: tried calling Camera.getPicture, but the Camera plugin is not installed. (cordova.js, line 1732)
[Warning] Install the Camera plugin: 'ionic cordova plugin add cordova-plugin-camera' (cordova.js, line 1732)
[Error] ERROR – Error: Uncaught (in promise): plugin_not_installed
Error: Uncaught (in promise): plugin_not_installed
```

## Information
I installed the plugin like so:
ionic cordova platform add ios
ionic cordova plugin add cordova-plugin-camera

I've added these to my config.xml
```
<edit-config file="*-Info.plist" mode="merge" target="NSCameraUsageDescription">
        <string>need camera access to take pictures</string>
    </edit-config>
    <edit-config file="*-Info.plist" mode="merge" target="NSPhotoLibraryUsageDescription">
        <string>need photo library access to get pictures from there</string>
    </edit-config>
    <edit-config file="*-Info.plist" mode="merge" target="NSLocationWhenInUseUsageDescription">
        <string>need location access to find things nearby</string>
    </edit-config>
    <edit-config file="*-Info.plist" mode="merge" target="NSPhotoLibraryAddUsageDescription">
        <string>need photo library access to save pictures there</string>
    </edit-config>
```

And I installed the recommended npm packages. Those seem to be working, but the plugin does not. I have removed the platform and the plugin, reinstalled them. Removed node_modules and package-lock.json and re-ran npm -i. All to no avail.

I can see the camera plugin being added in the output of the AppFlow build, but I don't have access to it. 

What am I missing?

### Version information
I'm using Ionic 4 on macOS 10.14.4 with XCode 10.2 and an iPhone Xs with iOS 12.2, but mostly I use Ionic AppFlow to compile my IPAs. I have other plugins working fine (like Geolocation)

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by GedasGa** [comment]
Noticed that you are using `Ionic`. On my environment, I tried with a "pure" `Cordova 9.0.0` and iOS `^5.0.0` installation, and did not face any issues with the `cordova-plugin-camera`. On the other hand, I did not test with `Ionic`. Because of this, I believe it could be an issue with `Ionic` and not `Cordova` itself, and probably should be reported to `Ionic` support system.

**Comment by jcesarmobile** [comment]
Sorry, this is not a problem in the plugin. Closing

**Comment by razzul** [comment]
> Noticed that you are using `Ionic`. On my environment, I tried with a "pure" `Cordova 9.0.0` and iOS `^5.0.0` installation, and did not face any issues with the `cordova-plugin-camera`. On the other hand, I did not test with `Ionic`. Because of this, I believe it could be an issue with the `Ionic` and not `Cordova` itself, and probably should be reported to the `Ionic` support system.

Did you found any solution, I am facing the same
