### ISSUE TITLE
Is there any way to pinch-in and pinch-out the photo at CameraPopover mode?

### ISSUE THREAD

**Issue by goforitjin** [apache/cordova-plugin-camera#443]
We are looking for the way to check up the taken photo clearly at CameraPopover mode.

I know It is not able to handle the CameraPopover page but our requirement is that user want to check up the photo with pinch-in and out before save. 

I really thank you if someone customize or know how to customize the "CameraPopover" page. 
Thanks in advance. 

![Capture](https://user-images.githubusercontent.com/12743012/55782452-47334b80-5ae7-11e9-850b-8b8e9332d42e.PNG)

**Comment by jcesarmobile** [comment]
It’s not possible
