### ISSUE TITLE
Câmera with gallery

### ISSUE THREAD

**Issue by eeerrrttty** [apache/cordova-plugin-camera#446]
# Feature Request

I would like to acess 'gallery' with the camera, so the user can choose his last pictures, or to put an option 'gallery' in the display, so the user that is acessing the camera can type on 'gallery' to acess it (directly from plugin's camera).

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊.  
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
