### ISSUE TITLE
First camera.getPicture() costs 10 or more seconds to open native camera

### ISSUE THREAD

**Issue by DamianSheldon** [apache/cordova-plugin-camera#447]
# Bug Report

## Problem
First camera.getPicture() costs 10 or more seconds to open native camera

### What is expected to happen?
First call should almost works as follow calls.

### What does actually happen?
First camera.getPicture() costs 10 or more seconds to open native camera, follow calls cost less 1 second.

## Information

There is a reproduce [demo](https://github.com/ionic-team/photo-gallery-tutorial-ionic4)   

1. Run demo on iOS
2. Click tab 2
3. Click bottom camera button 

### Environment, Platform, Device

I'm experiencing the issue on iPhone 8 which OS version is iOS 12.1.4(16D57).

### Version information

OS:
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109

Device: 
iPhone 8, OS version is iOS 12.1.4(16D57)

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.0-rc.2
   @angular-devkit/build-angular : 0.12.1
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : ios 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 6 other plugins)

System:

   ios-sim : 8.0.1
   NodeJS  : v10.1.0 (/usr/local/Cellar/node/10.1.0/bin/node)
   npm     : 5.10.0
   OS      : macOS Mojave
   Xcode   : Xcode 10.1 Build version 10B61

Plugin:
cordova-plugin-camera 4.0.3 "Camera"

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by kevingrabher** [comment]
Reproduced:

Cordova CLI: 9.0.0 (cordova-lib@9.0.1)
Cordova Platforms : ios 5.0.1
@ionic/angular: 4.11.0
cordova-plugin-camera: 4.1.0


`let options = {sourceType: 0, destinationType: 0, encodingType: 1, targetWidth: 2048, targetHeight: 2048}`
`    this.camera.getPicture(options).then((imageData) => {`
`      let base64Image = "data:image/png;base64," + imageData;`
`      console.log(base64Image);`
`    }, (err) => {`
`      this.apiService.presentError(err);`
`    });`

**Comment by jyc66** [comment]
Same fix as Kevin but resolved conflicts : https://github.com/apache/cordova-plugin-camera/pull/515

**Comment by jyc66** [comment]
Can we merge this PR as it is a severe degredation in performance on iOS 13

**Comment by Sephyr0s** [comment]
Any progress on this?

**Comment by jyc66** [comment]
There are pr's that fix this but no one is merging it.

**Comment by nice2seeu** [comment]
Is this not merged yet?
