### ISSUE TITLE
Incorrect Orientation on Windows 10

### ISSUE THREAD

**Issue by MSwapna428** [apache/cordova-plugin-camera#448]
# Bug Report: Incorrect Orientation on Windows 10
We tried setting up with correctOrientation parameter and still the issue exist. 
The issue was fine until 2.3.1. After upgrading to 4.0.3, the orientation data is lost.

## Information
cordova platform list
Installed platforms:
  windows 6.0.1

cordova plugins list
at.gofg.sportscomputer.powermanagement 1.1.2 "PowerManagement"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-dialogs 1.3.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.2.0 "File Opener2"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 4.0.1 "Splashscreen"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-legacy-build-support 1.3.4 "Cordova sqlite legacy build support"
cordova-sqlite-storage 2.0.2 "Cordova sqlite storage plugin"

**Comment by Sushil1091Jes** [comment]
i am having the same issue

**Comment by gabrielberlanda** [comment]
I am having the same issue and I have already tried with `correctOrientation: true`.

**Comment by gabrielberlanda** [comment]
Changing from PNG to JPEG solved the orientation issue in my case, maybe the problem is just in PNG images.

**Comment by gabrielberlanda** [comment]
Guys, I'm sorry, the comment above just worked for android, with Windows the orientation error still hapenned.

**Comment by PabbleDabble** [comment]
I'll be picking this ticket up in our upcoming sprint.  If anyone is alerted by this message and has any new information, I would be greatly appreciative.  I'll report back findings as they arise.

**Comment by PabbleDabble** [comment]
@MSwapna428 Do you happen to remember what device you were using?  (Apologies if you're not supposed to mention people like that).

I develop an app that runs on a Windows Surface and running through the CameraProxy.js code, there is no path in that code that accesses the sensor (there is a bunch of code in this that deals with the sensor and orientation but that only seems to matter for the Windows phone).  

I've manually changed some of the code in testing and am able to use the native devices sensor to detect orientation and onOrientationChange events, however once the picture is captured I have no way to rotate it to match before saving the file and returning it back to my app.

**Comment by erisu** [comment]
[Cordova Windows](https://github.com/apache/cordova-windows) has been deprecated and is no longer supported making this issue obsolete.
