### ISSUE TITLE
Circular crop parameter

### ISSUE THREAD

**Issue by eeerrrttty** [apache/cordova-plugin-camera#451]
Pass to configurations an option to make a circular crop (0 or 1), as it can be used to profile photos. Then the crop preview will be circular.

**Comment by janpio** [comment]
Should the produced picture should still be rectangular?

(In general there is a reason we use issue templates like https://github.com/apache/cordova-plugin-camera/issues/new?template=FEATURE_REQUEST.md - issues using those have a much bigger chance to be taken into account)

**Comment by eeerrrttty** [comment]
Yes, the result will be rectangular

**Comment by eeerrrttty** [comment]
just the design as circle

**Comment by jcesarmobile** [comment]
This is not possible on iOS and probably not possible on Android neither, so going to close
