### ISSUE TITLE
App restart after getPicture() in Android

### ISSUE THREAD

**Issue by juppdes** [apache/cordova-plugin-camera#453]
# Bug Report
App restart after getPicture() in Android

## Problem
App restart after getPicture() in Android

### What is expected to happen?
Take a picture

### What does actually happen?
App restart 

### Environment, Platform, Device
cordova (Cordova CLI) : 9.0
Cordova Platforms : android 8.0
cordova-plugin-camera 4.0.3

**Comment by indraraj26** [comment]
I am having the same issue.

**Comment by Balgam** [comment]
Same problem here, however, very irregular and very difficult to reproduce.

**Comment by longtx1607** [comment]
I am having the same issue.

**Comment by Balgam** [comment]
I'm not sure but I assume that the app is terminated by the operating system due to lack of memory while using the camera app. Currently I'm not sure how to fix this.

**Comment by jtpdev** [comment]
I have the same issue, but only in a device with memory smaller than 3gb.

There was not a workarround to this?

**Comment by aximobile** [comment]
> I'm not sure but I assume that the app is terminated by the operating system due to lack of memory while using the camera app. Currently I'm not sure how to fix this.
> 
> EDIT:
> You can reproduce it by opening the camera, then filling the main memory with an app like FillRAM. After taking the picture, the Camera Activity will be closed and the app will restart.

I have the exact same feeling. Newer Android devices take pictures with a much higher resolution then the older ones.

**Comment by timbru31** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by OwenRay** [comment]
you can easily reproduce this by going into the develop settings and enable "Don't keep activities"

**Comment by breautek** [comment]
This is not a bug, but part of the Android lifecycle. The Android OS may kill activities that are in the background to preserve memory, particularly if the foreground activity requires a lot of memory. When you use the Camera App, it puts your app into the background.

This is documented here: https://github.com/apache/cordova-plugin-camera#android-quirks with an explanation of how to deal with these cases.
