### ISSUE TITLE
[Internal Apache Cordova] cordova-plugin-camera 4.0.3 is missing the `rel/` tag

### ISSUE THREAD

**Issue by janpio** [apache/cordova-plugin-camera#454]
There is no `rel/4.0.3` tag as the official Apache release tag:
https://github.com/apache/cordova-plugin-camera/releases/tag/rel%2F4.0.3

We should probably check if anything else is missing from that release.

npm release is present: https://www.npmjs.com/package/cordova-plugin-camera/v/4.0.3

**Comment by PieterVanPoyer** [comment]
I did add the tag on it.  https://github.com/apache/cordova-plugin-camera/releases/tag/rel%2F4.0.3

Seems like too long ago to see more things missing from that release.
