### ISSUE TITLE
Can not move picture in frame using allowEdit:true and Camera.PictureSourceType.CAMERA on iOS 

### ISSUE THREAD

**Issue by rastafan** [apache/cordova-plugin-camera#457]
# Bug Report

## Problem
On iOS, when using `allowEdit: true`, `sourceType: Camera.PictureSourceType.CAMERA` and a picture ration different from original (E.g. a square one), it is impossible to center the taken picture in the frame. It works fine when using `sourceType: Camera.PictureSourceType.PHOTOLIBRARY`.

### What is expected to happen?
One should be able to move the picture within the frame and/or zoom it in and out (with the limitation of having to cover the whole frame, of course), as it does when using `sourceType: Camera.PictureSourceType.PHOTOLIBRARY`. 

Here is a gif of the behaviour (might take a while to load).
![Issue Gif](https://sviluppo.controlliamo.com/issue.gif)

### What does actually happen?
The picture bounces back to the original position after being moved. It is possible to zoom in and move it horizontally when zoomed, but it is not vertically positionable. It works fine when using `sourceType: Camera.PictureSourceType.PHOTOLIBRARY`.

## Information

This used to work in older versions of this plugin as far as I remember.

### Command or Code

CameraOptions:

```
var options = {
   quality: 70, 
   destinationType: Camera.DestinationType.FILE_URI,
    sourceType: Camera.PictureSourceType.CAMERA,
    allowEdit: true,
    popoverOptions: CameraPopoverOptions,
    cameraDirection: 1,
    targetWidth: 720,
    targetHeight: 720,
    correctOrientation: true
};
```

### Environment, Platform, Device

We tested this on iPhone X with iOS 12.2

### Version information

Cordova: 9.0.0
Cordova iOS platform: 5.0.1
Ionic-CLI: 4.12.0
Ionic framework: 1.7.0

**Comment by rastafan** [comment]
@jcesarmobile bumping the post, just to know if there might be a solution to this.
We are currently using latest version and the issue still remains, so we need to use this in conjunction with another plugin (https://github.com/jeduan/cordova-plugin-crop), but it seems like a task that should be accomplished by this plugin by itself.

Thank you.

**Comment by jcesarmobile** [comment]
this is a bug in the native component the plugin uses, so only Apple can fix it
