### ISSUE TITLE
iOS Wrong image is shown

### ISSUE THREAD

**Issue by wynngd** [apache/cordova-plugin-camera#461]
# Bug Report

## Problem
On initial app run, the getpicture retrieves the correct photos properly. When I restart the app, photos being displayed are the photos selected in the previous session. there is some kind of cache not properly getting cleared. How to fix this?
### Environment, Platform, Device

iOS 12.0
plugin version 4.0.3
cordova ios 4.5.4

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
should be fixed by https://github.com/apache/cordova-plugin-camera/pull/306
