### ISSUE TITLE
Document `ANDROIDX_CORE_VERSION` preference

### ISSUE THREAD

**Issue by janpio** [apache/cordova-plugin-camera#472]
https://github.com/apache/cordova-plugin-camera/pull/751 added the `ANDROIDX_CORE_VERSION` preference to make  `androidx.core:core` configurable. As far as I could figure out this was not added to the documentation (README), so this should be done.

**Comment by jcesarmobile** [comment]
Updated si the the previous preference doesn’t exist, but the same happens with ANDROIDX_CORE_VERSION
