### ISSUE TITLE
Clicked image doesn't get deleted

### ISSUE THREAD

**Issue by Gurjit-ONEBCG** [apache/cordova-plugin-camera#476]
# Bug Report

Once I click the image and kill the app without clicking OK button of camera, in android image remain saved and keep showing in gallery. when I have set saveToPhtoAlbum=false. However if I click on OK image disappeared from gallery.

 Here are my camera options
-  const options: CameraOptions = {
            quality: 80,
            correctOrientation: true,
            destinationType: this.camera.DestinationType.DATA_URL,DataURI, NativeURI,
            sourceType: this.camera.PictureSourceType.CAMERA,
            allowEdit: true,
            encodingType: this.camera.EncodingType.JPEG,
            saveToPhotoAlbum: false,
            targetWidth: 300,
            targetHeight: 300,
            
          }
  
## Information
"cordova-plugin-camera": "^4.0.3"
IONIC 3
 
### Environment, Platform, Device
 SAMSUNG Galaxy J7 Sky pro

**Comment by breautek** [comment]
stale
