### ISSUE TITLE
Multiple clicks

### ISSUE THREAD

**Issue by prashantbhat84** [apache/cordova-plugin-camera#477]
### Issue Type

- [ ] Bug Report
- [x ] Feature Request
- [ ] Support Question

## Description
I would like to have multiple clicks per second and able to specify the time in seconds that the click should take place. 

### Environment, Platform, Device

Android

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
click?

**Comment by jcesarmobile** [comment]
Closing as it's unclear what you are asking
