### ISSUE TITLE
Unable to open Front camera in ANDROID

### ISSUE THREAD

**Issue by gigonzalezs** [apache/cordova-plugin-camera#481]
After setting the cameraDirection to 1 it still opens the back camera. 

This issue was open in order to document the fix

**Comment by lu1tr0n** [comment]
Question: When will this problem be solved?

**Comment by lu1tr0n** [comment]
Is there any solution to automatically open the front camera?

**Comment by sonikdesign** [comment]
Any solution about this problem? with plugin @cordova-plugin-camera-preview front camera setting works.

**Comment by PieterVanPoyer** [comment]
As mentioned in the android quirks, the cameraDirection does not work for Android. https://github.com/apache/cordova-plugin-camera#android-quirks-1

There is no official solution for Android to force a back or front camera with the current Intent setup. ( https://developer.android.com/training/camera/photobasics )
The heavy load of the Camera is delegated to the Camera app and there are some hacks for some devices, but it is not implemented in the Android part. And these hacks do not work reliable in any way.

Off course there are other setups possible when you work directly with the Camera api, but that setup is a lot more challenging.
That's the setup of https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview 

PR are off course welcome.
