### ISSUE TITLE
Not included in directory ''Localizable.strings'', after build.

### ISSUE THREAD

**Issue by megumih** [apache/cordova-plugin-camera#487]
After,My project build.
Look at the attached capture.

Not included in directory ''Localizable.strings''.
Why?
I'm using .xcworkspace file.

<img width="995" alt="スクリーンショット 2019-08-08 16 08 59" src="https://user-images.githubusercontent.com/10084100/62682694-be2a1380-b9f7-11e9-95a7-ce5e7f1164dd.png">

<img width="231" alt="スクリーンショット 2019-08-08 16 14 31" src="https://user-images.githubusercontent.com/10084100/62682685-b9655f80-b9f7-11e9-85f6-6e3fd0c76bb1.png">

#

**Comment by jcesarmobile** [comment]
Use a resource-file tag to copy resources to the project, just copying files is not enough for xcode to pick them
