### ISSUE TITLE
application crash on getPicture, ver 4.1.0, iOS 11.4.1

### ISSUE THREAD

**Issue by gborisg** [apache/cordova-plugin-camera#488]
# Bug Report
camera plugin 4.1.0 crashes my application on getPicture on iPhone 6 with iOS 11.4.1

## Problem
I was using cordova-plugin-camera 2.4.1, along with cordova-plugin-file 6.0.2 and cordova-plugin-photos 1.0.8. Everything was working fine, until I upgraded the camera plugin to latest 4.1.0. Now on getPicture the application terminates. The moment I move back to 2.4.1 - everything starts working fine.

### What is expected to happen?
a bug fix in next camera plugin version, this looks like a regression

### Environment, Platform, Device

PhoneGap build using Cordova cli-9.0.0
iPhone 6
iOS 11.4.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
You have to add the usage descriptions now
https://github.com/apache/cordova-plugin-camera#ios-quirks
