### ISSUE TITLE
Android clicking input type=file brings up system file browser, not camera options

### ISSUE THREAD

**Issue by alexcroox** [apache/cordova-plugin-camera#489]
# Bug Report

## Problem

When clicking on an html type="file" input a system file picker appears instead of camera options. 

![ss](https://cl.ly/3dc68efab053/Screenshot%202019-08-20%20at%2008.35.57.png)

### What is expected to happen?

If I perform the same action in the system browser I get the expected dialog:

![ss2](https://cl.ly/97f9c511714e/Screenshot%202019-08-20%20at%2008.38.29.png)

### Version information

```
"cordova-android": "^8.0.0",
"cordova-plugin-camera": "^4.1.0",
"cordova-plugin-file": "^6.0.2",
"cordova-plugin-file-transfer": "^1.7.1",
```

cordova-cli 9.0.0

Full [package.json and config.xml here](https://pastebin.com/raw/9MAjXxZR)

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
this is not a bug in this plugin, input file is handled by cordova-android. You already reported it there https://github.com/apache/cordova-android/issues/816

**Comment by Aarbel** [comment]
@jcesarmobile @alexcroox do you know / found a way to fix it ?
