### ISSUE TITLE
GrandUriPersmission in AndroidManifest.xml

### ISSUE THREAD

**Issue by maltorpro** [apache/cordova-plugin-camera#490]
The plugin sets the provider "org.apache.cordova.camera.FileProvider" with the grandUriPermission="true" in the AndroidManifest.xml.
According to google developer documentation https://developer.android.com/guide/topics/manifest/provider-element#gprmsn the given permission must be revoked via the function Context.revokeUriPermission().
Is it possible to remove the entry and use grantUriPermission before using the FileProvider and after revokeUriPermission in the class "CameraLauncher"?

**Comment by PieterVanPoyer** [comment]
@maltorpro can you clarify a little bit more on your expectation. The android permissions seems to work just fine.
Why should the given permission be revoked?

**Comment by PieterVanPoyer** [comment]
I am closing this issue, because there is not enough information / answers to start working on this.
