### ISSUE TITLE
Camera stuck recording/streaming in portrait

### ISSUE THREAD

**Issue by darthme** [apache/cordova-plugin-camera#491]
Hi,

I am new to ionic cordova and started with a simple android app that, with the help of the cordova camera and rtsp/rtmp plugin, pushes a stream to my server. My problem is the camera is locked to portrait mode, even when i change camera positions it may look like its landscape but when viewing recording or stream, its in portrait.

Unfortunately I am not sure which files I need to add or edit in order to get the camera to stay locked landscape. I had edited the CameraLauncer.java and set the correctOrientation to true which had been suggested but it has not worked

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊.  
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
