### ISSUE TITLE
Get Option for Cricular/Round Camera Preview 

### ISSUE THREAD

**Issue by Mrugank93** [apache/cordova-plugin-camera#493]
# Feature Request

## Motivation Behind Feature
Idea about capturing user's display picture

## Feature Description
I need the camera preview that should display Circular or Round shape but should capture the image normally (Rectangle/Square). This can help the user to get idea how their display profile picture will look like.

**Comment by jcesarmobile** [comment]
This is not possible with current implementation as the native elements used don't allow it. You'll have to create your own plugin.
