### ISSUE TITLE
iOS 13 Photo is not shown in Gallery

### ISSUE THREAD

**Issue by kneekicka** [apache/cordova-plugin-camera#494]
# Save taken Photos to the photo.app on iOS 13

## Motivation Behind Feature
On iOS 13, which is available in Beta Version. When you take a photo inside of the Cordova app, the photo doesn't land in photo.app and you cannot find it in gallery
saveToPhotoAlbum property is set to true

## Feature Description
I know that iOS 13 is in beta and still pretty raw and I don't know if this behaviour is like this in each cordova photo plugin. But would be nice to know if it's implementable(to save pictures after they are taken in the app).

**Comment by vlinde** [comment]
@kneekicka you can try this fix: https://github.com/vlinde/cordova-plugin-camera-with-exif/commit/4afa1516b0037768a4c51dfc4c77a9d04f68b886

**Comment by kneekicka** [comment]
@vlinde Thanks a lot for the response. These changes haven't helped in this case. I guess it has something to do with the saveToPhotoAlbum property

**Comment by kneekicka** [comment]
What solved it for me
CDVCamera.m

#import <Photos/Photos.h>

and

if (saveToPhotoAlbum && image) {
    UIImageWriteToSavedPhotosAlbum(image, nil, nil, nil);
}

**Comment by PieterVanPoyer** [comment]
@kneekicka  is this issue still present in the latest stable versions? If not, please close this issue.

**Comment by PieterVanPoyer** [comment]
Closing due to a lack of response. Issue is most likely not occuring in the latest release.
