### ISSUE TITLE
Android Bug in CameraLauncher.java cause "adding the current system time to the end of the file url"

### ISSUE THREAD

**Issue by BorntraegerMarc** [apache/cordova-plugin-camera#495]
# Bug Report

## Problem

Sometimes choosing an image with this plugin from image gallery will not work because file url is wrong.

On this line: https://github.com/apache/cordova-plugin-camera/blob/db4b4b947d53be1fc0ae929e793270392c7fc8aa/src/android/CameraLauncher.java#L738 we add the current system time to the end of the file URL. This leads to a problem if this line is actually executed that the returned file URL can not be read from the webview.

Because: If we try to read the file in the file system with the name `filename.jpg?1234` then it obviously doesn't exist. Because the last part was added.

I'm trying to figure out why this timestamp is added? The code was added 6 years ago.

The related comment `The modified image is cached by the app` does not give a lot of insights.

### What is expected to happen?

The callbackContext returned string shouldn't include the timestamp.

### What does actually happen?

Timestamp included in file url.

## Information

Choose a file that triggers the code referenced. Maybe by choosing a file that isn't locally downloaded (like from GDrive or OneDrive).

### Environment, Platform, Device

Android 9

### Version information

Latest version of this Plugin

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by jcesarmobile** [comment]
If you read from de filesystem you need to remove what’s after the ? (Included). The webview is able to do so automatically if you put it in an img tag (in example).
That’s done because of caching problems on the webview that can show a previous image.
