### ISSUE TITLE
FileUri returned by camera.getPicture() with SourceType PHOTOLIBRARY cannot be resolved

### ISSUE THREAD

**Issue by dominic-simplan** [apache/cordova-plugin-camera#496]
# Bug Report

### What is expected to happen?
camera.getPicture() with SourceType = Camera.PictureSourceType.PHOTOLIBRARY and DestinationType = FILE_URI should return a fileUri which can be resolved by window.resolveLocalFileSystemURL() on Windows 10

### What does actually happen?
camera.getPicture() returns a string which cannot be resolved, looking something like this: `blob:9954c-xxx- ...`.
Only workaround seems to be to set the DestinationType to NATIVE_URI.

See also this (old) question on stockoverflow: https://stackoverflow.com/questions/26139679/cordova-windows-8-app-blob-url-to-ms-appdata-url

### Environment, Platform, Device
Windows 10

### Version information
Cordova Windows 6.0.1
Cordova CLI 8.1.2
cordova-plugin-camera: 4.0.3

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
[Cordova Windows](https://github.com/apache/cordova-windows) has been deprecated and is no longer supported making this issue obsolete.
