### ISSUE TITLE
Save with specific name and into a specific folder

### ISSUE THREAD

**Issue by emieuxcharles** [apache/cordova-plugin-camera#497]
Hi,
I need to save the picture a take into a specific folder with a specific name.
Here is my code to take picture: 

public takePhoto() {
    console.log('Camera Photo Click');
    const options: CameraOptions = {
      quality: 100,
      destinationType: this.camera.DestinationType.DATA_URL,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE,
      saveToPhotoAlbum: true,
    }
    this.camera.getPicture(options).then((imageData) => {
    let base64Image = 'data:image/jpeg;base64,' + imageData;

    this.currentImage = base64Image;
    this.arrayImg.push(this.currentImage);

    }, (err) => {
    // Handle error
    });
  }

Thanks

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason 😉 
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by jcesarmobile** [comment]
This is not possible, if you want that you'll have to re save the photo using cordova-plugin-file
