### ISSUE TITLE
navigator.camera undefined

### ISSUE THREAD

**Issue by iakwvina** [apache/cordova-plugin-camera#498]
I have an issue with cordova-plugin-camera when I call navigator.camera.getPicture(cameraSuccess, cameraError, [cameraOptions]);
While cordova and cordova-plugin-camera plugin is loaded, it says that camera is undefined.

Cordova version: 6.1.2
 cordova-plugin-camera plugin: 4.1.0

I have tried it on Android 5.1.1 (emulator device) and Android 7 & 9 on physical devices.

**Comment by xyozio** [comment]
`navigator.camera` is not available until after the `deviceready` event.

```
document.addEventListener("deviceready", onDeviceReady, false);
function onDeviceReady() {
    console.log(navigator.camera);
}
```

**Comment by xyozio** [comment]
@iakwvina OK?

**Comment by jcesarmobile** [comment]
4.1.0 of the plugin requires cordova-android >=6.3.0 and cordova >=7.1.0.
Update your cordova version or use an older version of the plugin
