### ISSUE TITLE
Camera return different file name when picking the same image from gallery.

### ISSUE THREAD

**Issue by cikcoh** [apache/cordova-plugin-camera#503]
# Bug Report

## Problem

Camera return different file name when picking the same image from gallery.

### What is expected to happen?

The same file name should be return when picking the same image.

### What does actually happen?

Different file name is return for the same image.

file:///var/mobile/Containers/Data/Application/98D7C3AE-A24F-46CE-A3B4-CF03B26355BE/tmp/cdv_photo_001.jpg
file:///var/mobile/Containers/Data/Application/98D7C3AE-A24F-46CE-A3B4-CF03B26355BE/tmp/cdv_photo_002.jpg 

## Information

This is important because, i want to check for image duplication. since it returns different name for the same image, duplication checking function no longer works.

Works fine in Android.

### Command or Code

        const options: CameraOptions = {
          quality: 100,
          destinationType: this.camera.DestinationType.FILE_URI,
          sourceType: this.camera.PictureSourceType.PHOTOLIBRARY,
          mediaType: this.camera.MediaType.ALLMEDIA
        }

      this.camera.getPicture(options).then((mediaData) => {}):

### Environment, Platform, Device
 iOS 11.4.1, iPhone 6 
### Version information
What are relevant versions you are using?
    "cordova-plugin-camera": "^4.0.3",
    "@ionic-native/camera": "^5.0.0",
    "cordova": "8.0.0",
    "cordova-ios": "4.5.5",
    "ionic-angular": "3.9.2",

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
When using DestinationType.FILE_URI a temp image is saved to the disk and returned, so it has to have a different name every time. 
If you need that feature you'll need a new plugin, won't be possible with this one
