### ISSUE TITLE
 after auto back when take picture

### ISSUE THREAD

**Issue by WIlson-shuoshuoya** [apache/cordova-plugin-camera#504]
when i was take picture ,camera auto goback html ,i want   like android camera can continuity take,help

**Comment by jcesarmobile** [comment]
Can you provide more information and/or a sample app where the issue can be reproduced?

**Comment by vgmcglaughlin** [comment]
I believe I'm seeing the same issue. When I successfully take a picture or select from saved pictures, the success callback fires, then the application behaves as if `window.history.back()` was executed. (I don't believe it's actually calling `window.history.back()`, but the effect is the same, transitioning the view to the previous view on the stack.)

**Comment by iMestav** [comment]
Hi, I have this problem. 

You can see on this video : https://streamable.com/xz6xm 

Sometimes camera auto go back when i trigger open camera.

**Comment by jcesarmobile** [comment]
closing since the original reporter didn't answer and the problem is unclear.
please, when reporting issues provide all the information that the template request instead of deleting it
