### ISSUE TITLE
iOS 13 Picking video from Camera Roll, URL (FILE_URI) returned error

### ISSUE THREAD

**Issue by litiobat** [apache/cordova-plugin-camera#505]
When you've picked a video file from gallery/camera roll (no affected to photos, only to videos), the URL returned is not "Applications/tmp" as usual but "PluginKitPlugin/" directory not proprietary and you gets permission error as "NSCocoaErrorDomain Code=257" if you try to access it, for upload to server for example.

Only affected to video (I don't try it recording a video only picking from camera roll), never to photos.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason 😉 
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by wolfg1969** [comment]
Same with #506
