### ISSUE TITLE
Webview is under statusbar after camera interface is dismissed

### ISSUE THREAD

**Issue by fjckls** [apache/cordova-plugin-camera#511]
# Bug Report

## Problem
In iOS after closing native camera interface and returning to the cordova webview,  `cordova-plugin-statusbar` is not respected

### What is expected to happen?
`cordova-plugin-statusbar` is taken into account and cordova APP should be rendered using provided settings inside config.xml :
```
<preference name="StatusBarOverlaysWebView" value="false"/>
<preference name="StatusBarBackgroundColor" value="#F27D09"/>
```

### What does actually happen?
After closing native camera interface, the cordova app appears under the status bar

## Information
Repo here: https://github.com/fjckls/cordova-google-maps-issues

### Environment, Platform, Device
iOS

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

## Before
![IMG_0111](https://user-images.githubusercontent.com/2750675/66836114-7381c600-ef69-11e9-9d42-2a136a197fb3.PNG)
## After
![IMG_0112](https://user-images.githubusercontent.com/2750675/66836143-7c729780-ef69-11e9-8f08-13199f082d5a.PNG)

**Comment by Crash--** [comment]
thanks for reporting the issue. See this issue : https://github.com/apache/cordova-plugin-statusbar/issues/156

**Comment by fjckls** [comment]
If Iam not mistaken then solution is to change `src/ios/CDVCamera.m` here:

```
- (BOOL)prefersStatusBarHidden
{
    // return YES;
    return NO;
}
```
Why is it necessary to hide status bar?

**Comment by Steco17** [comment]
Hi. i have this same issue. even after putting the status bar overlay false using the apache/cordova-plugin-statusbar, after i use my camera to with this camera plugin the status bar overlays

**Comment by breautek** [comment]
Reworded the title to be a better summary of the described problem.

**Comment by jcesarmobile** [comment]
This was a problem in statusbar plugin, has been fixed there https://github.com/apache/cordova-plugin-statusbar/pull/157

**Comment by tryhardest** [comment]
Any ideas on how to fix this on Android? WIth and without the status bar plugin, when we return from native view on camera or media capture, the webview drops a few pixels and moves up again.

When we remove the statusbar fully, it does not occur. We need the status bar. I see the iOS fix.
