### ISSUE TITLE
THREAD WARNING: exec() call to Camera.takePicture blocked the main thread for 291ms. Plugin should use CordovaInterface.getThreadPool().

### ISSUE THREAD

**Issue by alindzon** [apache/cordova-plugin-camera#514]
# Bug Report
this is happening one specific type of android device, but might indicate a bigger issue.
CAT S31 running android 8.1.0

## Problem
camera does not return image 

### What is expected to happen?
It normally returns the image

### What does actually happen?
W/PluginManager: THREAD WARNING: exec() call to Camera.takePicture blocked the main thread for 291ms. Plugin should use CordovaInterface.getThreadPool().
D/CordovaActivity: Paused the activity.
D/CordovaWebViewImpl: >>> loadUrl(javascript:cordova.plugins.backgroundMode._setActive(true);cordova.plugins.backgroundMode.on('activate', null);cordova.plugins.backgroundMode.fireEvent('activate',null);)
D/YoikScreenOrientation: execute action: screenOrientation
D/YoikScreenOrientation: Requested ScreenOrientation: portrait-primary
W/Adreno-ES20: <core_glFinish:34>: glFinish skipped: 0
W/Adreno-ES20: <core_glFinish:34>: glFinish skipped: 0
W/Adreno-ES20: <core_glFinish:34>: glFinish skipped: 0
D/CordovaActivity: Stopped the activity.
W/Adreno-ES20: <core_glFinish:34>: glFinish skipped: 0
W/Adreno-ES20: <core_glFinish:34>: glFinish skipped: 0
D/CordovaActivity: Incoming Result. Request code = 33
D/CordovaInterfaceImpl: Sending activity result to plugin
D/CordovaActivity: Started the activity.
D/CordovaActivity: Resumed the activity.

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
> W/PluginManager: THREAD WARNING: exec() call to Camera.takePicture blocked the main thread for 291ms. Plugin should use CordovaInterface.getThreadPool().

Has nothing to do with the camera taking a picture or not. All this states that that method is on the main thread and it blocked it for ~300ms, so it should probably be moved off of the main thread so the phone can still feel responsive.

What's more interesting is:

> D/CordovaActivity: Stopped the activity.

I'm not 100% sure if this is the low memory android quirk as I never actually encountered this situation myself but...

> Android uses intents to launch the camera activity on the device to capture images, and on phones with low memory, the Cordova activity may be killed. In this scenario, the result from the plugin call will be delivered via the resume event. See the Android Lifecycle guide for more information. The pendingResult.result value will contain the value that would be passed to the callbacks (either the URI/URL or an error message). Check the pendingResult.pluginStatus to determine whether or not the call was successful.

https://github.com/apache/cordova-plugin-camera#android-quirks

Let me know if this helps.

**Comment by mirko77** [comment]
> > W/PluginManager: THREAD WARNING: exec() call to Camera.takePicture blocked the main thread for 291ms. Plugin should use CordovaInterface.getThreadPool().
> 
> Has nothing to do with the camera taking a picture or not. All this states that that method is on the main thread and it blocked it for ~300ms, so it should probably be moved off of the main thread so the phone can still feel responsive.
> 
> What's more interesting is:
> 
> > D/CordovaActivity: Stopped the activity.
> 
> I'm not 100% sure if this is the low memory android quirk as I never actually encountered this situation myself but...
> 
> > Android uses intents to launch the camera activity on the device to capture images, and on phones with low memory, the Cordova activity may be killed. In this scenario, the result from the plugin call will be delivered via the resume event. See the Android Lifecycle guide for more information. The pendingResult.result value will contain the value that would be passed to the callbacks (either the URI/URL or an error message). Check the pendingResult.pluginStatus to determine whether or not the call was successful.
> 
> https://github.com/apache/cordova-plugin-camera#android-quirks
> 
> Let me know if this helps.

We are getting the same 'D/CordovaActivity: Stopped the activity', related to #345

**Comment by alindzon** [comment]
Solved by changing the camera app.  We isolated this issue to snapdragon based devices, tested with Open Camera, and the issue went away.

**Comment by mirko77** [comment]
@alindzon are you going to tell all your users to change the camera app?

**Comment by alindzon** [comment]
I consider it a work around until the real issue is resolved.  So the short answer is if a client needs to use our photo feature, then they have to install Open Camera to make it work on those devices.  We have an open case with bullitt-group.com  about the issue since they make some of the phones in question and as a manufacturer they can deal with Qualcomm.  Their S31 and S61 have Snapdraggon and have this issue.  Their S41 uses a different processor, and no issue.

We tested on Google pixel that uses the snapdraggon, same issue, one that does not, no issue.

Seems to be something Qualcomm did.

**Comment by mirko77** [comment]
Same issue on Xiaomi MI devices with Qualcomm Snapdragon 712

**Comment by alindzon** [comment]
I would be shocked if there were any devices running Snapdragon work.  The S31 uses Qualcomm MSM8909 Quad core, the S61 uses Qualcomm SD630 Octacore 2.2GHz.  Bet the entire family uses the same libraries which are messed up in some way.

**Comment by mirko77** [comment]
We do not have any issues on the Pixel 2 and Pixel 3A. 

On the MI devices, it happens randomly though, not always.

**Comment by mirko77** [comment]
But how would using Open Camera solve the issue? We are experiencing the same, with Open Camera no crashes, with the stock camera a lot of issues.

**Comment by fatehMohamed14** [comment]
Hello, any news about this issue, i'm having it on a specific device :/
