### ISSUE TITLE
android 10 qusetion of CAMERA

### ISSUE THREAD

**Issue by Super-Jiang** [apache/cordova-plugin-camera#517]
# Bug Report
你好，我说的是汉语不知道是否能解决
## Problem
关于adnroid 10 插件不兼容问题，拍照按钮点击了但是照片没有生成
### What is expected to happen?
我测试机  荣耀20 pro   android 10版本，在使用插件进行拍照的时候出现点击拍摄按钮后没有任何的反应（仅仅是闪了一下，不会出现拍摄成功），无论前后摄像头

### What does actually happen?

我测试机  荣耀20 pro   android 10版本，在使用插件进行拍照的时候出现点击拍摄按钮后没有任何的反应（仅仅是闪了一下，不会出现拍摄成功），无论前后摄像头

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Please provide an English translation, thank you.

**Comment by Super-Jiang** [comment]
> 请提供英文翻译，谢谢。
ok
I test the HUAWEI HONOR 20 Pro Android 10 version of the machine. When using the plug-in to take photos, there is no response after clicking the capture button (a flash will appear, and the shooting will not succeed), no matter the front and rear cameras.

**Comment by GuShiwei** [comment]
I have the same problem on HUAWEI HONOR V20, OS is Magic 3.0.0 base on android 10, please help us

**Comment by Super-Jiang** [comment]
> 我在HUAWEI HONOR V20上遇到了相同的问题，基于Android 10的操作系统是Magic 3.0.0，请帮助我们

https://github.com/apache/cordova-plugin-camera/issues/520

看一下这个链接，这里有解决方法，不知道是不是一样的

**Comment by GuShiwei** [comment]
你解决了这个问题吗，我这边就一台手机会这样子，点拍照没反应，但是偶尔也能拍成功，很奇怪，会报错No Image Selected

**Comment by Super-Jiang** [comment]
> 你解决了这个问题吗，我这边就一台手机会这样子，点拍照没反应，但是偶尔也能拍成功，很奇怪，会报错

document.addeventlistener（“ deviceready”，ondevicereready，false）；
功能onDeviceReady（）{destinationType = navigator.camera.DestinationType; }


这个加了吗

**Comment by GuShiwei** [comment]
> > 我在HUAWEI HONOR V20上遇到了相同的问题，基于Android 10的操作系统是Magic 3.0.0，请帮助我们
> 
> #520
> 
> 看一下这个链接，这里有解决方法，不知道是不是一样的

你好，请问一下document.addeventlistener ("deviceready", ondevicereready, false);这个要加在什么地方呢，我是在ionic环境下面用的这个插件，非常感谢！能把代码写的详细一点吗？

**Comment by GuShiwei** [comment]
我在代码里面追加了platform.ready(),把拍照放到这个里面还是不行

**Comment by Super-Jiang** [comment]
> 我在代码里面追加了platform.ready（），把镜头放到这个里面还是不行

在哪调用的插件？直接是java代码里面吗，，，，我的在js里面调用的插件，这个放到了js里

**Comment by GuShiwei** [comment]
getPicture(type) {
    this.plt.ready().then(() => {
      // 照片配置设置
      const options: CameraOptions = {
        // 图片质量
        quality: 100,
        // 返回图片类型，DATA_URL：返回base64格式，FILE_URI：返回安卓的照片路径，NATIVE_URI：返回IOS的照片路径
        destinationType: this.camera.DestinationType.FILE_URI,
        // 照片格式
        encodingType: this.camera.EncodingType.JPEG,
        // 照片类型，PICTURE：照片，VIDEO：视频，ALLMEDIA：所有格式
        mediaType: this.camera.MediaType.PICTURE
      };
      this.camera.getPicture(options).then(
        imageData => {
          // imageData is either a base64 encoded string or a file URI
          // If it's base64 (DATA_URL):
          let base64Image = "data:image/jpeg;base64," + imageData;
          console.log(imageData);
          // 存放相册
          this.photoLibrary.requestAuthorization().then(res => {
            this.photoLibrary
              .saveImage(imageData, "MIBS")
              .then(res => {})
              .catch(error => {
                `alert(error);`
              });
          });
        },
        err => {
          // Handle error
          // alert("照片拍摄错误")
          console.log(err);
        }
      );
    });
  }


我是这么写的，我的是ionic3工程

**Comment by Super-Jiang** [comment]
> getPicture（type）{ 
> this.plt.ready（）。then（（）=> { 
> //照片配置设置
> const选项：CameraOptions = { 
> //图片质量
> ：100，
> //返回图片类型，DATA_URL：返回base64格式，， FILE_URI：返回安卓的照片路径，NATIVE_URI：返回IOS的照片路径
> destinationType：this.camera.DestinationType.FILE_URI，
> //照片格式
> 编码
> 类型：this.camera.EncodingType.JPEG，//照片类型，图片：照片，VIDEO ：视频，ALLMEDIA：所有格式
> mediaType：this.camera.MediaType.PICTURE 
> }; 
> this.camera.getPicture（options）.then（
> imageData => { 
> // imageData是base64编码的字符串或文件URI 
> //如果是base64（DATA_URL）：
> let base64Image =“ data：image / jpeg; base64，” + imageData; 
> console.log（imageData）;
> // //存放相册
> this.photoLibrary.requestAuthorization（）。then（res => { 
> this.photoLibrary 
> .saveImage（imageData，“ MIBS” ）.then（res = 
> > {}）. 
> catch（error => { 
> `alert(error);`
> }）; 
> } ）; 
> }，
> err => { 
> //处理错误
> // alert（“照片拍摄错误”）
> console.log（err）; 
> } 
> ）；
> }）; 
> }
> 
> 我是这么写的，我的是ionic3工程
在这个上面加上试一下，
document.addeventlistener ("deviceready", ondevicereready, false);
function onDeviceReady() { destinationType=navigator.camera.DestinationType; }

**Comment by GuShiwei** [comment]
document.addeventlistener ("deviceready", ondevicereready, false);
function onDeviceReady() { destinationType=navigator.camera.DestinationType; }
这个在ionic里面怎么加呢，放到constructor()里面，下面这样写可以吗？destinationType是什么？
constructor(){
    document.addEventListener("deviceready", onDeviceReady, false);
    function onDeviceReady() {
      this.destinationType = this.camera.DestinationType;
    }
}

**Comment by jcesarmobile** [comment]
Closing as I don’t understand a word and the template was not filled.

**Comment by shixb** [comment]
> 



> getPicture(type) { this.plt.ready().then(() => { // 照片配置设置 const options: CameraOptions = { // 图片质量 quality: 100, // 返回图片类型，DATA_URL：返回base64格式，FILE_URI：返回安卓的照片路径，NATIVE_URI：返回IOS的照片路径 destinationType: this.camera.DestinationType.FILE_URI, // 照片格式 encodingType: this.camera.EncodingType.JPEG, // 照片类型，PICTURE：照片，VIDEO：视频，ALLMEDIA：所有格式 mediaType: this.camera.MediaType.PICTURE }; this.camera.getPicture(options).then( imageData => { // imageData is either a base64 encoded string or a file URI // If it's base64 (DATA_URL): let base64Image = "data:image/jpeg;base64," + imageData; console.log(imageData); // 存放相册 this.photoLibrary.requestAuthorization().then(res => { this.photoLibrary .saveImage(imageData, "MIBS") .then(res => {}) .catch(error => { `alert(error);` }); }); }, err => { // Handle error // alert("照片拍摄错误") console.log(err); } ); }); }
> 
> 我是这么写的，我的是ionic3工程

问题怎么解决的呢，分享一下吧
