### ISSUE TITLE
cordova-plugin-camera not compatible with cordova-support-google-services plugin

### ISSUE THREAD

**Issue by RobotBroer** [apache/cordova-plugin-camera#518]
Suddenly from today my project fails to build only with this specific plugin. There was initially another issue with plugin cordova-support-google-services explained by this thread: 

[https://stackoverflow.com/questions/58529904/error-could-not-find-org-jetbrains-kotlinkotlin-stdlib-jdk81-3-60-eap-25-in-i](url)

Basically a `com.android.tools.build:gradle` upgrade to 4.0.0 for plugin: cordova-support-google-services

It is easy to fix this error by specifying a specific dependency version: `com.android.tools.build:gradle:3.5.0`
at  `<projectroot>/platforms/android/cordova-support-google-services/<project>-build.gradle`

Fixing the problem however left the following build error:

# The problem

> D8: Program type already present: android.support.v4.os.ResultReceiver$1
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
>   Program type already present: android.support.v4.os.ResultReceiver$1

# I have tried

Removing the cordova-support-google-services plugin allowed us to build successfully again. The issue is however the cordova-support-google-services plugin is required for Firebase. 

There should be some conflict in terms of the upgrade of cordova-support-google-services to com.android.tools.build:gradle:4+` and cordova-plugin-camera.

# Project Info

Ionic:

   ionic (Ionic CLI)  : 4.8.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.1.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 14 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/Library/Android/sdk)
   NodeJS            : v11.7.0 (/usr/local/Cellar/node/11.7.0/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
   Xcode             : Xcode 11.1 Build version 11A1027

**Comment by mhartington** [comment]
This is not really specific to Ionic, so not sure why it's mentioned. If this happens in a vanilla cordova project, might want to update the issue and title.

If the change is minimal, I'm sure a PR would be greatly appreciated

**Comment by RobotBroer** [comment]
The project is an Ionic 3 project. I do not have a simple solution for this, no idea why this is happening. Not sure if I am the only one experiencing this issue on this plugin.

**Comment by alexiscm72** [comment]
After change to 4.1.0 build fail with dupplicated entry for com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v13/view/DragAndDropPermissionsCompat.class

**Comment by AlibekJ** [comment]
Can confirm this behavior. 
Just like @RobotBroer reported.

**Comment by PieterVanPoyer** [comment]
Is this issue still present with the latest camera-plugin version? 5.0.2.

**Comment by AlibekJ** [comment]
Seems to be working fine now.

**Comment by PieterVanPoyer** [comment]
Thanks for your reply. Seems to be fixed with latest Cordova tooling.
