### ISSUE TITLE
IOS 13:Open the camera and return to the page. The page moves up and navbar is covered.

### ISSUE THREAD

**Issue by jackey-ho** [apache/cordova-plugin-camera#521]
IOS 13:Open the camera and return to the page. The page moves up and navbar is covered.

**Comment by brianarpie** [comment]
I also am experiencing this issue!

**Comment by sc0ttdav3y** [comment]
I'm currently working through this on my own project, and I think this may solve the issue
https://github.com/apache/cordova-plugin-statusbar/issues/156

**Comment by jackey-ho** [comment]
I annotated "this. Statusbar. Overlays WebView (false);" this code, and the following CSS about statusbar.

// .ios ion-menu > .menu-inner > .toolbar.statusbar-padding:first-child ion-segment,
// .ios ion-menu > .menu-inner > .toolbar.statusbar-padding:first-child ion-title,
// .ios ion-menu > .menu-inner > ion-header > .toolbar.statusbar-padding:first-child ion-segment,
// .ios ion-menu > .menu-inner > ion-header > .toolbar.statusbar-padding:first-child ion-title,
// .ios ion-nav > .ion-page > .toolbar.statusbar-padding:first-child ion-segment,
// .ios ion-nav > .ion-page > .toolbar.statusbar-padding:first-child ion-title,
// .ios ion-nav > .ion-page > ion-header > .toolbar.statusbar-padding:first-child ion-segment,
// .ios ion-nav > .ion-page > ion-header > .toolbar.statusbar-padding:first-child ion-title,
// .ios ion-tab > .ion-page > ion-header > .toolbar.statusbar-padding:first-child ion-segment,
// .ios ion-tab > .ion-page > ion-header > .toolbar.statusbar-padding:first-child ion-title,
// .ios ion-tabs > .ion-page.tab-subpage > ion-header > .toolbar.statusbar-padding:first-child ion-segment,
// .ios ion-tabs > .ion-page.tab-subpage > ion-header > .toolbar.statusbar-padding:first-child ion-title {
//   padding-top: 0;
//   height: calc(44px + 0px);
//   min-height: calc(44px + 0px);
//   line-height: calc(44px + 0px);
// }

// .ios ion-menu > .menu-inner > .toolbar.statusbar-padding:first-child,
// .ios ion-menu > .menu-inner > ion-header > .toolbar.statusbar-padding:first-child,
// .ios ion-nav > .ion-page > .toolbar.statusbar-padding:first-child,
// .ios ion-nav > .ion-page > ion-header > .toolbar.statusbar-padding:first-child,
// .ios ion-tab > .ion-page > ion-header > .toolbar.statusbar-padding:first-child,
// .ios ion-tabs > .ion-page.tab-subpage > ion-header > .toolbar.statusbar-padding:first-child {
//   padding-top: 0;
//   min-height: calc(44px + 0px);
// }

and then it work for me,but I still don't know why. I hope this will help you.

**Comment by jalilmotaz** [comment]
Ran into the same issue. I fixed this by calling statusbar.hide() before opening camera and then statusbar.show() after camera closes. This fixes the issue temporarily

**Comment by jcesarmobile** [comment]
the issue is on the statusbar plugin, it's been reported there https://github.com/apache/cordova-plugin-statusbar/issues/156 and fixed https://github.com/apache/cordova-plugin-statusbar/pull/157
