### ISSUE TITLE
Images broken upload

### ISSUE THREAD

**Issue by ashrafsaqib** [apache/cordova-plugin-camera#522]
# Bug Report

### What is expected to happen?

Image should be same as shown in gallery

### What does actually happen?

Image appears half black in some cases after uploaded to server

## Information

using this plugin to upload image to web server, while uploading some images appear broken / half black on server

### Environment, Platform, Device

Android version 9 

### Version information

Plugins version 4.1.1-dev

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by timbru31** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by ashrafsaqib** [comment]
I found an internet connection issue that broke the images during upload.
