### ISSUE TITLE
Camera does not open iOS

### ISSUE THREAD

**Issue by leandroseja** [apache/cordova-plugin-camera#532]
# Bug Report
Camera.getPicture: source type 1 not available -  iOS

## Problem

Hello friends, this is the first time.
Sorry if I did something wrong.
I am using ionic 3 (--type = ionic-angular)

My camera was working and I updated some things in my app. That's when the camera stopped working, only ios, in the latest updates. I tried to go back to 4.0.3 and it didn't work out.
The photo gallery is working !!! Only the camera to take a picture that has stopped working.
Returns
I tried on xcode 11.1 and it didn't work either.
Error Print: https://prnt.sc/q2jce0 and https://prnt.sc/q2jc8h

I tried installing with the commands below
I do not know what else to do.
Could you help me with that?

@ionic-native/camera": "^4.20.0"
cordova-plugin-camera: 4.0.3

ionic cordova plugin add cordova-plugin-camera
npm install --save @ionic-native/camera@4

ionic cordova plugin add https://github.com/spoonconsulting/cordova-plugin-camera.git
npm install --save @ionic-native/camera@4

ionic cordova plugin add cordova-plugin-camera
npm install --save @ionic-native/camera@

### What is expected to happen?
Open iOS Camera

### What does actually happen?
Does not open and return error message
Camera.getPicture: source type 1 not available. 

### Command or Code

const options: CameraOptions = {
                    quality: 60,
                    destinationType: this.camera.DestinationType.DATA_URL,
                    encodingType: this.camera.EncodingType.JPEG,
                    mediaType: this.camera.MediaType.PICTURE,
                   sourceType : this.camera.PictureSourceType.CAMERA, // I tested removing this line
                    targetWidth: 500,
                    saveToPhotoAlbum: false,
                    correctOrientation:true
                  }

                     this.camera.getPicture(options).then((imageData) => {
                     this.base64 = 'data:image/jpeg;base64,' + imageData;
                    }, (err) => {
                     // Handle error
                     console.log(err);
                    });

### Version information

XCODE 10.1

Ionic:

   Ionic CLI          : 5.4.9 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 5.1.0
   Cordova Plugins   : 

cordova-plugin-camera 4.1.1-dev "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 5.0.1 "Diagnostic"

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v11.12.0 (/usr/local/Cellar/node/11.12.0/bin/node)
   npm    : 4.6.1
   OS     : macOS High Sierra

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

![Captura de Tela 2019-11-26 às 20 03 14](https://user-images.githubusercontent.com/20361632/69679948-3e988100-1088-11ea-9ae6-7c257c19e1fc.png)
![Captura de Tela 2019-11-26 às 20 02 54](https://user-images.githubusercontent.com/20361632/69679953-422c0800-1088-11ea-80b3-a57f2a44d495.png)

**Comment by Basher888** [comment]
Did you get this sorted?

**Comment by jcesarmobile** [comment]
The camera doesn't work on iOS simulators

**Comment by ockang** [comment]
Hello I have the same problem, how did you solve it?

**Comment by Basher888** [comment]
Yes – was some time ago so cant remember how – I think I updated the cordova version

**Comment by leandroseja** [comment]
> Olá estou com o mesmo problema, como você o resolveu?



> Hello I have the same problem, how did you solve it?

Hello Friend.
I found out that using the XCode Simulator, taking pictures doesn't work.
When I tested it on my cell phone it worked.
See if that's not it.
