### ISSUE TITLE
`getExternalStoragePublicDirectory` is deprecated in API level 29

### ISSUE THREAD

**Issue by rodrigograca31** [apache/cordova-plugin-camera#534]
# Bug Report
`getExternalStoragePublicDirectory` is [deprecated in API level 29](https://developer.android.com/reference/android/os/Environment.html#getExternalStoragePublicDirectory(java.lang.String))
## Problem
I didnt run into any problem exactly but I was updating a plugin I maintain to work with Android 10 (Q, Api 29) [cordova-plugin-canvas2image-updated](https://github.com/rodrigograca31/Canvas2ImagePlugin) and while searching for occurences of this API noticed this plugin was also using it... 
https://github.com/apache/cordova-plugin-camera/blob/295e928784e2a9785982fbf15b05215a317774df/src/android/CameraLauncher.java#L608-L609

I also have a related issue on my plugin so I will [link it here...](https://github.com/rodrigograca31/Canvas2ImagePlugin/issues/10)
## Information

[This thread may help](https://stackoverflow.com/questions/56468539/getexternalstoragepublicdirectory-deprecated-in-android-q)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
It's not currently marked as deprecated anymore. But I'd believe you if you say it was. Google likes to go back and forth on stuff all the time.

Closing as obsolete.
