### ISSUE TITLE
GoogleCamera Orientation error

### ISSUE THREAD

**Issue by zhangjianying** [apache/cordova-plugin-camera#535]
# Bug Report

## Problem
googleCamera Photo rotation angle is always 0

I find CameraLauncher.java
  private int exifToDegrees(int exifOrientation) {
        if (exifOrientation == ExifInterface.ORIENTATION_ROTATE_90) {
            return 90;
        } else if (exifOrientation == ExifInterface.ORIENTATION_ROTATE_180) {
            return 180;
        } else if (exifOrientation == ExifInterface.ORIENTATION_ROTATE_270) {
            return 270;
        } else {
            return 0;
        }
    }

when exifOrientation = 6 [ExifInterface.ORIENTATION_ROTATE_90] ,  the return 0

### fix 

CameraLauncher.java
-->  line: 844
   private int exifToDegrees(int exifOrientation) {
            int retVal = 0;
            switch (exifOrientation) {
                case ExifInterface.ORIENTATION_ROTATE_90:
                    retVal = 90;
                    break;
                case ExifInterface.ORIENTATION_ROTATE_180:
                    retVal = 180;
                    break;
                case ExifInterface.ORIENTATION_ROTATE_270:
                    retVal = 270;
                    break;
                default:
                    retVal = 0;
            }
            return retVal;
    }

**Comment by timbru31** [comment]
You're switch-case seems the same as the current if-else - I don't understand what the change should change. Without proper code formatting with `` it is very hard to read the statements.

Also, the issue template exists for a reason. 😊.  
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
