### ISSUE TITLE
Not getting base64 string when source is Camera

### ISSUE THREAD

**Issue by patrickbussmann** [apache/cordova-plugin-camera#536]
# Bug Report

### What is expected to happen?
I get a base64 encoded string of the picture from the camera.

### What does actually happen?
I get an empty string.

## Information
![Screenshot 2019-12-05 at 21 54 44](https://user-images.githubusercontent.com/15617021/70278418-861fbb00-17b4-11ea-8be1-ac3edcc69bbd.png)
![Screenshot 2019-12-05 at 21 57 42](https://user-images.githubusercontent.com/15617021/70278419-8750e800-17b4-11ea-9800-02b7f4da78a5.png)

### Command or Code

    navigator.camera.getPicture(function(a, b, c) { console.log('OK', a, b, c); }, function(a, b, c) { console.log('ERR', a, b, c); }, {destinationType: navigator.camera.DestinationType.DATA_URL, sourceType: navigator.camera.PictureSourceType.CAMERA})

Results in:

    OK - "" - undefined - undefined

### Environment, Platform, Device
iOS 13.1.3
iPhone 11 Pro

### Version information
Cordova: 9.0.0 (cordova-lib@9.0.1)
cordova-plugin-camera: 4.1.0

## Checklist
- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by danielehrhardt** [comment]
Same issue here, please fix!!

**Comment by patrickbussmann** [comment]
Fixed through #525 Related #524.

**Comment by jdnichollsc** [comment]
I'm getting the same issue from Android

**Comment by SnpDeveloper** [comment]
I am getting this error in Android devices..samsung once i have tested? any workarround please?

**Comment by breautek** [comment]
stale
