### ISSUE TITLE
Cordova iOS 13 pick up video empty file content

### ISSUE THREAD

**Issue by zerefsoldier** [apache/cordova-plugin-camera#541]
# Bug Report

Hello everyone,

I'm in trouble since few days now. I know that many responses were written about a similar issue but I think that mine is different.
I'm using Cordova to create an application and I need to upload photos and videos.
The upload is ok and make with the help of Ajax.
Before to upload i create a formData and append all of my files(this part is ok to)
This is good on android and iOS behind 13

#### For iOS 13 it's another deal

When the user pick up photo the file (on JS side) is generated with success. When i try to pick up video there is an error, the file is completely empty and is length is at 0.
I tried to see the file content with JSON stringily and the result for the video is this : {}
I don't know why I can read photo but not video :/

I really need help.

Thanks in advance !

**Comment by NeckbreakerPascal** [comment]
Same here, did you find a solution?

**Comment by zerefsoldier** [comment]
> 
> 
> Same here, did you find a solution?

Not for the moment unfortunately. I try to find a solution

**Comment by NeckbreakerPascal** [comment]
> > Same here, did you find a solution?
> 
> Not for the moment unfortunately. I try to find a solution

Ok thanks for the answer, my bug is a bit different so I opened a new issue here: 
https://github.com/apache/cordova-plugin-camera/issues/546

**Comment by timbru31** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by jcesarmobile** [comment]
closing since there was no response
it's might be fixed by https://github.com/apache/cordova-plugin-camera/pull/580, if not, create a new issue and provide all the data requested by the template
