### ISSUE TITLE
custom camera 

### ISSUE THREAD

**Issue by 15301170766** [apache/cordova-plugin-camera#543]
How to implement
1.1. Similar to the function of mobile phone camera photo 
1.1.1. Can control the slide switch mode 
1.1.2. Take pictures at the bottom of the left side have already photo thumbnails and count 
1.1.3. Can realize more films 
1.1.4. Topped with flash

**Comment by breautek** [comment]
This plugin only provides a way to integrate with the default camera application on the device, so the features are limited depending on the installed camera application on the device. Thus customisation is limited.

If you want a more robust camera API, a third-party plugin is required to access the native camera APIs and to declare that your app uses privacy-sensitive camera permissions.

If you have more questions, feel free to join our [slack](http://slack.cordova.io/). Others may be able to recommend a good third-party plugin that has a more robust camera API.
