### ISSUE TITLE
IONIC Camera UI Language showing GERMAN and I don't know why.

### ISSUE THREAD

**Issue by johnkochjr** [apache/cordova-plugin-camera#552]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [X] Support Question

## Description
I updated to the latest version of the camera plugin for IONIC and Cordova and now when the camera comes up, the language is in GERMAN. 

## Information
My Localization... region is set to United States.
I am using @ionic-native/camera version 5.19.1

### Command or Code
I am simply calling camera.getPicture(options)... 
My options are 
`const options: CameraOptions = {
      quality: 100,
      allowEdit: true,
      cameraDirection: 1,
      targetWidth: 720,
      targetHeight: 720,
      sourceType: sourceType,
      destinationType: this.camera.DestinationType.FILE_URI,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE
    };`

### Environment, Platform, Device
This is in IOS (I haven't tested android yet)
XCode 11

### Version information
Ionic Info
Ionic:

   Ionic CLI          : 5.4.11 (/Users/johnkoch/.nvm/versions/node/v12.12.0/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.0
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.0
   Cordova Plugins   : cordova-plugin-ionic 5.4.5, cordova-plugin-ionic-webview 4.1.3, (and 19 other plugins)

Utility:

   cordova-res : 0.8.1 
   native-run  : 0.3.0 

System:

   Android SDK Tools : 26.1.1 (/Users/johnkoch/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 7.0.0
   NodeJS            : v12.12.0 (/Users/johnkoch/.nvm/versions/node/v12.12.0/bin/node)
   npm               : 6.13.6
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504

## Checklist

- [X] I searched for already existing GitHub issues about this
- [X] I updated all Cordova tooling to their most recent version
- [X] I included all the necessary information above

**Comment by niravparsana94** [comment]
Did you solved the issue?

**Comment by johnkochjr** [comment]
No - unfortunately. Any ideas? There has to be a language setting somewhere

**Comment by johnkochjr** [comment]
Ok - I downgraded from Cordova-ios 5.1.1  back down to cordova-ios@5.0.0 and that resolved the language issue. Not exactly sure what is going on with 5.1.1

**Comment by code-by** [comment]
I need Camera to show German translation, how to achieve this?
