### ISSUE TITLE
cordova camera plugin  ios problem ,  how can i show videos only when camera.getPicture ? 

### ISSUE THREAD

**Issue by jj449** [apache/cordova-plugin-camera#555]
as mentioned,  camera.getPicture   with  mediaType:1 , 

expect behavior : show videos only for user to pick up 

Result: not only show video but also pictures

iOS 13.3 

cordova: 9.0.0
cordova ios : ios 5.1.1
cordova-plugin-camera 4.1.0 "Camera"

how can I show videos only to user  ? Thanks

**Comment by vanderstelTroy** [comment]
const options = {
            destinationType: this.camera.DestinationType.FILE_URI,
            mediaType: MediaType.VIDEO,
            sourceType: PictureSourceType.PHOTOLIBRARY
};

this.camera.getPicture(options).then(async (videoUrl: string) => {
    // Do stuff with 'videoUrl'
}

**Comment by jj449** [comment]
> mediaType: MediaType.VIDEO

thanks for the reply  
but as mentioned ,  I already  set  mediaType: MediaType.VIDEO (1) 
it still can't filter ,  pictures(photos)  appear also .  

below is my  code : 


var options =   {   quality: 50,
                        
			destinationType: Camera.DestinationType.FILE_URI,
                        sourceType:0,      // 0:Photo Library, 1=Camera, 2=Saved Album
						// allowEdit: true, //allow cropping
					      targetWidth: 320, //what widht you want after capaturing
					      targetHeight: 320 ,
					      mediaType:1 //0=picture ,1=video , 2=Allow selection from all media types
                    };
      
      navigator.camera.getPicture(select_film_success, film_select_onFail,options);

**Comment by jj449** [comment]
or  anything I can do to help  figure it out ?

**Comment by 08Thug** [comment]
```
const options: CameraOptions = {
      destinationType: this.camera.DestinationType.FILE_URI,
      sourceType: this.camera.PictureSourceType.PHOTOLIBRARY,
      mediaType: this.camera.MediaType.VIDEO
    };
    this.camera.getPicture(options).then(
      async videoUrl => {
        console.log("videoUrl: ", JSON.stringify(videoUrl));
```
this is what i have done for picking video from gallery and it shows only video

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊.  
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
