### ISSUE TITLE
UIwebview change to WKwebview

### ISSUE THREAD

**Issue by weaponhax** [apache/cordova-plugin-camera#556]
### Issue Type

Apple are refusing UIwebview built apps in favour of WKwebview. Apps using UIwebview will not be allowed on the appstore from April 2020.

This plugn has a refererence to UIwebview that should be changed to WKwebview ASAP. 
## Description

UIwebview reference found in file CDVCamera.h

line 75 @property (strong) UIView* webView;

**Comment by breautek** [comment]
`UIView` is not deprecated, `UIWebView` is deprecated. `UIView` is the base class of both `UIWebView` and `WKWebView`

https://developer.apple.com/documentation/uikit/uiview
https://developer.apple.com/documentation/uikit/uiwebview
https://developer.apple.com/documentation/webkit/wkwebview

**Comment by weaponhax** [comment]
Thank you for your prompt clarification :)
