### ISSUE TITLE
can't select images from camera-roll(android/ios)

### ISSUE THREAD

**Issue by ctfrancia** [apache/cordova-plugin-camera#558]
# Bug Report

## Problem
I can select images that are on my phone, if they came from outside sources (they were sent to me from WhatsApp) or I took a screen shot, downloaded the image, etc. However, when selecting an image that I have taken from my camera nothing happens, there is no error thrown, the promise is never returned, the process of getting the image information is cancelled.

### What is expected to happen?
to be able to select an image from my camera roll

### What does actually happen?
nothing, no error caught or thrown.

### Command or Code

```typescript
         const options: CameraOptions = {
          quality: 80,
          destinationType: this.camera.DestinationType.FILE_URI,
          encodingType: this.camera.EncodingType.JPEG,
          mediaType: this.camera.MediaType.PICTURE,
          correctOrientation: true,
          sourceType: 0, // same result with 2
          allowEdit: true,
        };

  this.camera.getPicture(options).then(res => console.log('res', res)).catch(err => console.log('err', err));;
```
with the example above, after selecting an image from the camera roll, I neither see `res` nor `err`. however If I select an image that was sent to me through WhatsApp, then I see `res`

### Environment, Platform, Device

@ionic/angular 4.11.10
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1

### Version information

```
Ionic:

   Ionic CLI                     : 6.1.0 (/Users/me/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 17 other plugins)

Utility:

   cordova-res                         : 0.9.0
   native-run                            : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/me/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v13.7.0 (/usr/local/Cellar/node/13.7.0/bin/node)
   npm               : 6.13.6
   OS                : macOS Mojave
   Xcode             : Xcode 11.3 Build version 11C29
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by PieterVanPoyer** [comment]
@ctfrancia  is this issue still present with the lates plugin and cordova version?
