### ISSUE TITLE
After I added the camera plug-in, the app will crash when the imagepicker plug-in calls the getpicture event.

### ISSUE THREAD

**Issue by Aton5859** [apache/cordova-plugin-camera#559]
### Issue Type

- [ ] Bug Report

## Description
After I added the camera plug-in, the app will crash when the imagepicker plug-in calls the getpicture event.

## Information
 <plugin name="cordova-plugin-telerik-imagepicker" spec="^2.3.3" />
    <plugin name="cordova-plugin-camera" spec="^4.1.0">
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.+" />
    </plugin>
"cordova-plugin-camera": "^4.1.0",
"cordova-plugin-telerik-imagepicker": "^2.3.3",
 "@ionic-native/camera": "^5.21.5",
"@ionic-native/image-picker": "^5.20.0",

### Version information
ionic 4.12.0
android: 7.0.0

**Comment by timbru31** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

---

Thanks a lot for your issue, however the issue template exists for a reason. 😊.  
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by clarklight** [comment]
@Aton5859 I had the same issue earlier, and i used the version before your comment date then its opening the image picker ok, i am using the telerik image picker(latest version). And the camera i use cordova to add specific version which is camera 4.0.3, which is working correctly on my android OS 10. 

So the situation is whatever was introduced in 4.1.0 causes the conflict.

@timbru31 I did build a brand new empty app with just the camera plugin and the telerik image picker, and soon as the image picker event is triggered then the app crash, if i remove the camera app then the image picker wont crash the app, i also saw the same thing with cordova-plugin-qrscanner. If i had the qrscanner plugin(which also uses the camera),it will also crash the image-picker. 

I will also post this issue on the telerik image picker thread to see if they can help on that side. 
Thanks
Clark
