### ISSUE TITLE
Disallow taking of video

### ISSUE THREAD

**Issue by vtebano13** [apache/cordova-plugin-camera#560]
When the camera pop up to take a picture in IOS the option to switch to video is there.

Is there a way to remove the video option?

### What is expected to happen?
I would like to not allow the user to switch to video when using the camera

### What does actually happen?
Both camera and video options are present when specifying camera

![image](https://user-images.githubusercontent.com/7851946/74550238-0a15c200-4f1f-11ea-8666-72b56fc99ef3.png)

## Information

How the camera is being called:

  navigator.camera.getPicture(
     function (imageData) {
         dialog.close();
         thisController[actionPress](null, imageData);
    },
     function () {
              dialog.close();
    },
     {
               quality: 75,
               destinationType: Camera.DestinationType.FILE_URI,
               sourceType: navigator.camera.PictureSourceType.CAMERA,
               encodingType: Camera.EncodingType.JPEG,
               mediaType: Camera.MediaType.PICTURE,
               allowEdit: false,
               correctOrientation: true
      });

### Environment, Platform, Device
IOS 13.3

### Version information
cordova-plugin-appconfig 1.1.3 "AppConfig"
cordova-plugin-barcodescanner 0.7.4 "BarcodeScanner"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-email 1.2.7 "EmailComposer"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-opener2 2.2.1 "File Opener2"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-sqlcipher-adapter 0.1.8 "Cordova sqlcipher adapter"

## Checklist

- [X ] I searched for existing GitHub issues
- [ X] I updated all Cordova tooling to most recent version
- [X ] I included all the necessary information above

**Comment by vtebano13** [comment]
Have been able to duplicate this?   Will it be fixed?

**Comment by jcesarmobile** [comment]
I don't see the video option in iOS 12 nor iOS 14. 
You are using a very old version of the plugin, latest is 4.1.0.
Try updating.
