### ISSUE TITLE
 Camera Direction default back on android unable to change front  ==> CameraOptions Errata in doc

### ISSUE THREAD

**Issue by sandy1198** [apache/cordova-plugin-camera#562]
### Issue Type

- [ ] Bug Report
- [x] Feature Request
- [ ] Support Question

## Checklist

- [ ] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

**Comment by jcesarmobile** [comment]
I'm closing since the issue doesn't include any information and the title is confusing
