### ISSUE TITLE
Camera Cordova plugin issue on android

### ISSUE THREAD

**Issue by moustafawhb** [apache/cordova-plugin-camera#563]
My application uses ionic 1 and [cordova-camera-plugin](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-camera). It is working fine on ios. However on android the first time it asks for camera permission and then app crashes, then when I try again I get the following error: file:///storage/emulated/0/Android/data/com.company.test/cache/.Pic.jpg exposed beyond app through ClipData.Item.getUri()

I appriciate any help.. Please find my code below:

document.addEventListener("deviceready", onDeviceReady, false);
function onDeviceReady() {
    var cameraOptions = {
            quality: 100,
            targetWidth: 400,
            targetHeight: 400,
            destinationType: Camera.DestinationType.DATA_URL,
            correctOrientation: true
    };
       navigator.camera.getPicture(cameraSuccess, cameraError, cameraOptions);

}

 function cameraSuccess(imageURI){
     $scope.$apply(function () {
        //some code
     });
 }

 //here is where i am getting the error 
 function cameraError(message)
 {
    console.log(message);
   //alert('Failed because: ' + message);
 }

**Comment by bparkhurst** [comment]
We are getting this exact same error.  Does anyone have any insight on how to fix it?  We have found the camera plugin no longer works in any version of Android we use.  This is the exact error we are getting.  

PluginManager: Uncaught exception from plugin
    android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.epicor.POD/cache/.Pic.jpg exposed beyond app through ClipData.Item.getUri()

We do not know how to solve this issue and our release is held up right now because of this.

**Comment by timbru31** [comment]
Please make sure to follow the issue template, this highly increases your chances of getting your issue resolved.

**Comment by Inatan** [comment]
I have the same problem.
When we try to open camera in android, app crashes at the first time when app ask permission, when a do another try my catch returns this error: **length=1; index=1**

**Comment by PieterVanPoyer** [comment]
@moustafawhb  is issue still present with the lates Cordova and Cordova plugin versions?
