### ISSUE TITLE
Compression ratio not as high on iOS as compared to Android

### ISSUE THREAD

**Issue by staticbuzz** [apache/cordova-plugin-camera#565]
# Bug Report

## Problem
On iOS devices, photos are not being compressed as much as on Android devices with the same plugin settings, resulting in much larger file-sizes. We need photos to be similarly compressed on both platforms with similar resulting file-sizes.

### What is expected to happen?
Similar levels of compression and resulting image file-size irrespective of whether Android or iOS devices are used.

### What does actually happen?
With the same settings, photos taken with this camera plugin end up at around 500kb on iOS but only 60kb on Android.

### Version information
   Ionic CLI                            : 5.4.1 (C:\Users\Ionic\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.10.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1
   @ionic-native/camera         : 5.15.0

Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins  :  cordova-plugin-camera 4.1.0 

Utility:
   cordova-res : 0.6.0
   native-run  : 0.2.8

System:
   Android SDK Tools : 26.1.1 (C:\AndroidSdk)
   NodeJS            : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10

**Comment by breautek** [comment]
Different phones takes pictures at different resolutions, often controlled by the camera app itself. When you are comparing file sizes, I trust that you are also comparing against images of the same resolution?

**Comment by staticbuzz** [comment]
Thanks for that - it appears iOS camera always takes photos at max resolution and this cant be changed. When I set android devices to the same resolution, compressed file-size is about the same. Sorry to waste your time and thanks for a fantastic framework!
