### ISSUE TITLE
Opening camera causes status bar to disappear

### ISSUE THREAD

**Issue by jacobweber** [apache/cordova-plugin-camera#566]
# Bug Report

### What is expected to happen?
On an app that uses a visible status-bar, open and close the camera. Status bar should reappear.

### What does actually happen?
Status bar disappears after camera closed.

## Information

- run app from zip (or re-create using instructions below)
- notice white status bar area
- click content to open camera
- click Cancel to close camera
- notice status bar area has disappeared

[CordovaTest.zip](https://github.com/apache/cordova-plugin-camera/files/4288935/CordovaTest.zip)

### Command or Code

```
# create project
$ cordova create CordovaTest com.sample.cordovatest CordovaTest
$ cd CordovaTest
$ cordova platform add ios@5.1.1

# add status bar
$ cordova plugin add cordova-plugin-statusbar@2.4.3
# add to config.xml:
    <platform name="ios">
        <preference name="StatusBarOverlaysWebView" value="false" />
    </platform>

# create splash screen
$ mkdir -p res/screen/ios
$ /usr/local/bin/convert -size "2732x2732" "xc:#AA0000" "res/screen/ios/Default@2x~universal~anyany.png"
# add to config.xml:
    <splash src="res/screen/ios/Default@2x~universal~anyany.png" />

# add camera plugin
$ cordova plugin add cordova-plugin-camera@4.1.0
# add to config.xml:
	<config-file platform="ios" target="*-Info.plist" parent="NSCameraUsageDescription">
		<string>test</string>
	</config-file>
	<config-file platform="ios" target="*-Info.plist" parent="NSPhotoLibraryUsageDescription">
		<string>test</string>
	</config-file>

# add wkwebview
$ cordova plugin add https://github.com/mwchambers/cordova-plugin-wkwebview-engine#master
# add to config.xml:
	<preference name="WKWebViewOnly" value="true" />
# in www/index.html, wrap div around body, to deal with https://github.com/apache/cordova-plugin-wkwebview-engine/issues/108:
<div id="content" style="width: 100vw; height: 100vh;">
    <div class="app"> ...
</div>

# add to www/js/index.js in onDeviceReady:
    document.getElementById('content').addEventListener('click', function() {
      if (window.navigator.camera) {
        window.navigator.camera.getPicture(
          imageURI => {},
          message => {},
          {
            sourceType: window.Camera.PictureSourceType.CAMERA,
            destinationType: window.Camera.DestinationType.FILE_URI,
            allowEdit: false
          }
        );
      }
    });

# add build.json with your development team
$ cordova run ios --buildConfig build.json
```

### Environment, Platform, Device

Running on iOS 13.3.1, iPhone XR

### Version information

cordova: 9.0.0 (cordova-lib@9.0.1)
Xcode 11.3.1
Building on Mac OS 10.14.6.

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by Scipionh** [comment]
Any news on this ?

**Comment by lonwi** [comment]
@Scipionh 

This is an issue with the status bar plugin itself
You can get the fixed version from the repository directly, use 
"cordova-plugin-statusbar": "git+https://github.com/apache/cordova-plugin-statusbar.git",
instead of 
"cordova-plugin-statusbar": "2.4.3",

I hope they will release a properly fixed version soon

**Comment by erisu** [comment]
[v3.0.0](https://www.npmjs.com/package/cordova-plugin-statusbar/v/3.0.0) has been released.

**Comment by jjtfsalgado** [comment]
Guys we are experiencing the same issue as described in iOS 13 and 14 (it works fine in 15) and we don't use the cordova-plugin-statusbar. Do we need the cordova-plugin-statusbar to overcome this?

![image](https://user-images.githubusercontent.com/14180997/155576389-2eb65b9b-b581-4fb8-918a-79b31eb8d01d.png)
