### ISSUE TITLE
app crashing while opening camera ios 13.3.1 ionic 2

### ISSUE THREAD

**Issue by keshavkhatri** [apache/cordova-plugin-camera#567]
app is crashing while opening camera in ios 13

below is output from ionic info

Ionic:

   ionic (Ionic CLI)  : 4.2.1
   Ionic Framework    : ionic-angular 2.2.0
   @ionic/app-scripts : 1.3.12

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : ios 5.0.1
   Cordova Plugins       : no whitelisted plugins (31 plugins total)

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/Users/himanisharma/.nvm/versions/node/v10.16.3/bin/node)
   npm        : 2.15.12
   OS         : macOS
   Xcode      : Xcode 10.2 Build version 10E125

**Comment by breautek** [comment]
Is this reproducible without ionic?

**Comment by ontwikkelfabriek** [comment]
Same here not using ionic but quasar with ios 13. App crashed when opening camera. No issues when opening the gallery. No issue with an Iphone 4s with ios 9

**Comment by jcesarmobile** [comment]
closing as there is no information about the error or how to reproduce

make sure you added the UsageDescription texts in config.xml

https://github.com/apache/cordova-plugin-camera#ios-quirks
