### ISSUE TITLE
Unable to select video file to upload in Cordova

### ISSUE THREAD

**Issue by monjitd** [apache/cordova-plugin-camera#569]
I have a Django application that uses javascript to upload images and videos to AWS S3. Converted it to an ios app using Cordova 9.0. Added cordova-plugin-camera to the package. Using my iphone's camera I am able to take photos or videos and they get uploaded successfully. I am also able to upload a photo from the iPhone's library. But I am unable to upload any videos from the library.  Any reason why the videos from the library do not get uploaded ?

### Environment, Platform, Device
iOS, Cordova

### Version information
Cordova: 9.0
Xcode

## Checklist

- [ X] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [X ] I included all the necessary information above

**Comment by monjitd** [comment]
Issue got resolved after adding the cordova-plugin-wkwebview-engine plugin.

**Comment by D-Marc1** [comment]
I'm facing the exact same issue, but I actually already had the `wkwebview` plugin installed. Everything works, except for getting videos from my library. Any tips for me @monjitd? Are you maybe using an older version of the plugin? Because I currently have the latest.

**Comment by monjitd** [comment]
Hi,

Here's what I had to add to my config.xml:

    *<feature *name*=*"Device"*>*

        *<param *name*=*"ios-package" value*=*"CDVDevice"* />*

    *</feature>*

    *<feature *name*=*"CDVWKWebViewEngine"*>*

        *<param *name*=*"ios-package" value*=*"CDVWKWebViewEngine"* />*

    *</feature>*

    *<preference *name*=*"CordovaWebViewEngine" value*=*"CDVWKWebViewEngine"*
/>*

    *<feature *name*=*"WKWebViewWindowOpen"*>*

        *<param *name*=*"ios-package" value*=*"WKWebViewWindowOpen"* />*

    *</feature>*


Add plugin ‘@zestia/cordova-plugin-wkwebview-engine-windowopen’.  This will
install the ‘ cordova-plugin-wkwebview-engine’ plugin, and also add
zestia-cordova-plugin-wkwebview-engine-windowopen to package.json

Simply adding plugin ‘ cordova-plugin-wkwebview-engine’ was not enough,
because once this plugin was added  (  so that video files, similar to
photos,  can be selected to be uploaded from the iphone’s image library ),
it broke the ability to open all the external links. So, the plugin
‘@zestia/cordova-plugin-wkwebview-engine-windowopen’ had to be installed.

Website:
https://developer.aliyun.com/mirror/npm/package/@zestia/cordova-plugin-wkwebview-engine-windowopen/v/1.0.1?spm=a2c6h.14275010.0.0.74f2643eCJWdAV&file=1.0.1



Cheers
Monjit.

**Comment by D-Marc1** [comment]
Thank you for the reply! I deleted my comment here, so it might be confusing. I realized quickly the problem was that you have clone the Github repo here, as they recently fixed the issue, and isn't on NPM. Thanks again for taking the time to provide your code!
