### ISSUE TITLE
how to delay the request for camera permission [Android]

### ISSUE THREAD

**Issue by matrixreal** [apache/cordova-plugin-camera#572]
Hello,
how to delay the request for camera permission on android?
i use this plugin and it ask for permission on start of the app
thanks

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
