### ISSUE TITLE
Android 10 select video return path error

### ISSUE THREAD

**Issue by ztj1993** [apache/cordova-plugin-camera#573]
# Bug Report
Android 10 select video return path error.
I tested OK on Android 8.

## Problem
android 10

### What is expected to happen?
```
I/chromium: [INFO:CONSOLE(67)] "/storage/emulated/0/DCIM/Camera/VID_20200322_153048.mp4",
```

### What does actually happen?
```
D/CameraLauncher: File location is: null
W/ContentResolver: Failed to get type for: content://com.google.android.apps.photos.contentprovider/-1/2/content%3A%2F%2Fmedia%2Fexternal%2Fvideo%2Fmedia%2F28/ORIGINAL/NONE/1039573866 (Invalid column latitude)
```

### Command or Code

```
        navigator.camera.getPicture(function (videoURI) {
            console.log(videoURI);
            alert(videoURI);
        }, function (message) {
            console.log('Failed because: ' + message);
        }, {
            mediaType: Camera.MediaType.VIDEO,
            destinationType: Camera.DestinationType.NATIVE_URI,
            sourceType: Camera.PictureSourceType.PHOTOLIBRARY,
        });
```
or
```
Camera.DestinationType.FILE_URI
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by tmk1991** [comment]
Similar issue using the following in android 10:

```
    const options: CameraOptions = {
      quality: 40,
      targetHeight: 1000,
      targetWidth: 1000,
      correctOrientation: true,
      allowEdit: true,
      destinationType: this.camera.DestinationType.FILE_URI,
      sourceType: this.camera.PictureSourceType.PHOTOLIBRARY,
      mediaType: this.camera.MediaType.ALLMEDIA
    };
```

Returns undefined with `FILE_URI`. Changing to DATA_URL works. Would prefer to use FILE_URI.

**Comment by tmk1991** [comment]
@ztj1993  - did you resolve?

**Comment by ztj1993** [comment]
@tmk1991 No

**Comment by tmk1991** [comment]
I've made changes to my fork for existing iOS and Android OS updates. 
https://github.com/TDTECHLINK/cordova-plugin-camera

Remove the plugin and then add back via git repo
`cordova plugin add git+https://github.com/TDTECHLINK/cordova-plugin-camera.git`

**Comment by HardikDG** [comment]
@tmk1991 Do you have any working example or sample code snippet. I am also facing the same issue
