### ISSUE TITLE
build android failed when camera plugin is added

### ISSUE THREAD

**Issue by rashnk** [apache/cordova-plugin-camera#574]
# Bug Report

## Problem
cordova build android failed 
Error :
`D8: Program type already present: android.support.v4.app.INotificationSideChannel

FAILURE: Build failed with an exception.

* What went wrong:
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.app.INotificationSideChannel

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s34 actionable tasks: 9 executed, 25 up-to-date
`

### What is expected to happen?
cordova build android should generate apk without fail

### What does actually happen?
Build failed with error

## Information
I have google the issue and found the project need to be migrated to androidx, there are are some 3rd party plugins exist for this like cordova-plugin-androidx-adapter which fixes the issue

### Command or Code
cordova build android

### Version information

$ cordova -v
`9.0.0 (cordova-lib@9.0.1)`

`  "dependencies": {
    "cordova-android": "^8.1.0",
    "cordova-browser": "^6.0.0",
    "cordova-plugin-camera": "^4.1.0"
  },`

gradle-6.2.1

Windows 8.1
Android Studio 3.6.1 for Windows

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
Could you narrow it down to the conflicting plugin? Otherwise we can't help you.

**Comment by rashnk** [comment]
> ~Could you narrow it down to the conflicting plugin? Otherwise we can't help you.~
> 
> Are you using AndroidX?

Thank you for quick reply.
No, I have not added androidx library, 
I have android studio  3.6.1 installed 
SDK installed Android 9.0 only

**Comment by rashnk** [comment]
I have cordova-admob-plus also installed in the project
and when I remove one of the plugin from the project it works, build is successful
cordova-plugin-camera
cordova-admob-plus
if I add both build is failing

**Comment by timbru31** [comment]
Play services >=17 require AndroidX support, you’ll need to install the two Androidx plugins (adapter and normal) until #418 is merged.

**Comment by rashnk** [comment]
Thank you @timbru31

**Comment by ChrisTomAlx** [comment]
@timbru31 I am assuming these are the plugins :- 
 
- [normal ](https://www.npmjs.com/package/cordova-plugin-androidx)
- [adapter ](https://www.npmjs.com/package/cordova-plugin-androidx-adapter)
