### ISSUE TITLE
SaveToPhotoAlbum does not save image on Android

### ISSUE THREAD

**Issue by HarelM** [apache/cordova-plugin-camera#577]
# Bug Report
When setting `saveToPhotoAlbum` to be `true` image is not saved

### What is expected to happen?
Image should be saved to photo album

### What does actually happen?
Image is not saved

## Information

Pretty straight forward - clicking on a button to open the camera, taking a picture, the picture is used in the app but does not appear in the gallery
Related to #341

### Command or Code

https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/sources/application/directives/image-capture.directive.ts#L50L55

### Environment, Platform, Device
Android, both samsung 9 and xiomi redmi 4, 
App can be found here:
https://play.google.com/store/apps/details?id=il.org.osm.israelhiking&hl=en
Clicking the up-side-down drop on the right
Clicking a location on the map
Clicking on the camera to take a picture
Clicking OK in the camera app
The image is presented in the app but it is not stored in the gallery.

### Version information

Cordova 9.0
Cordova-plugin-camera 4.0.3

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by tmk1991** [comment]
I've made changes to my fork for existing iOS and Android OS updates. 
https://github.com/TDTECHLINK/cordova-plugin-camera

Remove the plugin and then add back via git repo
`cordova plugin add git+https://github.com/TDTECHLINK/cordova-plugin-camera.git`

**Comment by HarelM** [comment]
Thanks @tmk1991! I don't see changes related to this specific issue, is it because of the API changes you did?
Any chance you can send a PR and this will hopefully be merged to solve this issue (Although there seems to be too many open pull requests... :-( )?

**Comment by 949mac** [comment]
> Thanks @tmk1991! I don't see changes related to this specific issue, is it because of the API changes you did?
> Any chance you can send a PR and this will hopefully be merged to solve this issue (Although there seems to be too many open pull requests... :-( )?

Did this solution work for you, HarelM? Thanks for updating!

**Comment by HarelM** [comment]
@949mac haven't had the chance to try it yet. Since forks can be easily abandoned I usually prefer to wait for a formal fix and release. I'm experiencing this issue for a while now and it is not a top priority bug so I want to see how this plays out.
Nevertheless, if you get around to test it let me know :-)
