### ISSUE TITLE
 Turn off Photo Preview

### ISSUE THREAD

**Issue by dex252** [apache/cordova-plugin-camera#578]
Hello! I use google translation.
First of all, thanks for the plugin, it helped me a lot in my tasks.
However, I am extremely lacking in the ability to take photos without a preview. 
![qhgkNNdFx2g](https://user-images.githubusercontent.com/38129962/78454369-0f9bb700-76db-11ea-8703-e94f8ffafe36.jpg)
After each shot, I have to click on the confirmation. The confirmation line can be seen at the top of the screenshot.
I would like the photos to always be written to the phone’s memory without confirmations, is this possible? If so, how do I achieve this?

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊.  
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
