### ISSUE TITLE
ios13.4, no further action occurred when the user tapped the 拍照上传 and 从相册选择 option

### ISSUE THREAD

**Issue by yj666** [apache/cordova-plugin-camera#579]
# Bug Report
ios13.4 no further action occurred when the user tapped the 拍照上传 and 从相册选择 option
## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
