### ISSUE TITLE
Missing Geolocation in backup files (saveToPhotoAlbum) on iOS

### ISSUE THREAD

**Issue by rimosystems** [apache/cordova-plugin-camera#582]
The plugin does not store the geolocation in the exif data when `saveToPhotoAlbum` is true. But only the file in the photo album does not have the exif geolocation information. The one we are sending to the server, which is temporary stored in the dataDirectory on iOS, comes with the exif metadata. It looks like the plugin copies the file to the photoAlbum without the exif data.

All necessary flags are enabled (`NSLocationWhenInUseUsageDescription`, `CameraUsesGeolocation`)

**Version**
9.0.0 (cordova-lib@9.0.1)
latest version of the plugin

**Comment by bloigge** [comment]
Looks like there is already an issue for this: https://github.com/apache/cordova-plugin-camera/issues/524

**Comment by rimosystems** [comment]
Looks like there is already an issue for this: https://github.com/apache/cordova-plugin-camera/issues/524
