### ISSUE TITLE
destinationType:0 But the return path

### ISSUE THREAD

**Issue by zhaolei11** [apache/cordova-plugin-camera#583]
# Bug Report

phone: HUAWEI
system: emui 8.0.0

opyions = {
correctOrientation: true
destinationType: 1
encodingType: 0
mediaType: 0
quality: 90
saveToPhotoAlbum: true
sourceType: 0
}

this.camera.getPicture(options).then((imageData) => {
}
i. want  imageData is base64 but get  /storage/emulated/0/tencent/MicroMsg/WeiXin/100.jpg

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
