### ISSUE TITLE
destinationType:0 But the return path

### ISSUE THREAD

**Issue by zhaolei11** [apache/cordova-plugin-camera#584]
# Bug Report
destinationType:0 But the return path
## Problem
destinationType:0 But the return path
### What is expected to happen?
destinationType:0; i Hope to get  base64

### What does actually happen?

get url : /storage/emulated/0/tencent/MicroMsg/WeiXin/100.jpg

## Information

phone: HUAWEI 
system: emui 8.0.0

### Command or Code

this.camera.getPicture(options).then(resData => {})

### Environment, Platform, Device

phone: HUAWEI  NEXT-AL10
system: emui 8.0.0

### Version information

cordova 9.0.0 (cordova-lib@9.0.1)
ionic 3

## Checklist

- [ x ] I searched for existing GitHub issues
- [ x ] I updated all Cordova tooling to most recent version
- [ x ] I included all the necessary information above

**Comment by timbru31** [comment]
`this.camera.getPicture(options).then(resData => {})`

This looks a lot like Ionic's Native wrapper, please verify the same issue occurs in a new, plain Cordova app **without** Ionic. A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md
