### ISSUE TITLE
Getting error taking a photo 

### ISSUE THREAD

**Issue by jasonsultana** [apache/cordova-plugin-camera#587]
04-23 11:20:51.740  2495  2495 W System.err: java.io.IOException: ExifInterface only supports saving attributes on JPEG formats.
04-23 11:20:51.740  2495  2495 W System.err:    at android.media.ExifInterface.saveAttributes(ExifInterface.java:1770)
04-23 11:20:51.740  2495  2495 W System.err:    at org.apache.cordova.camera.ExifHelper.writeExifData(ExifHelper.java:163)
04-23 11:20:51.740  2495  2495 W System.err:    at org.apache.cordova.camera.CameraLauncher.processResultFromCamera(CameraLauncher.java:586)
04-23 11:20:51.740  2495  2495 W System.err:    at org.apache.cordova.camera.CameraLauncher.onActivityResult(CameraLauncher.java:808)
04-23 11:20:51.740  2495  2495 W System.err:    at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:159)
04-23 11:20:51.740  2495  2495 W System.err:    at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:359)
04-23 11:20:51.740  2495  2495 W System.err:    at android.app.Activity.dispatchActivityResult(Activity.java:7235)
04-23 11:20:51.740  2495  2495 W System.err:    at android.app.ActivityThread.deliverResults(ActivityThread.java:4320)
04-23 11:20:51.740  2495  2495 W System.err:    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4367)
04-23 11:20:51.740  2495  2495 W System.err:    at android.app.ActivityThread.-wrap19(Unknown Source:0)
04-23 11:20:51.740  2495  2495 W System.err:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
04-23 11:20:51.740  2495  2495 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:105)
04-23 11:20:51.740  2495  2495 W System.err:    at android.os.Looper.loop(Looper.java:164)
04-23 11:20:51.740  2495  2495 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6541)
04-23 11:20:51.741  2495  2495 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
04-23 11:20:51.741  2495  2495 W System.err:    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
04-23 11:20:51.741  2495  2495 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

`navigator.camera.getPicture( cameraSuccess, cameraError, {
                quality: 50,
                destinationType: Camera.DestinationType.FILE_URI,
                correctOrientation: true,
                saveToPhotoAlbum: true
  });`

Any advice is much appreciated. Thanks!

**Comment by jasonsultana** [comment]
Tried reproducing this in a brand new hello-world phonegap project and it still happens. I'm runnin on OSX 10.15.4 using Phonegap 8.2.2.

**Comment by jasonsultana** [comment]
Also tried using the example code from https://github.com/apache/cordova-plugin-camera#camera-getPicture-examples verbatim. Still fails :(

**Comment by jasonsultana** [comment]
I was able to get it working using the following options:

`            
navigator.camera.getPicture( cameraSuccess, cameraError, {
                quality: 100,
                destinationType: Camera.DestinationType.FILE_URI,
                correctOrientation: false,
                saveToPhotoAlbum: false
            });
`

I think there is definitely something funny going on though.

**Comment by breautek** [comment]
Thanks a lot for your issue, however the issue template exists for a reason.
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by jasonsultana** [comment]
# Bug Report
## Problem
### What is expected to happen?
No Android exceptions being thrown regardless of property values of CameraOptions passed to `navigator.camera.getPicture(...)`

### What does actually happen?
"System.err: java.io.IOException: ExifInterface only supports saving attributes on JPEG formats." is thrown.

## Information
See full stack trace in first comment. I noticed that setting the quality to 100 and `correctOrientation` and `saveToPhotoAlbum` to false fixed the problem.

### Command or Code
Passing case:
```
navigator.camera.getPicture( cameraSuccess, cameraError, { quality: 100, destinationType: Camera.DestinationType.FILE_URI, correctOrientation: false, saveToPhotoAlbum: false });
```

Failing case:
```
navigator.camera.getPicture( cameraSuccess, cameraError, { quality: 50, destinationType: Camera.DestinationType.FILE_URI, correctOrientation: false, saveToPhotoAlbum: false });
```

Changing the other bools to true (even with a 100 quality) also fails.

### Environment, Platform, Device
Android, Genymotion Emulator, Samsung Galaxy S9

### Version information
Phonegap 8.2.2
OSX 10.15.4
    <plugin name="cordova-plugin-camera" spec="4.1.0">
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.+" />
    </plugin>

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
The fail case code provided does not reproduce the issue for me. Are you able to provide a [sample reproduction app](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md)?

**Comment by PieterVanPoyer** [comment]
Closing ticket due to lack of response, due to missing information and invalid bug report. Issue is probably solved with most recent Cordova tooling.
