### ISSUE TITLE
getPicture() fails with Ionic 

### ISSUE THREAD

**Issue by vratislavino** [apache/cordova-plugin-camera#590]
# Bug Report

### What is expected to happen?
I expected camera plugin to return BASE64 data so I can send it and save it on server.

### What does actually happen?
On device, this.camera.getPicture(options) fails with error message:

> Cannot read property 'present' of undefined

Same thing happens if I use CAMERA or PHOTOLIBRARY as sourceType

### Command or Code

imported 
`import { Camera } from '@ionic-native/camera/ngx';`

injected in constructor
`constructor(public camera: Camera) { }`

and then used in my upload() method
```
let options = {
      quality: 100,
      destinationType: this.camera.DestinationType.DATA_URL,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE,
      sourceType: this.camera.PictureSourceType.CAMERA,
      saveToPhotoAlbum: false,
      correctOrientation: false
};
this.camera.getPicture(options).then((imageData) => {
let base64Image = 'data:image/jpeg;base64,' + imageData;
      this.sendToServer(base64Image);
    }).catch(err => {
      console.log(err.message);
    });
```

### Environment, Platform, Device
Not depending on device, happened on multiple devices wit different versions, eg.
Xiaomi Mi 8 - Android 10
Samsung Galaxy A3 - Android 6

### Version information
Ionic 5.4.16
Cordova: 9.0.0 (cordova-lib@9.0.1)
cordova-plugin-camera 4.1.0 "Camera"

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by s3ppo** [comment]
i have the same issue on ionic 5.
i got an error back:
length=1; index=1

**Comment by vratislavino** [comment]
> i have the same issue on ionic 5.
> i got an error back:
> length=1; index=1

So if I get your answer correctly, you didn't find a solution, right?

**Comment by timbru31** [comment]
Please verify this is not an issue with Ionic Native and the same issue happens when using the actual plugin's API, **not** the wrapper. A minimal reproduction repository (without Ionic) would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by s3ppo** [comment]
sorry but i dont understand why you close this issue.. if you dont want to
support the ionic wrapper okay.. but maybe other users have the same
behavior and can help each other here :(

Tim Brust <notifications@github.com> schrieb am Do., 7. Mai 2020, 00:51:
