### ISSUE TITLE
The application stopped when taking a photo with the camera on the Moto G7 devices

### ISSUE THREAD

**Issue by dunkel015** [apache/cordova-plugin-camera#593]
When I try to take a photo with the moto g7 cell phone, the application closes, with the other cell phones it works correctly, I have already updated the android version and the repository version to 4.1.0 but it still does the same.

**Comment by jcesarmobile** [comment]
Please, when reporting issues provide all the information requested by the template instead of deleting it.
We can't reproduce with the provided information.
