### ISSUE TITLE
Remove Confirmation button for the ionic-camera plugin

### ISSUE THREAD

**Issue by ketanakbari** [apache/cordova-plugin-camera#595]
`Cancel` and `Ok` in android and `Retake` and `Used` confirmations buttons shown after photo taken from camera. i need to bypass those confirmation buttons after phone taken.

is it possible to remove confirmation buttons after taken photo?

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

---

Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
