### ISSUE TITLE
Error with .bmp images only on android

### ISSUE THREAD

**Issue by carlosGonzalezUri** [apache/cordova-plugin-camera#596]
### Issue Type

- [x] Bug Report

## Description
Can't add .bmp images with the plugin on android devices, same image on ios devices works ok.
### Command or Code

Just add some .bmp image

### Environment, Platform, Device

Fails on android v9 and v8

### Version information

im using
cordova-plugin-camera v4.1.0
cordova v9
Ionic CLI         : 6.4.1 
Ionic Framework   : ionic1 1.3.0
@ionic/v1-toolkit : 3.1.1

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by arturoberanlg** [comment]
+1

**Comment by timbru31** [comment]
+1 comments do not help in any way and just generate unnecessary noise for a lot of people - pls use the reactions of GitHub instead.

---

@carlosGonzalezUri can you share some example files that could be tested by us?

**Comment by PieterVanPoyer** [comment]
[sample_640×426.zip](https://github.com/apache/cordova-plugin-camera/files/6511337/sample_640x426.zip)

I did add a bmp inside the zip. 

@carlosGonzalezUri When I select the .bmp with the plugin on android the app or plugin does not crash. It is returned to the html part of the app. Can you elaborate a bit on the wrong behaviour? It's not clear for me.

**Comment by PieterVanPoyer** [comment]
@carlosGonzalezUri closing this. Bmp's are returned to the webview part by the latest version. There is also no collaboration on this issue.
