### ISSUE TITLE
Android: Camera fails with an exception

### ISSUE THREAD

**Issue by ryaa** [apache/cordova-plugin-camera#597]
# Bug Report

### What is expected to happen?
Camera should take photos as expected.

### What does actually happen?
An exception is thrown
```
java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/<PACKAGE_NAME>/cache/.Pic.jpg
```

## Information

The problem might be related to this commit https://github.com/apache/cordova-plugin-camera/commit/df1441420376696994d77f0856ab3dfbed5f0bbe

The plugin uses this configuration for FileProvider from **android/xml/camera_provider_paths.xml** with external-path however it might need to use cache-path instead.

I will try to provide a PR

### Command or Code

Install the latest version 4.2.0 which includes the above commit/change

### Environment, Platform, Device

Android 10

### Version information

N/A

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by ryaa** [comment]
The potential changes to fix the above and EXIF related problem in my PR https://github.com/apache/cordova-plugin-camera/issues/524

**Comment by matiaspando** [comment]
Hey guys!  I have the same problem , is there any  workaround to avoid this issue ?

**Comment by timbru31** [comment]
Use 4.1.0 and not an unreleased, unstable version.

**Comment by ryaa** [comment]
> Hey guys! I have the same problem , is there any workaround to avoid this issue ?

Until the fix is merged/provided, you can install from my fork https://github.com/ryaa/cordova-plugin-camera where this and some other problems have been fixed.

**Comment by CodeWithOz** [comment]
@ryaa thanks for your fork, it fixes the issue on my end. However, have you noticed an increase in the size of your app bundle as a result of using your fork? My bundle went from 16.8MB to 23MB after switching to your fork. Any idea why that is?

**Comment by CodeWithOz** [comment]
I'm also seeing a bug where my app gets shifted by ~50px at the bottom. The black area did not exist previously.
![blank-space](https://user-images.githubusercontent.com/28525986/86926214-b6a04c80-c129-11ea-92a4-9d627c1f9880.png)

I noticed that I use CSS to reposition it correctly, but this wasn't happening before I installed your fork. Any ideas?
