### ISSUE TITLE
Type 'CameraOriginal' is not assignable to type 'Provider'.

### ISSUE THREAD

**Issue by jefflee789** [apache/cordova-plugin-camera#598]
# Bug Report
I am using latest version cordova camera plugin 5.25.0. 

"dependencies": {
    "@angular/common": "~9.1.6",
    "@angular/core": "~9.1.6",
    "@angular/forms": "~9.1.6",
    "@angular/http": "^7.2.16",
    "@angular/platform-browser": "~9.1.6",
    "@angular/platform-browser-dynamic": "~9.1.6",
    "@angular/router": "~9.1.6",
    "@capacitor/core": "2.1.0",
    "@ionic-native/camera": "^5.25.0",
    "@ionic-native/core": "^5.0.7",
    "@ionic-native/crop": "^5.25.0",
    "@ionic-native/device-motion": "^5.25.0",
    "@ionic-native/file-transfer": "^5.25.0",
    "@ionic-native/google-analytics": "^5.25.0",
    "@ionic-native/google-plus": "^5.25.0",
    "@ionic-native/http": "^5.25.0",
    "@ionic-native/in-app-browser": "^5.25.0",
    "@ionic-native/onesignal": "^5.25.0",
    "@ionic-native/screen-orientation": "^5.25.0",
    "@ionic-native/screenshot": "^5.25.0",
    "@ionic-native/social-sharing": "^5.25.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic-native/unique-device-id": "^5.25.0",
    "@ionic/angular": "^5.0.0",
    "@ionic/storage": "^2.2.0",
    "com.darktalker.cordova.screenshot": "^0.1.6",
    "cordova-plugin-advanced-http": "^2.4.1",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-crop": "^0.4.0",
    "cordova-plugin-device-motion": "^2.0.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-google-analytics": "^1.9.0",
    "cordova-plugin-googleplus": "^8.5.0",
    "cordova-plugin-inappbrowser": "^3.2.0",
    "cordova-plugin-screen-orientation": "^3.0.2",
    "cordova-plugin-uniquedeviceid": "^1.3.2",
    "cordova-plugin-x-socialsharing": "^5.6.5",
    "highcharts": "^8.1.0",
    "ion2-calendar": "^3.0.0-rc.0",
    "ionic-cache": "^5.2.0",
    "moment": "^2.25.3",
    "onesignal-cordova-plugin": "^2.9.1",
    "rxjs": "~6.5.1",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.5",
    "@angular/cli": "~9.1.5",
    "@angular/compiler": "~9.1.6",
    "@angular/compiler-cli": "~9.1.6",
    "@angular/language-service": "~9.1.6",
    "@capacitor/cli": "2.1.0",
    "@ionic/angular-toolkit": "^2.1.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"

in my App.module i import
import { Camera } from '@ionic-native/camera/ngx';

and provider
 Camera,

## Problem
My VS code keep showing this error:

Type 'CameraOriginal' is not assignable to type 'Provider'.
  Type 'CameraOriginal' is missing the following properties from type 'any[]': length, pop, push, concat, and 26 more.ts(2322)

i try uninstall and install again but the error still there.

may i know what problem is this?

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
This is probably the same as https://github.com/ionic-team/ionic-native/issues/3415 and has nothing to do with this plugin.

**Comment by zero-1** [comment]
try doing ..

`import { Camera } from '@ionic-native/camera/ngx/index';`
