### ISSUE TITLE
Android navigation bar overlaps "Retake" and "Ok" Buttons

### ISSUE THREAD

**Issue by mhornung85** [apache/cordova-plugin-camera#599]
# Bug Report

## Problem
On some Devices (Galaxy A20e (a20e) (SM-A202F) OS 10, Galaxy A40 (a40) (SM-A405FN) OS) the Android navigation bar overlaps the retake and ok button (pls. see picture
![PHOTO-2020-05-14-11-50-44](https://user-images.githubusercontent.com/1035269/81930176-808e9280-95e8-11ea-80bd-a66a20c156fa.jpg)
 attached).

### What is expected to happen?
Buttons are completely reachable, e.g. above the navigation bar.

### What does actually happen?
Buttons are mostly covered by the navigation bar making it hard to reach the buttons. If you´re not exactly looking where you´re clicking, youre hitting "back" and the photo is gone.

### Version information
(Galaxy A20e (a20e) (SM-A202F) OS 10, Galaxy A40 (a40) (SM-A405FN) OS)
camera plugin version: 4.1.0
ionic info:
Ionic:

   Ionic CLI                     : 6.2.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 9.0.5
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 15 other plugins)

Utility:

   cordova-res (update available: 0.14.0) : 0.10.0
   native-run (update available: 1.0.0)   : 0.3.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.16.1 (/usr/local/bin/node)
   npm        : 6.13.4
   OS         : macOS Catalina
   Xcode      : Xcode 11.4.1 Build version 11E503a

## Checklist
- [ x] I searched for existing GitHub issues
- [ not the camera version, since I don´t have direct access to one of those devices + the last release notes mentioned nothing that is related to this issue] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by gcancro** [comment]
I've got the same problem. Did you sort it out?

**Comment by matchdogmx** [comment]
did you resolve it?

**Comment by jcesarmobile** [comment]
Camera plugin just launches an intent to the camera app, has no control about the camera UI since it’s a different app.
