### ISSUE TITLE
Publish version 4.2.0 to npm

### ISSUE THREAD

**Issue by kevinswartz** [apache/cordova-plugin-camera#602]
Hi guys,
Thanks for your help on this great plugin!  Any chance version 4.2.0 is getting published to npm any time soon?  I'm looking in particular at your ios fix for the camera running on a background thread.
Thanks again!

**Comment by jcesarmobile** [comment]
the vote for releasing it failed and it's broken for Android, so won't be released until it's fixed

**Comment by jprinsloo** [comment]
Does anyone know when the Android-specific fix will be made so that a release can be made?
