### ISSUE TITLE
preview photos in opening photolibrary

### ISSUE THREAD

**Issue by carolinetanxin** [apache/cordova-plugin-camera#603]
# Feature Request
preview photos in album

## Motivation Behind Feature

Thanks to the plugin , it help me to solve a lot . But users said that the photo in ablums look small that they always select wrong photos. So they want that they can preview photos when open the local album like wechat. . How can I solve this problem. If there is any suggestion ?

## Feature Description
When open the photolibrary （this.camera.PictureSourceType.PHOTOLIBRARY） , users can preview the photos and swipe.

## Alternatives or Workarounds
I try to use this plugin [cordova-plugin-ImagePicker](https://github.com/giantss/cordova-plugin-ImagePicker) to preview photos. But it will crash after confirm the selected pictures in iOS . And it can't like corova-plugin-camera to show photo in <img> immediately after select picture . It won't appear until I tap anywhere on the screen neither in iOS or Android.

**Comment by jcesarmobile** [comment]
the native component used by this plugin can't do that, sorry
