### ISSUE TITLE
don't build for android in phonegap

### ISSUE THREAD

**Issue by aribela** [apache/cordova-plugin-camera#605]
## Problem
i build in phonegap for android but the cordova-plugin-camera causes this error:

WARNING: Overriding compileSdkVersion from android-26 (default) to android-28
WARNING: This is unsupported, please consider updating your phonegap version instead

i use cordova cli-8.0.0 and cordova-plugin-camera 4.1.0 version

**Comment by breautek** [comment]
Latest version of cordova-android uses target/compile sdk version 28. As the warning says, you'll need to update phonegap.

If there is an issue, you should raise an issue with phonegap.
