### ISSUE TITLE
Document practical example of uploading files

### ISSUE THREAD

**Issue by slothstronaut** [apache/cordova-plugin-camera#608]
# Feature Request

## Motivation Behind Feature

The documentation does not show a functional example of uploading a file to a remote endpoint, which likely is the most common use case.

## Feature Description

Simply show a full example, don't leave a comment saying "now you can upload", show the user how, its actually quite difficult to solve without this.

## Alternatives or Workarounds

Sure, hundreds or thousands of people can haphazardly figure it out on their own

**Comment by jcesarmobile** [comment]
I think this is out of the scope of the plugin, the docs are already too complex.

If it helps, we wrote a blog post about transitioning from cordova-plugin-file-transfer to using XHR, you can probably take the XHR part to upload your pictures.

**Comment by FractalMind** [comment]
At least post an example here on how to upload with httpClient
