### ISSUE TITLE
Problem with NSPhotoLibraryUsageDescription when source is GIT

### ISSUE THREAD

**Issue by PegasusAwesome** [apache/cordova-plugin-camera#609]
# Bug Report
First of all: thanks for the wonderfull plugin :)

## Problem
NSPhotoLibraryUsageDescription is not included in Info.plist, this leads to a rejection by Apple

### What is expected to happen?
NSPhotoLibraryUsageDescription should be included in Info.plist

### What does actually happen?
NSPhotoLibraryUsageDescription is not included after build

## Information
The problem happens when I define the plugin as such in my config,xml:
```
<plugin name="cordova-plugin-camera" spec="https://github.com/apache/cordova-plugin-camera" source="git">
       <param name="CAMERA_USAGE_DESCRIPTION" value="We need access to scan qr codes and to show the buildingmanager pictures of the problem." />
       <param name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="We need access to scan qr codes and to show the buildingmanager pictures of the problem." />
</plugin>
```

The problem does NOT happen when I define the plugin as this:
```
<plugin name="cordova-plugin-camera" source="npm" spec="=4.1.0">
       <param name="CAMERA_USAGE_DESCRIPTION" value="We need access to scan qr codes and to show the buildingmanager pictures of the problem." />
       <param name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="We need access to scan qr codes and to show the buildingmanager pictures of the problem." />
</plugin>
```

I've tried adding the following to the config.xml file, to prevent the problem:
```
<config-file parent="NSPhotoLibraryUsageDescription" platform="ios" target="*-Info.plist">
    <string>We need access to scan qr codes and to show the buildingmanager pictures of the problem.</string>
</config-file>
```
And also tried adding this to the config.xml:
```
<edit-config target="NSPhotoLibraryUsageDescription" file="*-Info.plist" mode="merge">
    <string>We need access to scan qr codes and to show the buildingmanager pictures of the problem.</string>
</edit-config>
```

But both those config entries do not resolve the problem.

Ps.: I need the 4.2.0 version, because of the fixes for video.

### Command or Code
The problem occurs as soon as I place this string in the config.xml:
```
    <plugin name="cordova-plugin-camera" spec="https://github.com/apache/cordova-plugin-camera" source="git">
       <param name="CAMERA_USAGE_DESCRIPTION" value="We need access to scan qr codes and to show the buildingmanager pictures of the problem." />
       <param name="PHOTOLIBRARY_USAGE_DESCRIPTION" value="We need access to scan qr codes and to show the buildingmanager pictures of the problem." />
    </plugin>
```

### Environment, Platform, Device
Phonegap build => upload to iOS

### Version information
Phonegap CLI
cordova-plugin-camera from git
iOS

## Checklist
- [X ] I searched for existing GitHub issues
- [ X] I updated all Cordova tooling to most recent version
- [ X] I included all the necessary information above

**Comment by PegasusAwesome** [comment]
Just tried all possible combinations: without params, with params, without edit-config, with params. Nothing works.
The camera usage string can be found in the info.plist, but the photolibrary usage string is never in the info plist.
Well, unless I use the older npm version...
Anybody got any idea or workaround?

**Comment by jcesarmobile** [comment]
the plugin doesn't add usage descriptions, you have to add them using `edit-config` tags in `config.xml`
```
<edit-config target="NSPhotoLibraryUsageDescription" file="*-Info.plist" mode="merge">
    <string>need photo library access to get pictures from there</string>
</edit-config>
```

**Comment by jcesarmobile** [comment]
if edit-config is not working fine, then you should report it in cordova-cli repo, but it's not a plugin issue, closing

**Comment by PegasusAwesome** [comment]
Hiya,

> the plugin doesn't add usage descriptions, you have to add them using `edit-config` tags in `config.xml`
> 
> ```
> <edit-config target="NSPhotoLibraryUsageDescription" file="*-Info.plist" mode="merge">
>     <string>need photo library access to get pictures from there</string>
> </edit-config>
> ```

As you can read in my report, I've literally tried doing exactly that. 
And when I use one version of the plugin that works. However, with the latest version of cordova-camera-plugin, the NSPhotoLibraryUsageDescription disappears from info.plist.

So, to me it seems that this is a plugin issue. One version of the plugin: no problem, other version of the plugin: there is a problem. 

Of course, if this should be reported to the cordova cli repo, I'd be happy to do so, just seems a plugin problem. 

Best,
Marcel

**Comment by jcesarmobile** [comment]
The thing that adds the NSPhotoLibraryUsageDescription is the CLI, not the plugin, so it’s imposible that this is a plugin issue.

**Comment by PegasusAwesome** [comment]
Ok, so the fact that the only difference between my two config.xml files is the plugin version, doesn't indicate that this is a plugin problem.

Thanks and have a nice day.

**Comment by jcesarmobile** [comment]
Just noticed you use phonegap build, as far as I remember they use a slightly different syntax for the edit-config and config-file entries, that could be the problem too.

**Comment by PegasusAwesome** [comment]
Hey, thanks, Im gonna try to google that ;)
If you'd happen to have a url towards that syntax, Id be very grateful, if not, no worries, google-fu re-activated ;)

**Comment by PegasusAwesome** [comment]
still weird though that it would work with one version and not the other
