### ISSUE TITLE
v4.2.0 missing on npmjs

### ISSUE THREAD

**Issue by BorntraegerMarc** [apache/cordova-plugin-camera#610]
Latest release is v4.2.0: https://github.com/apache/cordova-plugin-camera/blob/master/RELEASENOTES.md

But I think you forgot to publish it to npmjs: https://www.npmjs.com/package/cordova-plugin-camera (latest one is v4.1.0)

**Comment by erisu** [comment]
Officially, the v4.2.0 release has failed to pass the vote and has not be released.
It will not be released to npm until a successful vote and at this time it has been halted.

**Comment by BorntraegerMarc** [comment]
Thx for the info!

May I ask why it has failed to pass the vote? (out of curiosity if I should install this version directly from github or if some bugs are to be expected)

**Comment by breautek** [comment]
v4.2.0 is broken on android. You can expect this issue: https://github.com/apache/cordova-plugin-camera/issues/601
