### ISSUE TITLE
Get gps data from image(Like were the image was clicked)

### ISSUE THREAD

**Issue by SumeetHindinkeri** [apache/cordova-plugin-camera#615]
I want to know if it really supports to get gps(lat,long) from image when the image is clicked. I have following code is it possible to get gps data from image with following code use:

    const cameraOptions: CameraOptions = {
      sourceType: this.camera.PictureSourceType.CAMERA,
      destinationType: this.camera.DestinationType.FILE_URI,
      quality: 50,
      encodingType: this.camera.EncodingType.JPEG,
      correctOrientation: true,
      saveToPhotoAlbum: true,
      mediaType: this.camera.MediaType.PICTURE,
      targetWidth: 1000,
      targetHeight: 1000
    }

    this.camera.getPicture(cameraOptions).then(fileUrl => {});

**Comment by indraraj26** [comment]
use cordova plugin geolocation along with this plugin

**Comment by SumeetHindinkeri** [comment]
@indraraj26  I using geolocation plugin but if I get the image from photo library then in that case its not possible. There is a plugin cordova-camera-plugin-with-exif which gets gps data for ios but not for android. Basically along with the fileUrl it should return metadata of image.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).

**Comment by SumeetHindinkeri** [comment]
@timbru31  I tried on cordova channel though no one responds so I opened an issue here!

**Comment by SumeetHindinkeri** [comment]
If anyone comes searching for it. This is stock and forked plugin which will work:
https://github.com/vlinde/cordova-plugin-camera-with-exif
Though it is not rebased with current plugin.
