### ISSUE TITLE
When users installed the android application and try to capture the video first time. Permission is not asked in android mobile's.This was happening in all the android version's 

### ISSUE THREAD

**Issue by Manigandasubbu** [apache/cordova-plugin-camera#618]
# Bug Report

### What is expected to happen?

It need to ask the storage permission for capturing the video. So the i can able to transfer the video.

### What does actually happen?

Because it's not asking the storage permission i am not able to transfer the video to the back-end.

## Information

When user try first time when app was installed to capture a video i need to get the storage permission but it was not happening. 

### Command or Code

  async captureVideo(): Promise<void> {
    const videoOptions: CaptureVideoOptions = { duration: 30 };

    try {
      const data: MediaFile[] | CaptureError =
        await this.mediaCapture.captureVideo(videoOptions);
      const video = data[0];
      const sizeError = await this.compareFileSizes(video.size);
      if (sizeError) throw sizeError;

      const fileObject = new FileObject();

      fileObject.name = 'file';
      fileObject.type = video.type;
      fileObject.data = video.fullPath;

      this.uploadFile(fileObject);
    } catch (error) {
      this.handleUploadError(error);
    }
  }

### Environment, Platform, Device

In all the Android version i have the same problem. 

### Version information

    "cordova-plugin-camera": "^4.1.0",

      "cordova-plugin-camera": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
  Operating System : Ubuntu 18.04.
 Cordova : 9,
Ionic version:-6.2.1
## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Can you tell me if you see `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` in your `platforms/android/app/src/main/AndroidManifest.xml` file?

**Comment by Manigandasubbu** [comment]
> Can you tell me if you see `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` in your `platforms/android/app/src/main/AndroidManifest.xml` file?

No ,Can i know where should i need to add that,When i try to capture the picture it was asking storage permission,If i capture the video it's not asking the storage permission.

**Comment by breautek** [comment]
> > Can you tell me if you see `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` in your `platforms/android/app/src/main/AndroidManifest.xml` file?
> 
> No ,Can i know where should i need to add that,When i try to capture the picture it was asking storage permission,If i capture the video it's not asking the storage permission.

Should be added automatically when you install the plugin/platform. If it's missing from your `AndroidManifest` that would explain why you're not getting a permission prompt. The question then becomes "Why wasn't that line added to your `AndroidManifest`?".

Some things I'd try:

- Ensure you're using the latest version of `cordova-android` (version `9.0.0` at the time of writing, not to be confused with the `cordova` cli version)
- Reinstall the `cordova-android` platform
- Reinstall the `cordova-plugin-camera` plugin.

If none of the above doesn't work, then I would confirm that this happens in a pure-cordova project (no frameworks), to eliminate the possibility that the problem is coming from a framework. If you can share a [sample reproduction app](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md) while using no frameworks, that would be very helpful.

**Comment by Manigandasubbu** [comment]
> > > Can you tell me if you see `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` in your `platforms/android/app/src/main/AndroidManifest.xml` file?
> > 
> > 
> > No ,Can i know where should i need to add that,When i try to capture the picture it was asking storage permission,If i capture the video it's not asking the storage permission.
> 
> Should be added automatically when you install the plugin/platform. If it's missing from your `AndroidManifest` that would explain why you're not getting a permission prompt. The question then becomes "Why wasn't that line added to your `AndroidManifest`?".
> 
> Some things I'd try:
> 
> * Ensure you're using the latest version of `cordova-android` (version `9.0.0` at the time of writing, not to be confused with the `cordova` cli version)
> * Reinstall the `cordova-android` platform
> * Reinstall the `cordova-plugin-camera` plugin.
> 
> If none of the above doesn't work, then I would confirm that this happens in a pure-cordova project (no frameworks), to eliminate the possibility that the problem is coming from a framework. If you can share a [sample reproduction app](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md) while using no frameworks, that would be very helpful.

Yes i tried many times no use on it.

**Comment by Manigandasubbu** [comment]
> > > Can you tell me if you see `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` in your `platforms/android/app/src/main/AndroidManifest.xml` file?
> > 
> > 
> > No ,Can i know where should i need to add that,When i try to capture the picture it was asking storage permission,If i capture the video it's not asking the storage permission.
> 
> Should be added automatically when you install the plugin/platform. If it's missing from your `AndroidManifest` that would explain why you're not getting a permission prompt. The question then becomes "Why wasn't that line added to your `AndroidManifest`?".
> 
> Some things I'd try:
> 
> * Ensure you're using the latest version of `cordova-android` (version `9.0.0` at the time of writing, not to be confused with the `cordova` cli version)
> * Reinstall the `cordova-android` platform
> * Reinstall the `cordova-plugin-camera` plugin.
> 
> If none of the above doesn't work, then I would confirm that this happens in a pure-cordova project (no frameworks), to eliminate the possibility that the problem is coming from a framework. If you can share a [sample reproduction app](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md) while using no frameworks, that would be very helpful.

Tomorrow i will share it.

**Comment by Manigandasubbu** [comment]
[videoe410c2a6-3e8e-4a5b-bbc3-ccf4f800c65bvideo.zip](https://github.com/apache/cordova-plugin-camera/files/4874543/videoe410c2a6-3e8e-4a5b-bbc3-ccf4f800c65bvideo.zip)
I shared a video recording the bug,I am working on sample application.When done i will share it.And i tried all my cordova version is 9 and i tried all the way's what you told.

**Comment by indraraj26** [comment]
You can clone this and reproduce for me
git : https://github.com/indraraj26/cordova-camera-fast-click

npm i 
cordova platform add android
cordova build android
