### ISSUE TITLE
Release 4.2.0 on npm?

### ISSUE THREAD

**Issue by grischan** [apache/cordova-plugin-camera#619]
Hello,

could the new version 4.2.0 published on npmjs? The latest version there is 4.1.0.

Thank you and best Regards
Christian

**Comment by erisu** [comment]
Cordova does not have a 4.2.0 release.

**Comment by grischan** [comment]
I dont mean the version of cordova,  I mean the camera-plugin itself on npm.

**Comment by timbru31** [comment]
That's what erisu meant, too. The attempted release for 4.2.0 failed as it's broken on Android. We are currently working on a new version (no ETA)

**Comment by DURK** [comment]
@timbru31 I don't see any issues on the Travis build of 4.2.0. Am I missing something?
https://travis-ci.org/github/apache/cordova-plugin-camera/builds/684163700

**Comment by timbru31** [comment]
Yes the issue was not discovered with automated testing (i.e., Travis is green)but observed when we've done manual testing.

Yes, a regression test should be added, but our current plugin testing setup is...well not optimal.

**Comment by DURK** [comment]
@timbru31 I see. Do you know what issue was found on Android?

Reason I'm asking: I'm mainly using the Capacitor's Camera API, but as this doesn't have the **select a video from library** feature, I'm still using the **cordova-plugin-camera** for that. So far, I've not found any issues with this feature, so I could be safe just updating to 4.2.0. But I want to be sure it's not some obscure issue or memory leak.
