### ISSUE TITLE
Can't access to file photolibrary with cordova ios 6.1.0 and wkwebview

### ISSUE THREAD

**Issue by fattanasio** [apache/cordova-plugin-camera#622]
# Bug Report

## Problem
I created a new standard with ios 6 to avoid rejecting the app from Apple.
In the config.xml I entered:
```xml
<preference name = "scheme" value = "app" />
<preference name = "hostname" value = "localhost" />
```
to be able to navigate in my application.
When I call the camera plugin:

```js
navigator.camera.getPicture(function(fileURI) {
		previewFoto(fileURI, id);
	}, function(error) {
		captureFotoError(error, id);
	},
	{
	quality: 20, 
	sourceType: navigator.camera.PictureSourceType.PHOTOLIBRARY,
	mediaType: navigator.camera.MediaType.PICTURE,
	destinationType: navigator.camera.DestinationType.FILE_URI 
	}
);

function previewFoto(fileURI,id){
    var thumbnailPhoto = document.getElementById('thumbnailPhoto_'+id);
    $("#thumbnailPhoto_"+id).addClass("thumbnail");
    thumbnailPhoto.src=fileURI;
}
```
I can't see the preview. Before installing cordova ios 6 and therefore also wkwebview the application worked correctly. 
Now I think there is a problem of link to the uri file of type file: //etc..../tmp/filename.jpg
I have searched all the forums but I cannot understand how to point to a camera file directly in my app.
I have cordova ios 6.1.0 and latest cordova-plugin-camera

Do you have any suggestions ?
Thanks so much !

### What is expected to happen?
Preview of image retrieved by camera plugin

### What does actually happen?
Preview is blank image. Probably error access to file://etc...../tmp/file

### Command or Code
```js
navigator.camera.getPicture(function(fileURI) {
		previewFoto(fileURI, id);
	}, function(error) {
		captureFotoError(error, id);
	},
	{
	quality: 20, 
	sourceType: navigator.camera.PictureSourceType.PHOTOLIBRARY,
	mediaType: navigator.camera.MediaType.PICTURE,
	destinationType: navigator.camera.DestinationType.FILE_URI 
	}
);

function previewFoto(fileURI,id){
    var thumbnailPhoto = document.getElementById('thumbnailPhoto_'+id);
    $("#thumbnailPhoto_"+id).addClass("thumbnail");
    thumbnailPhoto.src=fileURI;
}
```

### Environment, Platform, Device
The problem occurs on device IOS and on simulator xcode

### Version information
CORDOVA IOS 6.1.0
Cordova CLI version 9.0

## Checklist

- [x ] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by timbru31** [comment]
One issue is more than enough. Since you've provided more information, I'll close #621 instead.

**Comment by dolin-tan** [comment]
There is no imagedata in the callback after the photo is taken successfully in wkwebview

**Comment by jcesarmobile** [comment]
If using a custom scheme, the WebView won't allow to load file urls in img/video tags (nor fetch them, nor anything).
cordova-ios added a helper method to convert file urls to urls that have the scheme and the WebView can understand.

`window.WkWebView.convertFilePath('your/file/path');`

I've created an issue in cordova-ios to document it https://github.com/apache/cordova-ios/issues/947

**Comment by thirdwheel** [comment]
> If using a custom scheme, the WebView won't allow to load file urls in img/video tags (nor fetch them, nor anything). cordova-ios added a helper method to convert file urls to urls that have the scheme and the WebView can understand.
> 
> `window.WkWebView.convertFilePath('your/file/path');`
> 
> I've created an issue in cordova-ios to document it [LINK REDACTED]

This didn't work for me, but what did work was changing the destination type to DATA_URL - note that it won't actually give you a data URL, it'll give you the base64 encoded contents, but I can't imagine it giving you something other than the encoding type you defined.
