### ISSUE TITLE
FileTransfer Dependency is Deprecated and Throws Error in XCode Build on cordova-ios v6

### ISSUE THREAD

**Issue by patrickghidossi** [apache/cordova-plugin-camera#624]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Support Question

## Description
Upon upgrading to cordova-ios 6.1.0, and then proceeding to build my application in XCode, the following error is thrown from the cordova-plugin-file-transfer code:

<img width="236" alt="Screen Shot 2020-07-09 at 1 30 45 PM" src="https://user-images.githubusercontent.com/20171803/87082572-7522a680-c1e8-11ea-914f-d02f56475483.png">

cordova-plugin-camera still installs cordova-plugin-file-transfer as a dependency even though it has been deprecated since 2017 (https://cordova.apache.org/blog/2017/10/18/from-filetransfer-to-xhr2.html), thus we have no recourse to address this error.

This will need to be resolved soon as upgrading to cordova-ios version 6 will be required in iOS applications because of Apple's new WKWebView requirement: https://developer.apple.com/documentation/uikit/uiwebview.

Users will likely be forced off of this camera plugin otherwise.

### Version information
cordova-ios 6.1.0
cordova-plugin-camera 4.1.0

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
The camera plugin does not define `cordova-plugin-file-transfer` as a dependency, which is observable by looking at its `plugin.xml` file under the `4.1.0` release tag.

You likely still have a lingering reference of `cordova-plugin-file-transfer` in your `config.xml` or in your `package.json`. A `cordova plugin remove cordova-plugin-file-transfer` should clean everything up
