### ISSUE TITLE
Ionic Capacitor android.support.v4.content.FileProvider

### ISSUE THREAD

**Issue by pioneersingh321** [apache/cordova-plugin-camera#633]
# Bug Report
adding to ionic capacitor project its throw error while building application android.support.v4.content.FileProvider
## Problem
adding to ionic capacitor project its throw error while building application android.support.v4.content.FileProvider
### What is expected to happen?
not able to build 

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by erisu** [comment]
Ionic Capacitor is not Cordova. If you have an issue with Ionic Capacitor please contact Ionic for support.
