### ISSUE TITLE
Camera Not Working in Android 5.1/ Lollipop

### ISSUE THREAD

**Issue by cyrilxx** [apache/cordova-plugin-camera#638]
# Bug Report

### What is expected to happen?
Camera wont open in android 5.1/lollipop

### What does actually happen?
When opening camera error occurs illegal argument exception

### Command or Code

function capturePhoto() {
    navigator.camera.getPicture(onPhotoURISuccess, onFail, {
        quality: 90,
        destinationType: destinationType.DATA_URL,
        correctOrientation: true,
    });
}

### Environment, Platform, Device

Android 5.1 Emulator

### Version information

Cordova 9.0
"cordova-plugin-camera": "^4.1.0",

## Checklist

- [ X] I searched for existing GitHub issues
- [ X] I updated all Cordova tooling to most recent version
- [ X] I included all the necessary information above

**Comment by breautek** [comment]
Are you using `cordova-android@9`? If so, can you retry with setting the preference `android-targetSdkVersion` to `28`? Curious if this is an API level introduced issue.

**Comment by betagole** [comment]
Was there a fix for this? I'm also experiencing this problem.

**Comment by cyrilxx** [comment]
@betagole I think this is an emulator issue. just edit your emulator camera settings to emulated

**Comment by betagole** [comment]
I wasn't using an emulator. I downgraded to @4.1.0 and it worked on my phone now.

**Comment by cyrilxx** [comment]
hello please make sure you updated your webview, maybe some js not running correctly on 5.1
