### ISSUE TITLE
Unable to create bitmap!

### ISSUE THREAD

**Issue by epetre** [apache/cordova-plugin-camera#642]
# Bug Report
Crashlytics is giving us "Unable to create bitmap!" error for some users who try to take a picture.

## Problem
An error happens as the user uploads what seems to him as a valid picture and he is stuck on that page because we require a picture.

### What is expected to happen?
Just a normal flow of taking a picture and getting it's URL.

### What does actually happen?
An error occurs and the user is stuck there "Unable to create bitmap!"

## Information
So I don't have more information than what Crashlytics gives me other than the fact that it happens 100% of the time on Android and the below code and environment details.

### Command or Code
//Not sure exactly where in the plugin, but here is how we call it.
```
    let options = {
      quality : 100,
      destinationType: this.camera.DestinationType.DATA_URL,
      sourceType: sourcetype,
      encodingType: this.camera.EncodingType.JPEG, //0 JPEG
      saveToPhotoAlbum: false,
      correctOrientation: true,
      cameraDirection: 1,//front
      allowEdit: false
    }

    return new Promise((resolve, reject) => {
      this.camera.getPicture(options).then(base64 => {
   
      }
   }
```

### Environment, Platform, Device
Android, no specific version stands out.

### Version information
```
Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
Cordova Platforms : android 8.1.0, ios 5.1.1
Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 5.0.0, (and 26 other plugins)
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by wongpeiyi** [comment]
Had this happen on a production user too

```
Mozilla/5.0 (Linux; Android 9; INE-LX2 Build/HUAWEIINE-LX2; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.90 Mobile Safari/537.36
```

Not much other info. Hopefully this helps

**Comment by furkankatman** [comment]
I am still seeing this issue. Any solution for this ?

**Comment by xuyonghua** [comment]
The storage has changed after Android11, and the APP can only access its own private directory or public directory, and cannot access the private directory of other apps. You call the system’s built-in crop that does not belong to your app, and access to your app’s private directory is not allowed. Please add the following compatible code to the createCaptureFile method.
`
if (Build.VERSION.SDK_INT >= 30) {
          return new File(Environment.getExternalStoragePublicDirectory(DIRECTORY_PICTURES), fileName);
        }
`

**Comment by PieterVanPoyer** [comment]
@epetre is this issue still happening with the latest version?

**Comment by shahdeep1989** [comment]
@PieterVanPoyer Yes I am still facing same issue with latest version.

var options = {
      quality: 90,
      destinationType: Camera.DestinationType.DATA_URL,
      sourceType: 1,
      encodingType: 1,  // JPEG=0  PNG=1
      mediaType: Camera.MediaType.PICTURE,
      allowEdit: true,
      correctOrientation: true,
      targetWidth: 480,
      targetHeight: 480,
      cameraDirection: 1
    };

**Comment by fullmooooon** [comment]
The same mistake （error in JavaScript  onFail）, different reasons and Solutions
My app runs on an Android 10 AR device
I annotate a line of code which been red highlight error in my android studio Logcat to solve it
`//            this.cordova.getActivity().getContentResolver().delete(uri, null, null);`
Maybe my device just doesn't allow cordova to delete cacah.

For a suggestion, try view Android studio logcat

**Comment by xiandanchaorenguagua** [comment]
> 
resolved,thx~~

**Comment by kapilSoni101** [comment]
@xuyonghua sir can you tell me where we out above codes?

**Comment by breautek** [comment]
stale
