### ISSUE TITLE
Update npm release to 4.2.0

### ISSUE THREAD

**Issue by dpalou** [apache/cordova-plugin-camera#643]
# Feature Request

## Motivation Behind Feature
The 4.2.0 version of the plugin includes some important fixes, like https://github.com/apache/cordova-plugin-camera/issues/506. But the version published in npm is still 4.1.0. 

## Feature Description
Please release the 4.2.0 version in npm too:

https://www.npmjs.com/package/cordova-plugin-camera

## Alternatives or Workarounds
The workaround is to install the plugin using the github URL and tag:

https://github.com/apache/cordova-plugin-camera#4.2.0

**Comment by erisu** [comment]
Duplicate #619

The version `4.2.0` has failed the release vote and is broken for Android platform.
This version will not be released to NPM.
