### ISSUE TITLE
Version 4.2.0 has known breaking issues for android (if I recall properly) that caused the release vote to fail, so version 4.2.0 will not be released.

### ISSUE THREAD

**Issue by aquario-one** [apache/cordova-plugin-camera#644]
Version 4.2.0 has known breaking issues for android (if I recall properly) that caused the release vote to fail, so version 4.2.0 will not be released.

_Originally posted by @breautek in https://github.com/apache/cordova-plugin-camera/issues/530#issuecomment-675553747_

Can you, please, give me some recomendations to fix original problem posted in related issue ???

**Comment by timbru31** [comment]
Wait for a new release to contain the fix (#551).
