### ISSUE TITLE
Support AndroidX

### ISSUE THREAD

**Issue by eviv3k** [apache/cordova-plugin-camera#649]
Are you going to update the plugin to support AndroidX?

Thanks

**Comment by weijyewang** [comment]
+1

**Comment by weijyewang** [comment]
@eviv3k  I just found this https://github.com/apache/cordova-plugin-camera/pull/418

**Comment by timbru31** [comment]
Overall discussion in regards to AndroidX is at https://github.com/apache/cordova/issues/69
