### ISSUE TITLE
Picture is not taken in full resolution but scaled

### ISSUE THREAD

**Issue by Gulum** [apache/cordova-plugin-camera#652]
# Bug Report

### What is expected to happen?
Picture should be taken in full resolution

### What does actually happen?
Picture is taken not in full resolution but rather scaled.

## Information

CameraPreview.m
Line 704 seems to produce this error. When the same Resolution as the picture is given as a parameter, the image gets scaled by the factor 0.75.

### Command or Code
---

### Environment, Platform, Device
IOS

## Checklist
- [ X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by breautek** [comment]
> CameraPreview.m
Line 704 seems to produce this error. When the same Resolution as the picture is given as a parameter, the image gets scaled by the factor 0.75.

This plugin does not have a `CameraPreview` class.

https://github.com/apache/cordova-plugin-camera/tree/master/src/ios

**Comment by Gulum** [comment]
Youre totally right, had multiple tabs with almost the same name. Moved it to the right project (cordova-plugin-camera-preview).

**Comment by Gulum** [comment]
Youre totally right, had multiple tabs with almost the same name. Moved it to the right project (cordova-plugin-camera-preview).
