### ISSUE TITLE
Version missmatch Github vs npmjs.com

### ISSUE THREAD

**Issue by boengli** [apache/cordova-plugin-camera#653]
Can someone explain why the latest version on npm is 4.1.0 and here it's 4.2.0?
How can I update to 4.2.0 with npm?

Thanks

**Comment by erisu** [comment]
Please search the issue tracker before creating ticket.

> I searched for existing GitHub issues

Is one items suppose to have checked, IF the issue template was not deleted.

4.2.0 vote has failed and is broken and wont be on NPM.

https://github.com/apache/cordova-plugin-camera/issues/602
https://github.com/apache/cordova-plugin-camera/issues/604
https://github.com/apache/cordova-plugin-camera/issues/610
https://github.com/apache/cordova-plugin-camera/issues/613
https://github.com/apache/cordova-plugin-camera/issues/619
https://github.com/apache/cordova-plugin-camera/issues/639
https://github.com/apache/cordova-plugin-camera/issues/643
https://github.com/apache/cordova-plugin-camera/issues/644
