### ISSUE TITLE
Ios gallery sometimes shows no photos or Videos

### ISSUE THREAD

**Issue by giteshpatil** [apache/cordova-plugin-camera#657]
# Bug Report

### What is expected to happen?
 It should always open gallery with all the available photos.

### What does actually happen?
On some cases it opens as blank giving message no photos or videos.
[https://ibb.co/qgYk5pR](https://ibb.co/qgYk5pR)

### Command or Code

Code Used:
        const options: CameraOptions = {
          quality: 100,
          sourceType: this.camera.PictureSourceType.PHOTOLIBRARY,
          saveToPhotoAlbum: false,
          correctOrientation: true
        }

        this.camera.getPicture(options).then((imageData) => {
          //debugger
          console.log("imageData", imageData);
        }, (err) => {
          console.log(err);
        })

The same code works on another page but not working on a particular page.

### Environment, Platform, Device

Issue is happening on device iPhone 6 with os version 12.4.8
Plugin Version:  
"cordova-plugin-camera": "4.1.0"
"@ionic-native/camera": "4.20.0"

### Version information

Ionic:

   Ionic CLI          : 6.10.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 26 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.18.2 (/usr/local/bin/node)
   npm        : 6.14.5
   OS         : macOS Catalina
   Xcode      : Xcode 11.6 Build version 11E708

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
stale.

`NSPhotoLibraryUsageDescription` is required for accessing the user library. Not sure on iOS behaviour if key is not set.
