### ISSUE TITLE
Error on Camera Launch on Emulated Android 11 devices

### ISSUE THREAD

**Issue by jwburnside** [apache/cordova-plugin-camera#658]
# Bug Report

## Problem
When launching the camera on an emulated Android 11 device an error is thrown on **this.camera.getPicture()**

Error is: 
err: "Attempt to invoke virtual method 'boolean java.io.File.mkdirs()' on a null object reference"

### What is expected to happen?
Camera should function as it does on earlier emulated devices (<=29).

### What does actually happen?
After camera permission has been accepted, the app crashes completely (could not retrieve error in logcat). Subsequent attempts to launch the camera result in the error described above. 

## Information

- Ran with newly created project with only the camera plugin installed.
- Tested on several emulated Android 11 devices.
- No issues with physical Pixel 2 and Pixel 3 devices running Android 11.

### Command or Code
```
<!-- What command or code is needed to reproduce the problem? -->
const options: CameraOptions = {
      quality: 100,
      destinationType: this.camera.DestinationType.FILE_URI,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE
    }

    this.camera.getPicture(options).then((imageData) => {
      // imageData is either a base64 encoded string or a file URI
      // If it's base64 (DATA_URL):
      const base64Image = 'data:image/jpeg;base64,' + imageData;
    }, (err) => {
      console.log('err: ' + JSON.stringify(err));
      // Handle error
    });
```

### Environment, Platform, Device

- Emulated Android 11 devices (API 30)

### Version information

 Ionic CLI                     : 6.4.0 (/Users/j/.nvm/versions/node/v10.13.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 5 other plugins)

Utility:

   cordova-res (update available: 0.15.1) : 0.14.0
   native-run                             : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Users/j/Library/Android/sdk)
   ios-sim           : 8.0.1
   NodeJS            : v10.13.0 (/Users/j/.nvm/versions/node/v10.13.0/bin/node)
   npm               : 6.14.5
   OS                : macOS Catalina
   Xcode             : Xcode 11.6 Build version 11E708

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by mickytroxxy** [comment]
hey PTRFRLL, how did you solve this issue, i'm also stuck now. Thanks inadvance

**Comment by PTRFRLL** [comment]
> 
> 
> hey PTRFRLL, how did you solve this issue, i'm also stuck now. Thanks inadvance

I just switched my testing over to a physical device. Not ideal but it works for now.

**Comment by marshall86** [comment]
Hi, i'm having problem with cordova-plugin-camera 2.4.1 on an Ionic 3 project on a Samsung S10+ with Android 11 (emulator), my app crashes as soon as i try to take the picture after giving the permission.

Is there any fix for this?

**Comment by shoerofi** [comment]
i have this issue too

**Comment by PieterVanPoyer** [comment]
@jwburnside  is this issue still happening with the latest released version? If not, feel free to close this issue.

**Comment by Houdhey** [comment]
Same problem but app doesn't crash. Camera doesn't open, and there is no error message

**Comment by pcwSlide** [comment]
Yes code that worked 6 months ago on the Samsung Nexus emulator now does not - but still ok on a Pixel and my Moto g5 phone.
cordova-plugin-camera: 4.1.0
Cordova

Further
I upgraded the Emulator to Android 10 ( from 9 ) - now it works..

.

**Comment by Houdhey** [comment]
After using last version of plugin, deleting my android folder, and building a new one, (with capacitor), the problem didn't appear on emulator any more.

**Comment by PieterVanPoyer** [comment]
@jwburnside  is still issue still happening with the latest cordova versions?

**Comment by PieterVanPoyer** [comment]
Closing ticket due to lack of response, issue seems to be solved with the latest cordova versions..
