### ISSUE TITLE
IOS 14, Failed to read exposureBiasesByMode

### ISSUE THREAD

**Issue by vcomperq** [apache/cordova-plugin-camera#676]
# Bug Report

## Problem

unable to take picture

### What does actually happen?
i'am able to take picture but when i click on "use photo" in the preview, i get the following error 

> [Camera] Failed to read exposureBiasesByMode dictionary: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL}

### Version information

Cordova: 5.1.1 
Camera plugin 5.0.0
Other Frameworks: Ionic 4

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by WuglyakBolgoink** [comment]
@timbru31 I can reproduce this with Xcode 13 and iOS 14.6 (iPhoneX)

tested on 

- "cordova-ios": "6.2.0"
- "cordova-plugin-camera": "6.0.0",
