### ISSUE TITLE
How does quality convert to image size

### ISSUE THREAD

**Issue by gushi0224** [apache/cordova-plugin-camera#692]
Image size is dynamic, how to convert this?

If I want to limit one image to **105kb**, then what is quality?(**10,20 or...?**)

 CameraOptions = {
      quality: **??**,
      targetHeight: 500,
      targetWidth: 500,
      destinationType: this.camera.DestinationType.DATA_URL,
      sourceType: srcType,
      allowEdit: false,
      correctOrientation: true,
      encodingType: this.camera.EncodingType.JPEG,
      saveToPhotoAlbum: false,
      mediaType: this.camera.MediaType.PICTURE,
      cameraDirection: 0,
    }

because I only receive image size.

can anyone help to answer me this?

**Comment by breautek** [comment]
> Image size is dynamic, how to convert this?

Image size is always dynamic, it is impossible to get a specific size for an image. The size of the image depends on several factors including the resolution of the image, the quality of the image, and the nature of the capture image. An image that consists of straight lines and solid colors compresses easier than an image that contains complex shapes/lines and several colours. These all affect the resulting size of the image.

The `quality` option specifically is the inverse of the compression rate -- that is `0` means high compression (to reduce the file size at the lost of quality, ie the image will become "patchy"), and a value of 100 basically means no compression.

> this.camera.DestinationType.DATA_URL

Another note on sizes, `DATA_URL` means the image is represented in base64 encoded string. Binary data represented in base64 encoded string will be about 40% larger than the original binary in it's raw form. If you're concerned about image size, you may want to use `FILE_URI` instead.

**Comment by gushi0224** [comment]
@breautek  I am still confused, I need your further assistanc, I think.
