### ISSUE TITLE
[Android] content:// to file://storage does not get resolve

### ISSUE THREAD

**Issue by indraraj26** [apache/cordova-plugin-camera#695]
# Bug Report

## Problem
When you take pdf anyother file from download you get URI with content://. So in order to resolve i use this package to get file URI path https://www.npmjs.com/package/cordova-plugin-filepath

### What is expected to happen?
It should resolve and return file detail

### What does actually happen?
It returns error code: 1 // not found 

## Information

chrome://inspect
![image](https://user-images.githubusercontent.com/23274631/101600543-779c5d00-3a21-11eb-8f2f-f4ac4667cacf.png)

### Command or Code

```
const options: CameraOptions = {
          quality: 50,
          destinationType: this._camera.DestinationType.FILE_URI,
          mediaType: this._camera.MediaType.ALLMEDIA,
          sourceType: this._camera.PictureSourceType.SAVEDPHOTOALBUM,
          saveToPhotoAlbum: false,
        };
```
```
 if (file.indexOf("content://") > -1) {
          console.log("content //", file);
          window.FilePath.resolveNativePath(file, (success) => {
            console.log(success, "content");
            window.resolveLocalFileSystemURL(success, (fileEntry) => {
              console.log(fileEntry, "fileEntry");
              fileEntry.file((finalFile) => {
                console.log(finalFile, "resolve");
                resolve(finalFile);
              });
            });
          });
        }
```

### Environment, Platform, Device

All Android version i think so btw currently i am testing on Android 10 

### Version information

Cordova CLI       : 10.0.0
Cordova Platforms : android 9.0.0

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by breautek** [comment]
Just one bug ticket is enough. If this is a bug, it sounds like a `cordova-plugin-file` bug so I'll keep https://github.com/apache/cordova-plugin-file/issues/443 open and close this one.
