### ISSUE TITLE
On Android navigator.camera is undefined

### ISSUE THREAD

**Issue by Alessandro-PM** [apache/cordova-plugin-camera#698]
# On Android navigator.camera is undefined

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by Alessandro-PM** [comment]
done #701 please help me, I have the app blocked in production
