### ISSUE TITLE
Compile Android error: package android.support.v4.content does not exist

### ISSUE THREAD

**Issue by dgl30** [apache/cordova-plugin-camera#699]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Description
Ionic v. 5.4.16, Angular 9 and cordova-android@^9.0.0 conflict with plugin cordova-plugin-fingerprint-aio wich enables android.useAndroidX=true.
SDK android-30 or android-29 don't contain the package android.support.v4.content does not exist
Plugin cordova-plugin-androidx-adapter does not any effect.

### Command or Code
ionic cordova remove android
ionic cordova add android
ionic cordova build android
ionic cordova compile android <-- error here

CameraLauncher.java:42: error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;
FileProvider.java:21: error: package android.support.v4.content does not exist
public class FileProvider extends android.support.v4.content.FileProvider {}
CameraLauncher.java:296: error: cannot find symbol
        this.imageUri = FileProvider.getUriForFile(cordova.getActivity(),
CameraLauncher.java:823: error: cannot find symbol
                        Uri tmpFile = FileProvider.getUriForFile(cordova.getActivity(),

### Environment, Platform, Device
Android 11 (30 API level);

### Version information
Ionic v. 5.4.16
Gradle 6.5
Android Studio 4.x and WebStorm 2017.3
"cordova-android": "^9.0.0",
"cordova-plugin-androidx-adapter": "1.1.3",
"cordova-plugin-camera": "5.0.1",
"cordova-plugin-device": "2.0.2",
"cordova-plugin-file": "6.0.2",
"cordova-plugin-file-transfer": "1.7.1",
"cordova-plugin-fingerprint-aio": "4.0.1",
"cordova-plugin-inappbrowser": "4.0.0",
"cordova-plugin-ionic-keyboard": "2.2.0",
"cordova-plugin-ionic-webview": "5.0.0",
"cordova-plugin-splashscreen": "5.0.2",
"cordova-plugin-statusbar": "2.4.2",
"cordova-plugin-whitelist": "1.3.3",

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
Overall discussion in regards to AndroidX is at apache/cordova#69

**Comment by timbru31** [comment]
See also apache/cordova-android#841 and the discussion on YT: youtube.com/watch?v=oarY6ZYj-CU, if interested.

**Comment by farman-Ameer** [comment]
use this
ionic cordova plugin add  cordova-androidx-build

**Comment by breautek** [comment]
> @timbru31 Agree that overall discussion is at [apache/cordova#69](https://github.com/apache/cordova/issues/69), but what is best practice for users of this plugin at this point?

The latest release of this plugin is compatible with the latest release of cordova-android platform.
