### ISSUE TITLE
On Android navigator.camera is undefined (new)

### ISSUE THREAD

**Issue by Alessandro-PM** [apache/cordova-plugin-camera#701]
# Bug Report
On Android navigator.camera is undefined

## Problem
calling navigator.camera.getPicture results in a "Cannot read property 'getPicture' of undefined"

### What is expected to happen?
the call should open Camera or folder where images are present

### What does actually happen?
a javascript runtime error is produced:  Cannot read property 'getPicture' of undefined

## Information
I have a cordova app (Phonegap), a file newpost.js included in index.html file and a button that the user press on the form to add a picture. This app uses this plugin since I made it (5 years ago), and I think only lately the problem has occurred. 

### Command or Code

function getPhoto3() {      
      try
          {
     navigator.camera.getPicture(onPhotoDataSuccess, onFail, { quality: PIC_Q,
        destinationType: destinationType.DATA_URL,
        targetWidth: PIC_PROF_WIDTH, targetHeight: PIC_PROF_WIDTH,
        sourceType: pictureSource.PHOTOLIBRARY,correctOrientation:true });
          } catch (e)
              {
                DoAlert(e.message);
              }
    }

### Environment, Platform, Device

Cordova/Phonegap, on platform Android end on my device Samsung S9, my android emulator (pixel 2 api 29 android 10 x86)

### Version information

Cordova: cli-9.0.0 (Android 8.0.0)
Plugins: 
<plugin spec="https://github.com/MBuchalik/cordova-build-architecture.git#28e0237" />
<plugin spec="https://github.com/dpa99c/cordova-custom-config.git#fd54ff4" />
<plugin name="cordova-plugin-android-permissions" spec="1.1.2" />
<plugin name="cordova-plugin-app-launcher" spec="0.4.0" />
<plugin spec="https://github.com/pushandplay/cordova-plugin-apprate.git#a056ac7" />
<plugin spec="https://github.com/Rareloop/cordova-plugin-app-version.git#68ea434" />
<plugin name="cordova-plugin-calendar" spec="5.1.5" />
<plugin name="cordova-plugin-camera" spec="5.0.1" />
<plugin spec="https://github.com/hypery2k/cordova-certificate-plugin.git#7621758" />
<plugin spec="https://github.com/blakgeek/cordova-plugin-cocoapods-support.git#3f1f33d" />
<plugin spec="https://github.com/EddyVerbruggen/Custom-URL-scheme.git#881608e" />
<plugin name="cordova-plugin-device" spec="2.0.3" />
<plugin name="cordova-plugin-dialogs" spec="2.0.2" />
<plugin name="cordova-plugin-email" spec="1.2.7" />
<plugin name="cordova-plugin-facebook4" spec="6.4.0" />
<plugin name="cordova-plugin-geolocation" spec="4.1.0" />
<plugin name="cordova-plugin-globalization" spec="1.11.0" />
<plugin name="cordova-plugin-inappbrowser" spec="4.1.0" />
<plugin spec="https://github.com/chancezeus/cordova-plugin-jumbomode.git#0648cf1" />
<plugin spec="https://github.com/twogate/cordova-plugin-sign-in-with-apple#129866e" />
<plugin spec="https://github.com/prageeth/cordova-plugin-splashscreen.git#31ea5cf" />
<plugin name="cordova-plugin-statusbar" spec="2.4.3" />
<plugin name="cordova-plugin-whitelist" spec="1.3.4" />
<plugin spec="https://github.com/apache/cordova-plugin-wkwebview-engine#8735c46" />
<plugin name="cordova-plugin-x-socialsharing" spec="5.6.5" />
<plugin spec="https://github.com/chemerisuk/cordova-support-google-services.git#e4a57d2" />
<plugin spec="https://github.com/xale76/cordova-plugin-intel-xdk-cache.git#ceb626c" />
<plugin spec="https://github.com/xale76/cordova-plugin-intel-xdk-device.git#9674ae9" />
<plugin name="ionic-plugin-keyboard" spec="2.2.1" />
<plugin spec="https://github.com/jwall149/cordova-multidex.git#d2358b5" />
<plugin spec="https://github.com/xale76/phonegap-plugin-barcodescanner.git#f88c84a" />
<plugin name="pushwoosh-cordova-plugin" spec="7.18.11" />

Build by Phonegap site

## Checklist

- [ x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by breautek** [comment]
> a javascript runtime error is produced: Cannot read property 'getPicture' of undefined

Generally this kind of error occurs if you try to access the API before the `deviceready` event fires. Ensure that you only call plugin APIs after the `deviceready` event has fired.

> Build by Phonegap site

I would also strongly consider moving away from Phonegap technologies and use the cordova CLI instead. PhoneGap is no longer maintained. As of Oct 2020, Adobe has completely disabled their build services, so building via Phonegap is no longer possible. Additionally the Phonegap CLI doesn't allow you to use the latest cordova releases.

**Comment by Alessandro-PM** [comment]
hello I added 
document.addEventListener("deviceready", function(){ alert('ready');}, false);
in the head section of my index.html and after a build, this is the very first thing I see (the alert) when I open the app. So yes, I call the button after deviceready

**Comment by DavidGoricanec** [comment]
I am currently running into the same issue. I have set up an alert(navigator.camera); which is getting called on the deviceready-event and it always returns undefined. I've been trying to bugfix it all day but without success. I also tried adding/removing platforms and reinstalling the plugin but without success.

**Comment by whria78** [comment]
I have the same issue. "navigator.camera" returns null or undefined.

**Comment by Alessandro-PM** [comment]
perfect, nobody ca help us?

**Comment by whria78** [comment]
I found that camera works well on Monaca. I guess the problem may be related with the phonegap which is deprecated.

**Comment by Alessandro-PM** [comment]
mmm....I don't think this is the problem. Did you built the same project? anyway can I try to do the same? I mean, the same phonegap zip file could be built in monaca?

**Comment by timbru31** [comment]
Please reproduce the issue with actual Cordova tooling, not PhoneGap's outdated CLI, nor Monaco, VoltBuilder, ...

Otherwise we can't assist.

**Comment by jcesarmobile** [comment]
Latest version of the plugin requires cordova-android 9, so on cordova-android 8 it fails to install and it's not available
It's not a camera plugin bug, you just need to update your cordova-android version.

But since you use phonegap build, it won't allow you to use latest cordova-android, you should migrate to something else, it's officially abandoned, not sure why they still allow users to build apps from there, it was supposed to be shut down last October.

https://blog.phonegap.com/update-for-customers-using-phonegap-and-phonegap-build-cc701c77502c
