### ISSUE TITLE
No result with mediaType SAVEDPHOTOALBUM and enabled CameraUsesGeolocation (iOS)

### ISSUE THREAD

**Issue by sven-s** [apache/cordova-plugin-camera#702]
# Bug Report

## Problem

getPicture does not return an image when using mediaType SAVEDPHOTOALBUM with enabled CameraUsesGeolocation preference setting. 

### What is expected to happen?

When selecting an image from the camera roll and enabled CameraUsesGeolocation preference setting, the image should be returned from the plugin.

### What does actually happen?

The function returns a promise, which will never be completed.

## Information

When setting the CameraUsesGeolocation setting to false, the plugin works as expected, but I have an application, where the user is able to select both options.

### Environment, Platform, Device

Cordova 10.0.0
iOS Platform 6.1.1
iPhone OS 14.3

### Version information

Ionic 1.3.4
Xcode 12.3

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by codeconsole** [comment]
I have created a very easy to run example that demonstrates that EXIF information is lost:
https://github.com/codeconsole/exiftest

@ryaa I am unable to get your version of the plugin working with the latest version of cordova. 
```
% cordova --version
10.0.0
```

```
  git clone https://github.com/codeconsole/exiftest
  cd exiftest
  cordova prepare
  cordova run ios
```
Verify selecting an image works. In the simulator, click the Photo Library button, choose an image and then notice the image is shown and a popup comes up with some partial exif info.

Now to break everything then CameraUsesGeolocation to true in `config.xml` and run again. 
```
  ./setCameraUsesGeolocation.sh true
  cordova run ios
```
click the Photo Library button, choose a photo and notice nothing happens. Neither the success or error callbacks get executed for navigator.camera.getPicture()

Bonus points: 
Open the workspace in xcode 
open platforms/ios/HelloCordova.xcworkspace
and run the project

Notice the same behavior and the following message is shown in the console when nothing happens:

2021-02-21 16:55:30.974760-0800 HelloCordova[94981:4291237] [HelloCordova] copyThumbnail:301: *** skipping thumbnail -- too big [26417 bytes]

**Comment by codeconsole** [comment]
I have created a very easy to run example that demonstrates that EXIF information is lost:
https://github.com/codeconsole/exiftest

```
% cordova --version
10.0.0
```

```
  git clone https://github.com/codeconsole/exiftest
  cd exiftest
  cordova prepare
  cordova run ios
```
Verify selecting an image works. In the simulator, click the Photo Library button, choose an image and then notice the image is shown and a popup comes up with some partial exif info.

Now to break everything then CameraUsesGeolocation to true in `config.xml` and run again. 
```
  ./setCameraUsesGeolocation.sh true
  cordova run ios
```
click the Photo Library button, choose a photo and notice nothing happens. Neither the success or error callbacks get executed for navigator.camera.getPicture()

Bonus points: 
Open the workspace in xcode 
```
open platforms/ios/HelloCordova.xcworkspace
```
and run the project

Notice the same behavior and the following message is shown in the console when nothing happens:

```
2021-02-21 16:55:30.974760-0800 HelloCordova[94981:4291237] [HelloCordova] copyThumbnail:301: *** skipping thumbnail -- too big [26417 bytes]
```

**Comment by codeconsole** [comment]
I have created a very easy to run example that demonstrates the non working behavior:
https://github.com/codeconsole/exiftest

```
% cordova --version
10.0.0
```

```
  git clone https://github.com/codeconsole/exiftest
  cd exiftest
  cordova prepare
  cordova run ios
```
Verify selecting an image works. In the simulator, click the Photo Library button, choose an image and then notice the image is shown and a popup comes up with some partial exif info.

Now to break everything then CameraUsesGeolocation to true in `config.xml` and run again. 
```
  ./setCameraUsesGeolocation.sh true
  cordova run ios
```
click the Photo Library button, choose a photo and notice nothing happens. Neither the success or error callbacks get executed for navigator.camera.getPicture()

Bonus points: 
Open the workspace in xcode 
```
open platforms/ios/HelloCordova.xcworkspace
```
and run the project

Notice the same behavior and the following message is shown in the console when nothing happens:

```
2021-02-21 16:55:30.974760-0800 HelloCordova[94981:4291237] [HelloCordova] copyThumbnail:301: *** skipping thumbnail -- too big [26417 bytes]
```

**Comment by helenburns** [comment]
I can 100% agree with this. Commenting out that CameraUsesGeolocation preference is the difference between the photo being returned, or not, when picking from the library. Also, this is the behaviour I get when I have the source type set to either SAVEDPHOTOALBUM or PHOTOLIBRARY. It simply doesn't return anything, no error, no nothing.

In Xcode I can see the error `[core] "Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)"` whether it fails or not. I have all the appropriate privacy settings etc.

The only other thing to add, is that even though it works when using the camera, it does throw this up in Xcode when opening the camera: `[Camera] Failed to read exposureBiasesByMode dictionary: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL}` whether CameraUsesGeolocation is set to true or false or completely omitted. I don't know if that helps.

I REALLY need this to work. I can no longer retrieve EXIF data from gallery photos in my app and it's killing my users. Any suggestions welcome!

**Comment by bojanbizjak** [comment]
Same here.

Callback onSuccess is never called when using mediaType SAVEDPHOTOALBUM with enabled CameraUsesGeolocation preference setting.

Options:
```
{
                quality: 100,
                destinationType: Camera.DestinationType.FILE_URI,
                sourceType: Camera.PictureSourceType.SAVEDPHOTOALBUM,
                saveToPhotoAlbum: false,
                mediaType: Camera.MediaType.PICTURE
            }
```

Environment, Platform, Device
Cordova 10.0.0
iOS Platform 6.2.0
iPhone OS 14.4.1 (iPhone 7 Plus)
cordova-plugin-camera: 5.0.1,

Version information
Xcode 12.4

**Comment by codeconsole** [comment]
Have you tried installing the modified plugin?
cordova plugin add https://github.com/codeconsole/cordova-plugin-camera.git#ryaa

**Comment by bojanbizjak** [comment]
Unfortunately, https://github.com/codeconsole/cordova-plugin-camera.git#ryaa (cordova-plugin-camera 5.0.2-dev) doesn't work either. Callback onSuccess is never called.

**Comment by codeconsole** [comment]
you tried the ryaa branch (master is just the same as the fork)?

**Comment by ToddEllering** [comment]
Having the same issue with:
Cordova 10.0.0
iOS Platform 6.2.0
iPhone OS 14.6 (iPhone 7 Plus)
cordova-plugin-camera: 5.0.2

success callback is never called when sourceType is navigator.camera.PictureSourceType.SAVEDPHOTOALBUM

The image select comes up, and can pick an image, but then nothing. sourceType navigator.camera.DestinationType.FILE_URI works fine.

**Comment by erisu** [comment]
I am unable to reproduce this issue with the current master branch.

I will close out this issue as unreproducible.

If you are still experiencing the issue with master branch, please create a new ticket and:

1. create and link a simple reproduction repo.
2. provide additional steps, if necessary, to run the reproduction repo to see the issue.

### Code Sample:

**Simple JavaScript `index.js`**

```javascript
document.addEventListener('deviceready', onDeviceReady, false);

function onDeviceReady() {
  // encodingType: Camera.EncodingType.JPEG,
  const cameraOptions = {
    quality: 100,
    destinationType: Camera.DestinationType.FILE_URI,
    sourceType: Camera.PictureSourceType.SAVEDPHOTOALBUM,
    mediaType: Camera.MediaType.PICTURE,
    saveToPhotoAlbum: false
  }

  function onSuccess(result) {
    var image = document.getElementById('myImage');
    image.src = result;
  }

  function onFail(message) {
    alert('Failed because: ' + message);
  }

  document.getElementById('cameraTakePhoto').onclick = function() {
    navigator.camera.getPicture(onSuccess, onFail, cameraOptions);
  };
}
```

**iOS `config.xml` Snippet**

```xml
<platform name="ios">
    <preference name="CameraUsesGeolocation" value="true" />

    <edit-config target="NSCameraUsageDescription" file="*-Info.plist" mode="merge">
        <string>need camera access to take pictures</string>
    </edit-config>

    <edit-config target="NSPhotoLibraryUsageDescription" file="*-Info.plist" mode="merge">
        <string>need photo library access to get pictures from there</string>
    </edit-config>

    <edit-config target="NSLocationWhenInUseUsageDescription" file="*-Info.plist" mode="merge">
        <string>need location access to find things nearby</string>
    </edit-config>

    <edit-config target="NSPhotoLibraryAddUsageDescription" file="*-Info.plist" mode="merge">
        <string>need photo library access to save pictures there</string>
    </edit-config>
</platform>
```
