### ISSUE TITLE
Ionic cordova-plugin-camera crash the application after take picture

### ISSUE THREAD

**Issue by shalineemishra7284** [apache/cordova-plugin-camera#705]
Hi all, 
            I have an Ionic application that uses Cordova-plugin-camera: 4.1.0 version, In a Redmi with Android version 9x and MIUI version 11.0.3, it doesn't work. I can open the camera and click the picture but after that app crashes and restart the app.
   Please suggest a better solution to solve it.

**Comment by mateo2181** [comment]
This is a solution by @PieterVanPoyer that works for me. 

```
npx cordova plugin remove cordova-plugin-camera
npx cordova plugin add https://github.com/PieterVanPoyer/cordova-plugin-camera/#bugfix/issue-665-save-instance-restore-bug
```

**Comment by jcesarmobile** [comment]
latest version of the plugin is 5.0.1
