### ISSUE TITLE
[IOS] Could we get gif image from ios gallery? I try with this but always return jpg. 

### ISSUE THREAD

**Issue by ThangD** [apache/cordova-plugin-camera#708]

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).

**Comment by ThangD** [comment]
@timbru31 Thanks so much for your response. My question is this lib support for this? Dynamic image on ios always return jpg.
