### ISSUE TITLE
Android 10( some of devices) and 11 app getting crash not working camera , after changing android targetSdkVersion 28 to 29 

### ISSUE THREAD

**Issue by satheeshkumartitan** [apache/cordova-plugin-camera#716]
# Bug Report

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by alemit** [comment]
I'll try to add a little bit more information for this tickets based on observations from our users. Some of the devices have "Access denied" error when image is saved. We still cannot identify which devices are affected and which not but this is a blocker issue which affects very badly our users.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
