### ISSUE TITLE
Cordova+Vue 摄像头截流显示到UI界面上

### ISSUE THREAD

**Issue by hou18103912159** [apache/cordova-plugin-camera#719]
# Bug Report

## Problem
如何进行摄像头的截流操作，并将其展示到UI界面上？
### What is expected to happen?
想要做一个人脸识别页面，调取摄像头像canvas那样截流显示到app的界面上。

### What does actually happen?
实际没有办法去进行这样的操作，或许是我没有找到相应的方式方法。

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
Please use English and fill out the issue template.
