### ISSUE TITLE
When i take image from camera and upload on server some portion of image is seem grey

### ISSUE THREAD

**Issue by gtl-parth** [apache/cordova-plugin-camera#724]
# Bug Report
When i take image from camera and upload on server some portion of image is Appear as grey
## Problem
I have upload image throw camera plugin in cordova application some image part Appear as grey it is not capture actual image from camera and it happen some time in iOS device (iPad)

**Comment by PieterVanPoyer** [comment]
Please fill in the complete bug report form.

And provide us with more details. Add some screenshots or files, this report is not in a good shape to start working on.

**Comment by PieterVanPoyer** [comment]
Closing ticket due to lack of response, due to missing information and invalid bug report.
