### ISSUE TITLE
missing dependencies error in ionic 5

### ISSUE THREAD

**Issue by kennedyngigi4** [apache/cordova-plugin-camera#735]
Error: The target entry-point "@ionic-native/camera" has missing dependencies:

This is the error I get after installing the plugin in an Ionic project

Ionic 5
Using Cordova 9.1.0

How can I solve this?

**Comment by PieterVanPoyer** [comment]
Hey @kennedyngigi4 

Please fill in the complete issue form. This seems like an Ionic issue.
Because the package @ionic-native/camera is no Cordova package.

If the issue is reproducable in a plain Cordova app we can help. If it is an Ionic issue, please file an issue by Ionic.

Kind regards.
