### ISSUE TITLE
Camera fails to edit the image 

### ISSUE THREAD

**Issue by kennedyngigi4** [apache/cordova-plugin-camera#737]
While trying to crop images in an Ionic application I get the warning "Image edit is not supported" I have; 

1. allowEdit: true,
2. targetWidth: 300,
3. targetHeight: 500

After saving I do not get any output in terms of a base64 string.

**Comment by mharper6008** [comment]
Experiencing the same issue with allowEdit.  So far, have found Android 11 throwing the error, with other versions working, but have not yet fully completed testing.

**Comment by fcsteenkamp** [comment]
Experiencing the same with the below setup.

**Environment, Platform, Device**
Android 11
Cordova Android 9.1.0
cordova-plugin-camera 5.0.2

**Comment by breautek** [comment]
Closing as stale

Unclear the environment of the OP, but yes, editing images depends on support of the underlying camera app. Not all android devices have a camera app assigned that includes image editing/cropping functionality.
