### ISSUE TITLE
No image select

### ISSUE THREAD

**Issue by vietnux** [apache/cordova-plugin-camera#741]
My option:
```
quality: 50,
destinationType: Camera.DestinationType.DATA_URL,
 correctOrientation: true,
 allowEdit:true,
saveToPhotoAlbum:true
```
And when i edit image captured => error "No image selected"
It not save to my mobile
My phone using android 11

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
