### ISSUE TITLE
Android: FileURL returned by getPicture with sourceType photo album cannot be resolved

### ISSUE THREAD

**Issue by dominic-simplan** [apache/cordova-plugin-camera#746]
# Bug Report

### What is expected to happen?
Calling `camera.getPicture()` with options
```
getPicture({
   sourceType: Camera.PictureSourceType.SAVEDPHOTOALBUM,
   destinationType: Camera.DestinationType.FILE_URI,
}
```
should return a fileURL which can be processed with `window.resolveLocalFileSystemURL()`

### What does actually happen?
If I select an image from my photo gallery, getPicture returns "`/storage/emulated/0/DCIM/Camera/PXL_xyz.jpg`".
When I try to resolve this URL with `window.resolveLocalFileSystemURL`, I get `FileError {code: 5}`.

Only files which [are modified by the plugin](https://github.com/apache/cordova-plugin-camera/blob/d356030070d903a929b7fb2adae7b9b53ab3dc7a/src/android/CameraLauncher.java#L759) seem to work. For example, if I select a png file but the (default) encodingType is set to JPEG, I get the following URL: "`file:///data/user/0/de.appname/cache/Screenshot_20210607-075901.png?1626272750921`". This can be resolved correctly.

## Information

Already tried adding the following to my config.xml but nothing changed:
```
<edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
      <application android:requestLegacyExternalStorage="true" />
</edit-config>
```

### Environment, Platform, Device
Google Pixel 4a
Android 11

### Version information
Cordova CLI 10.0.0
cordova-android: 9.0.0
cordova-plugin-camera: 5.0.1
cordova-plugin-file: 6.0.2

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by bjdose** [comment]
Same problem here. I've been trying to fix it without success.

**Comment by skout90** [comment]
+1 same problem

**Comment by robman70** [comment]
Same problem here. No solution?

**Comment by rtherry** [comment]
+ Same problem here. With the latest Cordova stack 12.0.0 cordova-plugin-camera 7.0.0
