### ISSUE TITLE
MAJOR BUG - Camera - App crashes randomly on Android devices

### ISSUE THREAD

**Issue by Aarbel** [apache/cordova-plugin-camera#753]
Cf https://github.com/apache/cordova-plugin-camera/issues/665

This issue should be opened back, the crash still happens on most of our clients devices. Can we help you in any way ? Pay you to have a quick fix ?

**Comment by timbru31** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

And let's stick to the original issue - if you have MRE for us, we are happy to re-open the issue.

**Comment by Aarbel** [comment]
@jgoux i think we should create one

**Comment by Aarbel** [comment]
@timbru31 instead of closing these issues, can you help us to reproduce the crash ?

Camera is hard to test with desktop emulators, because there's no hardware camera on emulated device. What would be your ideas about it ? Is there a way to simulate hardware camera with desktop computer camera ?

- Among all existing issues, the crash seems to occur for devices with a bad CPU / RAM limitations / Camera resolution ratios.
Looks also that different brands manage differently the "limits" of the device. 
- A basic Re-boot also seems to remove the crash for many devices (but some devices have every time the crash).

=> So to reproduce the error, we should also simulate heavy resolution pictures taken by cameras, and different devices brands.

Thanks for your help !
