### ISSUE TITLE
App Restart when capture image from camera

### ISSUE THREAD

**Issue by vijayvagdiya** [apache/cordova-plugin-camera#755]
# Bug Report

## Problem
Steps :

1. Click on camera button in app then camera open 
2. Take picture front/back picture display 
3. Selection option cancel or OK then I have click OK
4. App restart (means app open from start page with splash screen) 

`
   
    const options: CameraOptions = {
      quality: 100,
      destinationType: this.camera.DestinationType.FILE_URI,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE
    }
    
    this.camera.getPicture(options).then((imageData) => {
      console.log("imageData ===> ",imageData);
     // imageData is either a base64 encoded string or a file URI
     // If it's base64 (DATA_URL):
     let base64Image = 'data:image/jpeg;base64,' + imageData;
    }, (err) => {
      console.log("errr",err);
      this.utilServices.openForSuccessError({ value: false, message1: err});
      
     // Handle error
    });`
### What is expected to happen?

App does not restart and get picture file/base64 return in logs

### What does actually happen?

But app Restart when capture image from camera 

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
> Android uses intents to launch the camera activity on the device to capture images, and on phones with low memory, the Cordova activity may be killed. In this scenario, the result from the plugin call will be delivered via the resume event. See the Android Lifecycle guide for more information. The pendingResult.result value will contain the value that would be passed to the callbacks (either the URI/URL or an error message). Check the pendingResult.pluginStatus to determine whether or not the call was successful.

https://github.com/apache/cordova-plugin-camera#android-quirks

Based on the information provided, this is most likely what you're running into. For the splashscreen, you may have to turn on [SplashShowOnlyFirstTime](https://github.com/apache/cordova-plugin-splashscreen#android-quirks) preference, if you don't want the splashscreen to appear on every launch.

This is an android activity thing that android developers generally have to work with. Unfortunately Cordova cannot solve this quirk. Therefore, closing as won't fix.

**Comment by vijayvagdiya** [comment]
Sorry, I guess I wasn't much clear about the issue in my original bug reporting. Please check below two notes:
1. My android version 11 [I am testing this code in android 11(MI device) and android 10(Motorola) devices]
2. All the permissions of camera access is 100% set.
3. The issue doesn't come in Android 10.
4. The issues comes in just Android 11.
So this has something to do with newer version of the Android because it already works with lower versions.
If there was an issue with Cordova or low memory phones, it should be occurring in Android 10 too.

**Comment by martin-dufka** [comment]
Try cordova-plugin-background-mode plugin to prevent garbage your app after switching to camera app
