### ISSUE TITLE
navigator.camera undefined when using cordova-android@10.1.0

### ISSUE THREAD

**Issue by noahcooper** [apache/cordova-plugin-camera#757]
If I install this plugin from npm, `navigator.camera` is undefined. If I install the plugin using https://github.com/apache/cordova-plugin-camera.git instead of npm, `navigator.camera` is defined as expected. This appears to be because of the `cordovaDependencies` defined in package.json.

Is cordova-android 10 supported, or do I need to wait for 6.0.0 to be released? (The comments in https://github.com/apache/cordova-plugin-camera/issues/756 seem to suggest this plugin is expected to work with cordova-android 10.)

**Comment by breautek** [comment]
> Is cordova-android 10 supported, or do I need to wait for 6.0.0 to be released?

cordova-android@10 is only officially supported in 6.0.0 (currently unreleased).

You can **probably** get away with using cordova-android@10 with camera 5.x by pinning the camera version to `5.0.2`, and use the [cordova-plugin-androidx-adapter](https://www.npmjs.com/package/cordova-plugin-androidx-adapter) but:
1. cordova-android@10 targets API 29 by default and there are other changes necessary to make the camera plugin work properly on API >= 29. So mileage may vary.

In general, the Apache community decided that telling users to install an external plugin to make Apache maintained plugins work is unacceptable. Additionally, the community also decided that it would be bad practice to include the androidx adapter automatically as it scans and modifies sources on-the-fly. Due to these reasons, we have no choice but to implement a breaking change and force the upcoming release to require cordova-android@10.

**Comment by noahcooper** [comment]
Thanks @breautek. I've already implemented the workaround to make API 30 work, and already include `cordova-plugin-androidx-adapter`. I was trying to upgrade so that I could remove the `<intent>`s from my config.xml, but I'll just hold off until 6.0.0 is released. 

FWIW - I think it would've made more sense to leave 5.0.0 as depending on cordova >=9.0.0. Unless I'm missing something, 5.0.3 doesn't actually _require_ 10.0.0.

**Comment by breautek** [comment]
Cordova package is irrelevant here. 5.0.3 adds a restriction so it won't be installed on cordova-android@10 or later.

In otherwords, 5.0.3 supports cordova-android@9, but not 10.

The upcoming 6.x release will support cordova-android@10.

**Comment by noahcooper** [comment]
@breautek I understand that. The problem is that for any app that didn't have 5.0.2 pinned, and instead had something like `~5.0.0`, version 5.0.3 gets installed and fails somewhat silently. It doesn't seem like such a dependency change should've been introduced in a patch release for just that reason. It also seems like it would've made more sense to wait until 6.0.0 was released to change the dependency for 5.0.3 to cordova-android<10.0.0.

**Comment by erisu** [comment]
5.x by default supports only Android Support Library. So we locked the 5.x versions to 9.x and below.

Eventhough you could use the androidx adapter plugin to get around the library issues. We do not maintain that plugin and should not require it or tell users to use it always.

Once 10.x releases with AndroidX, that means all plugins would break anyways.

**Comment by noahcooper** [comment]
@erisu I totally get it, my only point was that 5.0.3 perhaps should've actually been 5.1.0, which would've prevented apps from breaking for anyone using `~5.0.0`. (Of course I suppose then people with `^5.0.0` would've been complaining.)

Anyway, thank you for maintaining an open source project! I'll look forward to using 6.0.0. :)

**Comment by SimonBrazell** [comment]
> I've already implemented the workaround to make API 30 work

@noahcooper would you mind pointing me in the direction of this workaround? Having some troubles building an app to target API 30 today. 🙂

I've installed `cordova-plugin-androidx-adapter` and `cordova-plugin-camera@5.0.2`.

**Comment by noahcooper** [comment]
@SimonBrazell I have this in my config.xml:

```
<custom-config-file target="AndroidManifest.xml" parent="/*">
      <queries>
        <intent>
          <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
        <intent>
          <action android:name="android.intent.action.GET_CONTENT" />
        </intent>
      </queries>
    </custom-config-file>
```

(I use `cordova-custom-config` in my config for some other reasons, but I believe you could actually use `<edit-config>` if you wanted to.)

**Comment by SimonBrazell** [comment]
Thanks heaps @noahcooper! I'll give that a try now. 

Cheers!

**Comment by sirbarkley** [comment]
> <custom-config-file target="AndroidManifest.xml" parent="/*">
>   <queries>
>     <intent>
>       <action android:name="android.media.action.IMAGE_CAPTURE" />
>     </intent>
>     <intent>
>       <action android:name="android.intent.action.GET_CONTENT" />
>     </intent>
>   </queries>
> </custom-config-file>

When I put this in config.xml I'can't build the apk. I get this:
![image](https://user-images.githubusercontent.com/22507199/130304020-f164d554-e77c-4596-bfe7-8b6c83660db8.png)

Any ideas?

**Comment by SimonBrazell** [comment]
@sirbarkley I get the same, wasn't able to resolve it, the project built with API 30 as the target without it though, but I'm sure there will be issues in the build.

**Comment by noahcooper** [comment]
@sirbarkley do you have `xmlns:android="http://schemas.android.com/apk/res/android"` on the `<widget>` element in your config file?

**Comment by sirbarkley** [comment]
> @sirbarkley do you have `xmlns:android="http://schemas.android.com/apk/res/android"` on the `<widget>` element in your config file?

That was it. Thank you very much!

**Comment by toufiqpathan** [comment]
Hi @sirbarkley still i am facing same issue, you found any solution?

**Comment by sirbarkley** [comment]
> Hi @sirbarkley still i am facing same issue, you found any solution?

Hi,  noahcooper's answer was the solution for me: do you have `xmlns:android="http://schemas.android.com/apk/res/android" `on the `<widget>` element in your `config.xml` file?
