### ISSUE TITLE
Camera doesn't have bottom menu when opened from Cordova

### ISSUE THREAD

**Issue by cmarian5** [apache/cordova-plugin-camera#767]
I am building an Android application using Cordova and cordova-plugin-camera.
From what I understand, this plugin will trigger native Camera of Android and will allow to make a photo that later can be used in Cordova app.

The problem that I have is that when camera is opened by Cordova, I am missing the other options that I have in native camera (night-vision, HDR, etc).

Here you can see what I mean:

This is how camera looks when I opened it from Android (notice "mai multe" button)
https://i.imgur.com/FiH7gTi.png

And this is how camera looks when is opened by Cordova:

https://i.imgur.com/cCuzHve.png

You can notice that the bottom menu is no longer there. 

Can we do something to have this menu in Cordova? Because we want to take photos using different modes.

**Comment by jcesarmobile** [comment]
The plugin just launches an intent to the camera app, if the camera app shows different buttons based on it it was open from the camera app icon or from an intent is not something we can control.
