### ISSUE TITLE
ionic android 11 camera not opening

### ISSUE THREAD

**Issue by bjornlain2** [apache/cordova-plugin-camera#777]
So i've got the same problem as here : https://github.com/apache/cordova-plugin-camera/issues/673?fbclid=IwAR3lUhLMFsonYvXSqjphQys9-ilUgbEfVLOJ7J3joB5iykeRjiuXJyESWgA

On there is says that you need to add this code , but i think it is only for Android studio or something, if i try to put like that
in the config.xml of Ionic it wont build the app and gives errors. 

`<config-file parent="/*" target="AndroidManifest.xml">
    <queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
        <intent>
            <action android:name="android.intent.action.GET_CONTENT" />
        </intent>
    </queries>
</config-file>`

What i do have is an 'edit-config'  and i tried to put it in like this, it builds but still doesn't fix the issue : 

`     <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
            <application android:networkSecurityConfig="@xml/network_security_config" />
            <queries>
                <intent>
                    <action android:name="android.media.action.IMAGE_CAPTURE" />
                </intent>
                <intent>
                    <action android:name="android.intent.action.GET_CONTENT" />
                </intent>
                <intent>
                    <action android:name="android.intent.action.PICK" />
                </intent>
            </queries>
        </edit-config>`

So this is actually a disaster because 15 big companies use my application and its really bad if they can't take pictures on Android.
Its very important in the app . It is also already uploaded on the playstore so i need to fix it really fast.

Please someone help me :)
![afbeelding_2021-11-15_122801](https://user-images.githubusercontent.com/94365201/141774393-ba644e2a-132d-4473-827e-8bbb90cdac9f.png)

## Checklist

- [ x] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by bjornlain2** [comment]
I finally was able to fix it with by adding :  xmlns:android="http://schemas.android.com/apk/res/android"

So you have to add this to your config.xml : 

`<config-file parent="/*" target="AndroidManifest.xml" xmlns:android="http://schemas.android.com/apk/res/android">
            <queries>
                <intent>
                    <action android:name="android.media.action.IMAGE_CAPTURE" />
                </intent>
                <intent>
                    <action android:name="android.intent.action.GET_CONTENT" />
                </intent>
            </queries>
        </config-file>`

**Comment by thiagoroc** [comment]
T

> I finally was able to fix it with by adding : xmlns:android="http://schemas.android.com/apk/res/android"
> 
> So you have to add this to your config.xml :
> 
> `<config-file parent="/*" target="AndroidManifest.xml" xmlns:android="http://schemas.android.com/apk/res/android"> <queries> <intent> <action android:name="android.media.action.IMAGE_CAPTURE" /> </intent> <intent> <action android:name="android.intent.action.GET_CONTENT" /> </intent> </queries> </config-file>`

Thanks! This was the solution for my case!!!

**Comment by SidiBecker** [comment]
Thanks @bjornlain2! Saved my life

**Comment by kevindanielr** [comment]
Thanks for the help, I've been trying this and it hasn't worked for me. In the browser console it does not show me any error message when opening the camera or the gallery.

I would really appreciate your help.

![image](https://user-images.githubusercontent.com/43509405/145860700-b76063b6-846d-4580-ad29-8e9dd345b058.png)

**Comment by bjornlain2** [comment]
If you use pick you should include it

**Comment by SidiBecker** [comment]
Hello @kevindanielr, try this:

![image](https://user-images.githubusercontent.com/40251890/145869562-b8eb58d0-590d-4bec-ae31-6f8fff3125aa.png)

**Comment by kevindanielr** [comment]
If I try this way this happens:

> 
![image](https://user-images.githubusercontent.com/43509405/145873469-1d363e8c-8b6a-4716-a87c-5f0d365c48c9.png)

**Comment by kevindanielr** [comment]
> If you use pick you should include it

Could you explain to me what you mean by that?

**Comment by SidiBecker** [comment]
> If I try this way this happens:
> 
> > 
> 
> ![image](https://user-images.githubusercontent.com/43509405/145873469-1d363e8c-8b6a-4716-a87c-5f0d365c48c9.png)

You are removing and adding the android platform?

**Comment by kevindanielr** [comment]
No, I did not delete the platform. I'm trying this way and I still don't get an error message when I try to use the camera

![image](https://user-images.githubusercontent.com/43509405/145874819-b1ae1d97-7e2e-433d-bb79-91de73dccf56.png)

**Comment by SidiBecker** [comment]
Try putting `queries` on a separate config, like my screenshot above.

`<edit-config file="AndroidManifest.xml" mode="override" target="/manifest">
<queries>...`

**Comment by kevindanielr** [comment]
> Try putting `queries` on a separate config, like my screenshot above.
> 
> `<edit-config file="AndroidManifest.xml" mode="override" target="/manifest"> <queries>...`
> 
> And re-add the platform



I have tried to put the queries in the way you mentioned to me, I removed the platform and added it again.

If I remove this: xmlns: android = "http://schemas.android.com/apk/res/android"

![image](https://user-images.githubusercontent.com/43509405/145880111-ea1fb5e3-a852-40cc-ba8e-39750d0d86c8.png)

If I add again, if I can do the build and the camera still does not work

**Comment by phusting** [comment]
> I finally was able to fix it with by adding : xmlns:android="http://schemas.android.com/apk/res/android"
> 
> So you have to add this to your config.xml :
> 
> `<config-file parent="/*" target="AndroidManifest.xml" xmlns:android="http://schemas.android.com/apk/res/android"> <queries> <intent> <action android:name="android.media.action.IMAGE_CAPTURE" /> </intent> <intent> <action android:name="android.intent.action.GET_CONTENT" /> </intent> </queries> </config-file>`

THANK YOU SO MUCH!!!!!

**Comment by IllusionVK** [comment]
Hey @bjornlain2 do you think you could submit a pull request to update read me file so its in official documentation ?

**Comment by scamposd** [comment]
installing cordova "cordova-plugin-camera": "^6.0.0", didn't work for us either.

Ionic:

   Ionic CLI                     : 6.13.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.9.3
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 13 other plugins)

Utility:

   cordova-res (update available: 0.15.4) : 0.15.2
   native-run (update available: 1.6.0)   : 1.2.2

System:

   ios-deploy : 1.11.3
   ios-sim    : 8.0.2
   NodeJS     : v12.14.1 (/usr/local/bin/node)
   npm        : 6.13.4
   OS         : macOS
   Xcode      : Xcode 13.4.1 Build version 13F100
