### ISSUE TITLE
Get the width and height of the captured image

### ISSUE THREAD

**Issue by tiagocaus** [apache/cordova-plugin-camera#782]
How do I get the width and height of the captured image, inside 

```
function onSuccess(imageData) {

}
```

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
