### ISSUE TITLE
Xiaomi Redmi 7A camera crash

### ISSUE THREAD

**Issue by amanfreda** [apache/cordova-plugin-camera#784]
# Bug Report

## Problem
I am looking for help, with a camera crashing problem on an Xiaomi Redmi 7A mobile device.

### What is expected to happen?
In my Cordova application ([https://github.com/amanfreda/cordova-camera-debug](https://github.com/amanfreda/cordova-camera-debug)), I want to utilize the camera. I tried using this plugin to achieve that. The app is just a simple button, that should return the image uri.

### What does actually happen?
It works fine on most devices, except on Xiaomi Redmi 7A. On this specific device, the application crashes at the moment the camera is opened and the picture is taken (as seen in the logs). Then, when the plugin wants to return the image data to the application, the application restarts and the image data is lost. After some googling, the issue seems to be, that Xiaomi's MIUI OS is pretty aggressive with killing background processes.

### Solutions I Tried
- Set the applications battery settings to "No restrictions", and lock the application, so it should stay running in the background. Somthing like https://dontkillmyapp.com/xiaomi
- Use cordova-plugin-background-mode (https://bitbucket.org/TheBosZ/cordova-plugin-run-in-background) to force my application, to run in the backround. I also tried running it with disableBatteryOptimizations and disableWebViewOptimizations.

Both obvously didn't work. This is as far as I got, before I was out of ideas. The github link to the application includes the sample application (nothing fancy, just a button that opens the camera with the plugin), and also some logcat logs in the log folder. The logcat logs contain a verbose output of all the logs, application logs, chromium logs and adb bugreport. The chrome://inspect console is not much use in this case, because no errors were logged.

So, if anyone came across similar issues I would be grateful for any sort of info that could be provided.

### Command or Code
Install the app listed above with: 
```
npm i
cordova platform add android
cordova run android
```
Feel free to bump the cordova and plugin versions (I tried with cordova 10 and cordova-plugin-camera 6, but the problem persists). The versions listed are just the ones I use in my production app.  

### Environment, Platform, Device
**Device:** Xiaomi Redmi 7A, 2GB RAM 16GB ROM, MIUI 12.5.3
**Platform:** Android 10

### Version information
**Nodejs:** 10.24.1
**Application Framework:** Cordova 9.0.0
**Plugins:** cordova-plugin-camera 5.0.3, cordova-plugin-background-mode

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by phyr0s** [comment]
I tried also with cordova cli 11 and lastest versions of cordova-android and camera plugin and still same

**Comment by whria78** [comment]
If we can't solve the problems of the camera plugin right away, it would be very helpful to have a list of devices with the problem.

**Comment by mobiliseapplabllp** [comment]
Same issue with Android 
Device Name: Redmi Note 7 pro
MIUI Version 12.5.1
