### ISSUE TITLE
[ANDROID 11] Camera plugin crashes app after image is taken

### ISSUE THREAD

**Issue by sbellver** [apache/cordova-plugin-camera#785]
# Bug Report

## Problem

In Android 11 phones, after taking photo o selected it from gallery, app closes; however, file is uploaded ok to the server and notify correctly "Your photo is uploaded".

Then, after few seconds, app close it self with toast

### What is expected to happen?

- Select a photo from gallery or take photo
- Save photo
- App still working as expected

### What does actually happen?

- Select a photo from gallery or take photo
- Save photo
- App crashes after few seconds

## Information
It only happens into Android 11 devices.
Tested into Android 7 and iOs and works fine

### Environment, Platform, Device
Android 11

### Version information
MacOs
ionic v1
ionic cli
Cordova 10.0.0 / 11.0.0.0
Cordova-android 10.0.0 / 10.1.1
Cordova-plugin-camera 6.0.0
FileTransfer (latest, from git repo, recently updated)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by sbellver** [comment]
Trying cordova-plugin-background-mode plugin and same result

**Comment by thiagoroc** [comment]
> Trying cordova-plugin-background-mode plugin and same result

I still have problems even with cordova-plugin-background-mode

**Comment by lucasrleandro** [comment]
Im also facing this problem

**Comment by skyttedk** [comment]
I also experience this problem on android 9.1, Getting this error message:

> 02-01 09:27:00.893 E/AndroidRuntime(15931): Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=33, result=-1, data=null} to activity {com.phonegap.gsv/com.phonegap.gsv.MainActivity}: java.lang.NullPointerException: filename cannot be null

**Comment by sbellver** [comment]
No way.

Try allowEdit: false, change processResultFromCamera function on CamaeraLauncher.java (seems imageFilePath give null data)

https://github.com/apache/cordova-plugin-camera/issues/718#issuecomment-864517005

https://stackoverflow.com/questions/65844036/ionic-cordova-plugin-camera-crash-the-application-after-take-picture

https://stackoverflow.com/questions/17083255/cordova-phonegap-crashes-after-taking-a-picture-with-camera-getpicture

But nothing solves it

**Comment by sbellver** [comment]
More debug results.

It only happens with DestinationType.FILE_URI; with DestinationType.DATA_URL works well.

But Base64 sometimes close the app if terminal have low RAM :'(

**Comment by sbellver** [comment]
well, I think is related about FileTransfer plugin, not Camera plugin.

If I dont use a FT upload, it works (dont close)

**Comment by sbellver** [comment]
Finally, it's from toast plugin!

https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin/commit/4399bed9e1ccda46a71609abad17e3c3cc068c82

After update it, I have no problems

**Comment by MdBahaul007** [comment]
I am not using toast plugin anywhere in my project but still facing the crash issue in some devices
