### ISSUE TITLE
Android 11 Go - camera doesn't open

### ISSUE THREAD

**Issue by schindler-nuuway** [apache/cordova-plugin-camera#786]
Camera does not open on "Android 11 Go" devices. There is no error message, not even in the console. On devices with "normal Android 11" the camera works normally as expected.
Other plugins have no issue with the camera: the barcode-scanner, for example, starts the camera without any problems. So it does not seem to be due to permissions.

Cordova Platform: android 10.1.1
Plugin: cordova-plugin-camera 6.0.0

Is this behaviour known or does anyone have an idea what could be causing it?

**Comment by schindler-nuuway** [comment]
I'm sorry, my mistake: they are managed devices and special permission was needed for the camera.... still strange that the barcode scanner worked anyway.

**Comment by martinarlando** [comment]
Hello @schindler-nuuway, I got this issue as well. What do you mean with special permission?
