### ISSUE TITLE
Image picker on redmi note 10S android 11

### ISSUE THREAD

**Issue by jhautot** [apache/cordova-plugin-camera#787]
Hello,
I'm using this plugin successfully to pick images from the gallery. Usually I get something that displays only images and with a "recent" menu to show recent images.
On my redmi note 10S android 11, I get a directory browser working but not convenient at all to use.
Is there something that can be done to get more something like a gallery display ?

Thank you
![Screenshot_2022-02-12-22-17-00-162_com mi android globalFileexplorer](https://user-images.githubusercontent.com/24245993/153729030-25ffd297-e37e-431b-8684-8b8ce630e067.jpg)

**Comment by jcesarmobile** [comment]
The plugin uses an intent, which means any app that declares that intent can be opened. It usually ask you to choose one if more than one app implements that intent, but if you only have one it will be used without prompting, which looks like your case.
There is nothing we can do.
Users can install other gallery apps such as google photos.

**Comment by jhautot** [comment]
> The plugin uses an intent, which means any app that declares that intent can be opened. It usually ask you to choose one if more than one app implements that intent, but if you only have one it will be used without prompting, which looks like your case. There is nothing we can do. Users can install other gallery apps such as google photos.

Thank you for your answer.
I never had any prompt asking me to choose an app. Usually it opens gallery app. On my phone I have also google photo app but it opens directly this directory browser app.

Is it possible I missed something  that prevents the prompt to show to select the app ?
