### ISSUE TITLE
camera plugin is not working in ionic 5 using capacitor 

### ISSUE THREAD

**Issue by sudeshgoyat20** [apache/cordova-plugin-camera#789]
i installed the plugin and checked the build in ios device , when i open the camera it crashes the app

**Comment by jcesarmobile** [comment]
you have to add the usage descriptions, in Capacitor you can't use the edit-config tag as[ this sections ](https://github.com/apache/cordova-plugin-camera#ios-quirks)documents, you have to edit the Info.plist manually and add those entries
