### ISSUE TITLE
Camera return 20 , after implementing smallcase plugin (Ionic 6)

### ISSUE THREAD

**Issue by jagatb880** [apache/cordova-plugin-camera#794]
I am getting error in camera while taking photo. (gallery is working fine). It throws 20 as a error.
 

I am implemented below plugin:

    "com.scgateway.phonegap": "git+https://github.com/smallcase/gw-mob-sdk-cordova.git",
    
    if I delete this plugin the camera is working fine , but when i add the camera take photo not working .
    

    I am using below camera plugins:

    "@awesome-cordova-plugins/camera": "^5.43.0",
    
    "cordova-plugin-camera": "^6.0.0",
    
    "cordova-plugin-camera": {
        "ANDROIDX_CORE_VERSION": "1.6.+"
      }

**Comment by breautek** [comment]
Error code 20 is a permission error.

`gw-mob-sdk-cordova` declares the `CAMERA` permission. The camera permission isn't required for this plugin but does introduce some caveats.

Camera permission is to use the camera APIs programmatically, which this plugin does not do, as this plugin offloads the responsibility to the device's camera app. However, if the application has the `CAMERA` permission declared, then the app must have the `CAMERA` permission granted, even if you're using intents like this plugin does.

This plugin will attempt to request the camera permission if it's declared in the manifest, but if you have previously denied permission, the OS may remember that choice and auto reject the permission grant.

I would advise to double check your permission grants in the app settings.

**Comment by SaurabhSalunkeGT** [comment]
i have same issue i have given permissions also

**Comment by SaurabhSalunkeGT** [comment]
still my camera doesnt working only for android 13

**Comment by brunoalex** [comment]
any update ?

**Comment by sagarnkakad** [comment]
any update? any one found at least work around

**Comment by hiteshbasware** [comment]
> still my camera doesnt working only for android 13

Permissions have been updated for Android13 so the names and related checks needs to be updated in cordova plugins java files. This is resolved in #840 

This needs to be merged into master, we are waiting for that till then if you want you can use this using direct git link in package.json

**Comment by breautek** [comment]
Should be fixed by https://github.com/apache/cordova-plugin-camera/pull/844
