### ISSUE TITLE
#ionic 3 camera crash after asking for permission. 

### ISSUE THREAD

**Issue by ashilanazeer1** [apache/cordova-plugin-camera#795]
#ionic 3 camera crash after asking for permission

I am using cordova 8.1.2.   The camera is working when I Change: this.applicationId = (String) BuildHelper.getBuildConfigValue(cordova.getActivity(), "APPLICATION_ID"); To: this.applicationId = cordova.getContext().getPackageName();  Please commet if there is another solution for this.

**Comment by jcesarmobile** [comment]
Can you provide a sample app?

**Comment by jcesarmobile** [comment]
closing sinde there was no response, probably fixed by https://github.com/apache/cordova-plugin-camera/pull/827
