### ISSUE TITLE
Apple complains about this message 

### ISSUE THREAD

**Issue by MustafaSarhan** [apache/cordova-plugin-camera#802]
Apple rejected my App due to this permission message. while I had no option to change it dynamically and got to change it manually in this file

https://github.com/apache/cordova-plugin-camera/blob/4608f8ef8027a5c7130a3479c2d37a5e391c70e8/src/ios/CDVCamera.m#L167

However, Apple reviewer/tester provided me this link [appropiate permission requests](https://developer.apple.com/design/human-interface-guidelines/patterns/accessing-private-data/)

I think it's the time to change this message or even to cancel it and trigger an error to let the apps developers customize their message.

**Comment by breautek** [comment]
I agree, Cordova shouldn't be making an assumption here.

For the time being, a workaround for you would likely to fork the plugin and change the text to something that is a bit more in context within your app, which sounds like is what you've already done. Apple doesn't like generic messages for permissions.

**Comment by jcesarmobile** [comment]
This is not a permission request, is an error shown when the permission was rejected, but you should have requested it first. 
The link you provided is about requesting the permissions.
Can you share a screenshot of Apple's message?

**Comment by jcesarmobile** [comment]
closing since the requested information was not provided

The message is a `NSLocalizedString`, which means it can be localized (and even replaced) using strings files 
https://developer.apple.com/documentation/foundation/nslocalizedstring
