### ISSUE TITLE
Application is Crash when take picture from camera

### ISSUE THREAD

**Issue by mobiliseapplabllp** [apache/cordova-plugin-camera#803]
# Bug Report

## Problem
Application is crashed when take picture from camera

### What is expected to happen?
when picture is taken then image file_url show

### What does actually happen?
Application is crahsed and restart automatically

## Information
When select image from gallery it working fine

### Command or Code

 photoOption(src, val) {
    const options: CameraOptions = {
      quality: 60,
      destinationType: this.camera.DestinationType.FILE_URI,
      encodingType: this.camera.EncodingType.JPEG,
      mediaType: this.camera.MediaType.PICTURE,
      sourceType: src,
      correctOrientation: true
    };

    this.camera.getPicture(options).then((imageData) => {
      this.convertImageToFile(imageData, val);
    }, (err) => {
      alert(JSON.stringify(err));
    });
  }

### Environment, Platform, Device

Android one plus nord 5

### Version information
Ionic:

   Ionic CLI                     : 6.19.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 19 other plugins)

Utility:

   cordova-res (update available: 0.15.4) : 0.11.0
   native-run (update available: 1.6.0)   : 1.5.0

System:

   Android SDK Tools : 26.1.1 (/Users/apple/Library/Android/sdk/)
   ios-sim           : 8.0.2
   NodeJS            : v14.17.0 (/usr/local/bin/node)
   npm               : 8.3.0
   OS                : macOS Monterey
   Xcode             : Xcode 13.4.1 Build version 13F100

**Comment by jcesarmobile** [comment]
What’s the crash error message?
What’s the android version of the device?
Can you provide a sample app?

**Comment by mac89** [comment]
Presumably the same issue as #679

**Comment by jcesarmobile** [comment]
closing since there was no response and looks like a duplicate of #679
