### ISSUE TITLE
Application crash when take picture from camera and accept this image

### ISSUE THREAD

**Issue by marina31714** [apache/cordova-plugin-camera#806]
# Bug Report

## Problem

When I take a picture with the tablet and accept, the application crashes.

### What is expected to happen?

The image is successfully added and the alert is displayed. 

### What does actually happen?

The application is crashed.

## Information

When select image from gallery it working fine
When change option to allowEdit to true, no crashes but showed this alert: You can't edit this image.

### Command or Code

`function setOptions(srcType) {
                var options = {
                    // Some common settings are 20, 50, and 100
                    quality: 75,
                    destinationType: Camera.DestinationType.FILE_URI,
                    // In this app, dynamically set the picture source, Camera or photo gallery
                    sourceType: srcType,
                    encodingType: Camera.EncodingType.JPEG,
                    mediaType: Camera.MediaType.PICTURE,
                    allowEdit: false,
                    correctOrientation: true
                }
                return options;
            }`

                        var srcType = Camera.PictureSourceType.CAMERA;
                        var options = setOptions(srcType);

                        navigator.camera.getPicture(function cameraSuccess(imageUri) {

                            alert("get picture");

                        }, function cameraError(error) {
                            console.debug("Unable to obtain picture: " + error, "app");

                        }, options);

### Environment, Platform, Device

Lenovo tab m10 hd 
Android: 11

### Version information

Cordova 11.0.0
Cordova platform: Android 10.1.2
Cordova plugins: 
![image](https://user-images.githubusercontent.com/47326565/190383961-f4f32c1a-1018-443f-93fd-b1ec823e745b.png)

Android studio: 2021.1
Android sdk-tools: 
![image](https://user-images.githubusercontent.com/47326565/190384634-6015b27d-89b3-47fb-af39-5cb7e1de2a2a.png)
Java Jdk:
![image](https://user-images.githubusercontent.com/47326565/190384698-3e9d049e-689f-4389-bc40-b8be9facb4c0.png)
Gradle: 
![image](https://user-images.githubusercontent.com/47326565/190384735-9e7e5f8d-ca3d-416e-9c32-290bf510705f.png)

Operating System: Windows 10 Home

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by FZampetti** [comment]
I have the same issue, have you solved it?

**Comment by marina31714** [comment]
Hi @FZampetti,
I change the plugin. Now I use https://github.com/apache/cordova-plugin-media-capture.
I hope this helps to you.

**Comment by mac89** [comment]
Presumably the same issue as #679

**Comment by Trilvid** [comment]
have something similar, any recommended solution

**Comment by breautek** [comment]
Closing as stale.

If the "crash" involves the webview restarting, then it isn't a crash. It's the android activity that got killed while the camera is operating, which is normal android lifecycle. Your camera response will be in the `resume` event. [Android Quirk](https://github.com/apache/cordova-plugin-camera?tab=readme-ov-file#android-quirks)

If the app is fatally crashing (completely closes, potentially with "App stopped working" dialog, then it is likely related to `RecoverableSecurityException` error which is indirectly fixed by https://github.com/apache/cordova-plugin-camera/pull/907
