### ISSUE TITLE
Camera wont open on OnePlus Node.

### ISSUE THREAD

**Issue by pradeep531** [apache/cordova-plugin-camera#818]
**Problem** 
Camera wont open on OnePlus Nord . Works as intended on every other device we have tested with, including emulators.

### What is expected to happen?
Camera opens, and pictures can be taken.

### What does actually happen?
Nothing happens.

## Information
![image](https://user-images.githubusercontent.com/79002834/205861270-4f5ca06a-4434-4b9c-bf7f-233549171f0e.png)

**Comment by jcesarmobile** [comment]
what's your plugin version and the android version of the device where you are testing?
can you provide a sample app?

**Comment by jcesarmobile** [comment]
closing since there was no response
