### ISSUE TITLE
Does this plugin support cordova-android@9.x.x and above?

### ISSUE THREAD

**Issue by DONGNEZHA** [apache/cordova-plugin-camera#819]
Apache Cordova uses GitHub Issues as a feature request and bug tracker _only_.
For usage and support questions, please check out the resources below. Thanks!

---

You can get answers to your usage and support questions about **Apache Cordova** on:

* Slack Community Chat: https://cordova.slack.com (you can sign-up at http://slack.cordova.io/)
* StackOverflow: https://stackoverflow.com/questions/tagged/cordova using the tag `cordova`

---

If you are using a tool that uses Cordova internally, like e.g. Ionic, check their support channels:

* **Ionic Framework**
  * [Ionic Community Forum](https://forum.ionicframework.com/)
  * [Ionic Worldwide Slack](https://ionicworldwide.herokuapp.com/)
* **PhoneGap**
  * [PhoneGap Developer Community](https://forums.adobe.com/community/phonegap)

**Comment by DONGNEZHA** [comment]
I am using cordova-android@9.x.x but I am prompted with "Failed because:  Class not found".
```
navigator.camera.getPicture(onSuccess, onFail, { quality: 50,
    destinationType: Camera.DestinationType.FILE_URI });

function onSuccess(imageURI) {
    var image = document.getElementById('myImage');
    image.src = imageURI;
}

function onFail(message) {
    alert('Failed because: ' + message);
}
```

**Comment by breautek** [comment]
Modern versions of this plugin depends on AndroidX support libraries which cordova-android@9 has limited/buggy support for.

You'll need to use cordova-android@10 or later with the current release of cordova-plugin-camera. You can refer to the [Release Notes](https://github.com/apache/cordova-plugin-camera/blob/master/RELEASENOTES.md) to see when the platform requirements has changed.

Additionally, if you intend to deploy to Google Play store, then you'll need cordova-android@11 for API 31+ support.

**Comment by DONGNEZHA** [comment]
However, I still have this problem with cordova-plugin-camera@5.0.3 as well.
