### ISSUE TITLE
Taking screenshot while camera is active crashes app on android devices

### ISSUE THREAD

**Issue by aaronngkk** [apache/cordova-plugin-camera#823]
## Problem
Application restarts and crashes if user takes a screenshot while camera is active, snaps picture and presses "OK"

### Command or Code
<img width="805" alt="image" src="https://user-images.githubusercontent.com/122949685/213066701-79b1c993-49f0-4ad1-9253-234c614b9b9b.png">

<img width="692" alt="image" src="https://user-images.githubusercontent.com/122949685/213070001-d2cf6649-579b-418a-a57e-da27ad0738ea.png">

### Version information

OS: Android 11 
node -v : 14.21.1
cordova -v : 10.0.0 (cordova-lib@10.1.0)
"cordova-plugin-camera": "^6.0.0"

### Logs
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/122949685/213069481-c288ad43-3248-4d78-af8c-465ca147f4ea.png">

**Comment by breautek** [comment]
Potentially related to https://github.com/apache/cordova-plugin-camera/issues/679 with an open PR https://github.com/apache/cordova-plugin-camera/pull/781

If you could try testing that PR to see if it will solve your issue

```
cordova plugin remove cordova-plugin-camera
cordova plugin add https://github.com/dongourdet/cordova-plugin-camera.git#android-recoverable-security-exception
```

**Comment by breautek** [comment]
Fixed by https://github.com/apache/cordova-plugin-camera/pull/907
