### ISSUE TITLE
The plugin uses deprecated navigator.getUserMedia function, can't take a picture

### ISSUE THREAD

**Issue by romulko** [apache/cordova-plugin-camera#830]
# Bug Report

## Problem
The plugin uses the deprecated navigator.getUserMedia function that is currently missing.

### What is expected to happen?
To have the ability to take a picture from a browser.

### What does actually happen?
When I try to take a picture, it shows "Browser does not support camera :("

## Information

![IMG_0734](https://user-images.githubusercontent.com/524402/231703075-f49b7aaf-5b4a-4d5b-b678-c5e472c8d54f.jpg)

### Environment, Platform, Device

Ipad 6 (16.2), Chrome 110.

### Version information

cordova-plugin-camera: 6.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
this was fixed [here](https://github.com/apache/cordova-plugin-camera/pull/810)

but it's not released yet

**Comment by romulko** [comment]
@jcesarmobile When do you plane to release a new version?
