### ISSUE TITLE
OnResume dosen't get triggered when the photo is taken (Android)

### ISSUE THREAD

**Issue by matheus-inacio** [apache/cordova-plugin-camera#837]
# Bug Report

## Problem

I've subcribed to the `onResume` as documented, but i only get the event triggered (with the proper `pendingResult` value) when i cancel the photo. 

### What is expected to happen?

The app should be notified via the `onResume` event, with the taken photo.

### What does actually happen?

If i take the photo, the app restarts but the `onResume` event never gets fired.

## Information

I've had users reporting the issue on Redmi Note 7.

I'm simulating the issue by enabling `Don't keep activities` on the dev options.

![image](https://github.com/apache/cordova-plugin-camera/assets/29243277/2cf1b318-f7d9-4c73-9e10-41f92ee56d47)

### Environment, Platform, Device

Android (8.1 and 13)

### Version information
Plugin version: [6.0.0](https://github.com/apache/cordova-plugin-camera/releases/tag/6.0.0)
Tested on android 8.1 and 13

**Comment by goncalo-tomas** [comment]
Hello, the same issue is happening in our application.
However I'm using the outsystems fork:
https://github.com/OutSystems/cordova-plugin-camera/tree/4.2.0-OS41

Some users with the following devices are having this issue were after taking the picture the app restarts:
 Redmi Note 11  -> Android 12
 Samsung S21 FE -> Android 13
 
 I was also able to replicate this issue by enabling "Don't keep activities" on the dev options.

**Comment by matheus-inacio** [comment]
@goncalo-tomas My app is also using the OutSystems fork.

I've created a cordova app from scratch and the `resume` event triggered correctly, so i guess this may not be an issue in this repo.
