### ISSUE TITLE
Npm publish for version 7.0.0

### ISSUE THREAD

**Issue by hieunguyen2211** [apache/cordova-plugin-camera#852]
Hi, I see that the latest version 7.0.0 has been released but it is unavailable on the npm repo, therefore, I cannot install the latest version via npm (workaround: install via git). Do you guys have any plan or when will version 7.0.0 be published to the npm repo?

**Comment by erisu** [comment]
It is not released yet.

**Comment by erisu** [comment]
For additional information:

The presence of the git tag labeled `7.0.0` does not indicate an official release. An official release tag would be named `rel/7.0.0`, which, at present, does not exist.

The `7.0.0` tag serves a specific purpose within the Apache release voting process. Think of it as a preliminary or draft tag. It is possible that this tag may be removed if the release vote does not succeed.

In the Apache Cordova project, the voting process mandates that the vote remains open for a minimum of 48 hours and requires a minimum of 2+1 binding votes in favor for the release to be considered successful.
