### ISSUE TITLE
This all work good but when trying to open video camera or picking videos from gallery this still gives error 20 > @cyril23 Here a fork inspired from the work of https://github.com/jalios. Work perfectly on Android 13, 7 and 8 🎉

### ISSUE THREAD

**Issue by adeel399** [apache/cordova-plugin-camera#862]
> @cyril23 Here a fork inspired from the work of https://github.com/jalios. Work perfectly on Android 13, 7 and 8 🎉
> 
> https://github.com/DaedalusDev/cordova-plugin-camera/

**Thanks a lot** for your work! I've tested it, too on the following the devices - **everything works perfectly**:
- Android 7.0, Medion LifeTab X10302 (the only tablet in my tests)
- Android 7.1.2, Zebra TC 25
- Android 8.0.0, Samsung Galaxy S7
- Android 8.1.0, Nexus 5X (LG H791)
- Android 11, Newland NFT 10
- Android 13, OnePlus 9 Pro
- Android 13, Pixel 7
- (iOS 16.5.1, iPhone 11 Pro)

> Using Cordova the jalios branch works fine under Android 12 and 13 (didn't test others).
I believe Apache should merge this into the main branch urgently as of next month targeting SDK 33 is required for Android / Google PlayStore. Thanks all for the community effort to solve this.

yes, but I would recommend DaedalusDev' Branch on https://github.com/DaedalusDev/cordova-plugin-camera/ (I mean his merge request) because of its Android 7-8 downwards compability.

_Originally posted by @cyril23 in https://github.com/apache/cordova-plugin-camera/issues/826#issuecomment-1618408989_

**Comment by adeel399** [comment]
opening simple camera and taking picture is working but opening video camera or loading videos does not work still gives error 20 .
i used npm i https://github.com/jalios/cordova-plugin-camera.git

**Comment by breautek** [comment]
If you have an issue with a fork of the plugin, than you must seek the maintainer of the fork. Apache cannot provide assistance or make an action against forks.
