### ISSUE TITLE
cameraDirection 在android13 平板中Camera.Direction.FRONT 无效 部分手机可以使用

### ISSUE THREAD

**Issue by wangguoyu0518** [apache/cordova-plugin-camera#863]
是有什么别的问题吗？ 
<img width="1279" alt="image" src="https://github.com/apache/cordova-plugin-camera/assets/42727078/c4cfae3b-7495-4d48-9d41-b416511d0ab9">

**Comment by breautek** [comment]
Please include an English translation

**Comment by jcesarmobile** [comment]
Android doesn't support setting the camera direction.
It's documented on the quirks section
https://github.com/apache/cordova-plugin-camera#android-quirks-1
