### ISSUE TITLE
On iOS 16+ when you open camera it crashes and closes the app

### ISSUE THREAD

**Issue by kristapspicelevics** [apache/cordova-plugin-camera#864]
# Bug Report

## Problem

On iOS 16+ when you open camera it crashes and closes the camera

### What is expected to happen?

The camera should open

### What does actually happen?

App crashes when you open camera

It also gives warning as follows:

**Attempted to change to mode Portrait with an unsupported device (BackWide). Auto device for both positions unsupported, returning Auto device for same position anyway (BackAuto).**

## Information

Before mentioned warning does not appear with iOS 15.7.2 and below

const options: CameraOptions = {
  quality: 90,
  destinationType: Camera.DestinationType.FILE_URI,
  encodingType: Camera.EncodingType.JPEG,
  mediaType: Camera.MediaType.PICTURE,
  sourceType: Camera.PictureSourceType.CAMERA,
  correctOrientation: true,
  targetWidth: 700
}

### Command or Code

await Camera.getPicture(options).then((result) => {
    ...
});

### Environment, Platform, Device

iPhone 17.0.3 iOS version 

### Version information

cordova-plugin-version: 6.0.0
Ionic 5.5.2
xCode 15.0

## Checklist

- [ x ] I searched for existing GitHub issues
- [ x ] I updated all Cordova tooling to most recent version
- [ x ] I included all the necessary information above

**Comment by erisu** [comment]
Looks like you're using an old version of the plugin. Also I think this issue was resolved in version 7.x.

I would recommend to try upgrading and testing. You most likely will also need to upgrade the platforms too.

**Comment by kristapspicelevics** [comment]
I looked into plugins RELEASENOTES.md i found no mention of iOS 16 or above

**Comment by kristapspicelevics** [comment]
I updated the plugin, seems to be working, closing the issue.
