### ISSUE TITLE
Could not resolve androidx.core:core:1.6.+.

### ISSUE THREAD

**Issue by tmwebs** [apache/cordova-plugin-camera#880]
when I install this plugin I get an error message:

Could not resolve androidx.core:core:1.6.+.

and I can't build the android application.

Installed platforms:
android 12.0.1
ios 6.1.0

cordova version
12.0.0 (cordova-lib@12.0.1)

**Comment by breautek** [comment]
`androidx.core:core:1.6.+` [definitely exists](https://mvnrepository.com/artifact/androidx.core/core/1.6.0)

Can you include the full build output or a [sample reproduction app](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md)?

**Comment by tmwebs** [comment]
I managed to solve it, it was a connection problem, it was not downloading the dependencies. Thank you.
