### ISSUE TITLE
error in plugin.xml

### ISSUE THREAD

**Issue by Nanahuatzin** [apache/cordova-plugin-camera#888]
# Bug Report

## Problem

# Bug Report

## Problem

After compiling my Cordova project, my AndroidManifest.xml file breaks at this line:

<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="32" />

### What is expected to happen?

The project should compile correctly without errors.

### What does actually happen?

The compilation fails due to the aforementioned line in the AndroidManifest.xml.

## Information

In the plugin.xml file of the cordova-plugin-camera, on line 58, there is this line:

<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="32" />

it should be <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

### Command or Code

Add the project in Cordova and compile.

### Environment, Platform, Device

Cordova V13, Android, running on Windows 10.

### Version information

Cordova: 13.0.0
Node: 18.0.0
cordova-plugin-camera: Latest version

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="32" />

### What is expected to happen?

I will compile correctly

## Information

In the line 58 of the current there is this line.

<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="32" />

it should be <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

### Command or Code

add the proyect in cordova and compile

### Environment, Platform, Device

Cordova V13,  android, runing on windows 10.

### Version information

Cordova, android 13.0.0
node 18.0.0

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by jcesarmobile** [comment]
The line is correct, that permission shouldn’t be requested on SDKs over 32, if it’s conflicting with another plugin, it’s the other plugin that should be updated to declare the permission like this plugin does
